#!/usr/bin/env bash
# Static gates for the WP13 character-visuals increment, the same set the
# previous WP13 increments ran: parser and SETGLOBAL per changed file and
# tree-wide, the five plain-5.1 sweeps scoped to the changed Lua and then
# tree-wide over mods/*/grug_* and tools, and the fresh-server audit.
set -uo pipefail
export LC_ALL=C
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd -P)"
cd "$repo"
LUAC="$repo/tools/bin/luac51"

CHANGED=(
	mods/PLAYER/grug_visuals/init.lua
	mods/PLAYER/grug_visuals/compose.lua
	mods/PLAYER/grug_visuals/apply.lua
	mods/PLAYER/grug_classes/init.lua
	mods/ITEMS/grug_gear/init.lua
	mods/ENTITIES/grug_mobs/init.lua
	mods/ENTITIES/grug_mobs/levels.lua
	mods/ENTITIES/grug_mobs/guard.lua
	mods/ENTITIES/grug_mobs/bandit.lua
	mods/ENTITIES/grug_mobs/mirefolk.lua
	mods/ENTITIES/grug_traders/vendors.lua
	tools/wp13/character_visuals_kat.lua
)

echo "== parser and SETGLOBAL on every Lua file this increment changed =="
for file in "${CHANGED[@]}"; do
	if "$LUAC" -p "$file" >/dev/null 2>&1; then
		globals="$("$LUAC" -p -l "$file" | grep -c SETGLOBAL)"
		echo "$file parser PASS; SETGLOBAL [$globals]"
	else
		echo "$file parser FAIL"
	fi
done

echo "== whole tree parses =="
find mods -name '*.lua' -path 'mods/*/grug_*' -print0 |
	xargs -0 "$LUAC" -p && echo "mods/*/grug_* parser PASS"
find tools -name '*.lua' -print0 | xargs -0 "$LUAC" -p &&
	echo "tools parser PASS"

sweeps() {
	local index=1
	for pattern in \
		'(^|[^[:alnum:]_.:])goto[[:space:](]|::[A-Za-z_]+::' \
		'\\u\{|\\x[0-9A-Fa-f]|\\z' \
		'table\.(unpack|pack|move)|rawlen|coroutine\.isyieldable|math\.(type|tointeger)|utf8\.' \
		'[^:/]//|[[:alnum:]_)"] *(&|\||<<|>>) *[[:alnum:]_("]' \
		'\brequire[[:space:]]*\(|io\.popen|os\.(execute|exit)|\bminetest\.'; do
		echo "SWEEP $index"
		grep -rnE "$pattern" "$@" --include=*.lua
		index=$((index + 1))
	done
	echo "SWEEPS DONE (no output above a SWEEP line means zero hits)"
}

echo "== five plain-5.1 sweeps, scoped to the Lua this increment changed =="
sweeps "${CHANGED[@]}"

echo "== the same five sweeps over all of mods/*/grug_* and tools =="
sweeps mods/*/grug_* tools

echo "== fresh server check =="
python3 tools/check_fresh_server.py

echo "== every media file of the new mod has a LICENSE-media.md row =="
missing=0
for png in mods/PLAYER/grug_visuals/textures/*.png; do
	name="$(basename "$png")"
	if grep -qF "\`$name\`" mods/PLAYER/grug_visuals/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
echo "media rows missing: $missing"

echo "== the art is reproducible from its generator =="
before="$(sha256sum mods/PLAYER/grug_visuals/textures/*.png | sha256sum)"
python3 tools/wp13/gen_character_visuals.py >/dev/null
after="$(sha256sum mods/PLAYER/grug_visuals/textures/*.png | sha256sum)"
if [[ "$before" == "$after" ]]; then
	echo "regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi
