name = grug_alchemy
title = Grudgelands Alchemy
description = Alchemist recipes, potions, elixirs and gathering authority.
depends = grug_brewing, grug_jobs, grug_core, grug_classes, grug_abilities, grug_traders, grug_mobs, grug_gathering, grug_cooking, grug_inventory, grug_materials, vessels, default
