-- Kezamba's one hole in the pad: the CENOTE. And the RAVINE, which was a
-- ROUTE and is now empty.
--
-- GENERATED by `tools/wp13/kezamba_water.lua --emit` (deleted in Round 22 with
-- the old static hydrology; restore it from git only if the mask must be
-- re-cut). Do not hand-edit. Since Round 22 Phase 5 the water itself is the
-- authored lake `kezamba_cenote` of `wp40/water_authored.lua`: the same
-- four-capsule chain, so inside the 95 x 95 core its wet columns are exactly
-- this LAGOON mask (checked on three seeds when the lake was authored, lane
-- W2b).
--
-- WHY A CAPITAL CORE HAS A MASK AT ALL. The capitals contract's section 1 says
-- "the 96 x 96 civic core is flat at the fitted reference height". At Kezamba
-- it is flat over 6 380 of its 9 025 columns and not over the other 2 645, and
-- that exception is WP40's own authored geometry rather than noise:
--
--   * THE CENOTE, four basins at fixed world coordinates whose north-east
--     wedge reaches into the core. Its surface stands TWO nodes below the
--     fitted civic reference on every seed (the piers at y -2..-1 stand in
--     it, the decks at y 0 keep a node of air over it).
--   * THE RAVINE IS EMPTY, and the story is worth keeping. Until WP40's routes
--     were taught to END at the capital gates (the wave-2 route lane, main
--     `0518a01b`), one graded ROUTE CORRIDOR ran diagonally through the pad
--     from its south-west edge and cut up to 26 nodes into it. This fixture
--     measured that as a ravine, and the composition was built around it as a
--     gorge. With the routes stopping at the gate points, every dry column of
--     the core stands at the reference on all nine seeds and the union is zero
--     columns wide. The mask stays in the module as an API and a GUARD: the
--     composition still refuses to lay a lane or stand a stilt in a ravine
--     column, so if a later terrain package cuts the pad again, `--verify`
--     turns red here and the refusals fire there.
--
-- Plain Lua 5.1, pure, no engine calls, no globals.

local function loader()
	local M = {}

	-- The core's own half-extent, and the fitted reference and lake surface
	-- the old static plan gave on the fixture seeds (historical: the reference
	-- is fitted per seed now and the surface is two nodes below it).
	M.REACH = 47
	M.ENVELOPE = 256
	M.REFERENCE_Y = 66
	M.WATER_SURFACE_Y = 65
	M.LAGOON_COLUMNS = 30354
	M.RAVINE_COLUMNS = 0

	-- Inclusive x runs per z. A wedge and a band are a few hundred bytes this
	-- way and nine thousand as a bitmap.
	local LAGOON = {
		{-10, {110, 110}},
		{-9, {94, 122}},
		{-8, {50, 50}, {63, 127}},
		{-7, {39, 131}},
		{-6, {34, 134}},
		{-5, {31, 136}},
		{-4, {28, 139}},
		{-3, {25, 141}},
		{-2, {23, 143}},
		{-1, {20, 145}},
		{0, {18, 147}},
		{1, {17, 149}},
		{2, {15, 150}},
		{3, {13, 152}},
		{4, {12, 153}},
		{5, {11, 155}},
		{6, {9, 156}},
		{7, {8, 157}},
		{8, {7, 158}},
		{9, {6, 159}},
		{10, {4, 160}},
		{11, {3, 162}},
		{12, {2, 163}},
		{13, {1, 164}},
		{14, {0, 164}},
		{15, {0, 165}},
		{16, {-1, 166}},
		{17, {-2, 167}},
		{18, {-3, 168}},
		{19, {-4, 169}},
		{20, {-4, 170}},
		{21, {-5, 170}},
		{22, {-6, 171}},
		{23, {-7, 172}},
		{24, {-7, 172}},
		{25, {-8, 173}},
		{26, {-8, 174}},
		{27, {-9, 174}},
		{28, {-10, 175}},
		{29, {-10, 175}},
		{30, {-11, 176}},
		{31, {-11, 176}},
		{32, {-11, 177}},
		{33, {-12, 177}},
		{34, {-12, 178}},
		{35, {-13, 178}},
		{36, {-13, 179}},
		{37, {-13, 179}},
		{38, {-14, 179}},
		{39, {-14, 180}},
		{40, {-14, 180}},
		{41, {-15, 181}},
		{42, {-15, 181}},
		{43, {-15, 181}},
		{44, {-16, 182}},
		{45, {-16, 182}},
		{46, {-16, 182}},
		{47, {-16, 182}},
		{48, {-16, 183}},
		{49, {-17, 183}},
		{50, {-17, 183}},
		{51, {-17, 183}},
		{52, {-17, 183}},
		{53, {-17, 184}},
		{54, {-17, 184}},
		{55, {-17, 184}},
		{56, {-17, 184}},
		{57, {-17, 184}},
		{58, {-17, 184}},
		{59, {-17, 184}},
		{60, {-18, 185}},
		{61, {-17, 185}},
		{62, {-17, 186}},
		{63, {-17, 186}},
		{64, {-17, 187}},
		{65, {-17, 187}},
		{66, {-18, 188}},
		{67, {-18, 188}},
		{68, {-18, 189}},
		{69, {-19, 189}},
		{70, {-19, 189}},
		{71, {-20, 190}},
		{72, {-21, 190}},
		{73, {-22, 191}},
		{74, {-22, 191}},
		{75, {-23, 192}},
		{76, {-24, 193}},
		{77, {-25, 194}},
		{78, {-25, 195}},
		{79, {-26, 196}},
		{80, {-26, 197}},
		{81, {-27, 198}},
		{82, {-27, 198}},
		{83, {-28, 199}},
		{84, {-28, 200}},
		{85, {-29, 200}},
		{86, {-29, 201}},
		{87, {-29, 202}},
		{88, {-30, 202}},
		{89, {-30, 203}},
		{90, {-30, 203}},
		{91, {-31, 204}},
		{92, {-31, 204}},
		{93, {-31, 204}},
		{94, {-31, 205}},
		{95, {-31, 205}},
		{96, {-31, 205}},
		{97, {-31, 206}},
		{98, {-31, 206}},
		{99, {-31, 206}},
		{100, {-32, 206}},
		{101, {-31, 207}},
		{102, {-31, 207}},
		{103, {-31, 207}},
		{104, {-31, 207}},
		{105, {-31, 207}},
		{106, {-31, 207}},
		{107, {-31, 207}},
		{108, {-31, 207}},
		{109, {-31, 207}},
		{110, {-30, 208}},
		{111, {-30, 207}},
		{112, {-30, 207}},
		{113, {-29, 207}},
		{114, {-29, 207}},
		{115, {-29, 207}},
		{116, {-28, 207}},
		{117, {-28, 207}},
		{118, {-27, 207}},
		{119, {-27, 207}},
		{120, {-26, 206}},
		{121, {-26, 206}},
		{122, {-25, 206}},
		{123, {-25, 206}},
		{124, {-24, 205}},
		{125, {-23, 205}},
		{126, {-22, 205}},
		{127, {-22, 204}},
		{128, {-21, 44}, {46, 204}},
		{129, {-20, 41}, {51, 204}},
		{130, {-19, 39}, {56, 203}},
		{131, {-18, 38}, {61, 203}},
		{132, {-17, 37}, {66, 202}},
		{133, {-15, 35}, {71, 202}},
		{134, {-14, 34}, {76, 201}},
		{135, {-13, 33}, {81, 200}},
		{136, {-11, 31}, {86, 200}},
		{137, {-9, 29}, {89, 199}},
		{138, {-7, 27}, {93, 198}},
		{139, {-5, 25}, {98, 198}},
		{140, {-2, 22}, {110, 110}, {113, 197}},
		{141, {1, 19}, {116, 196}},
		{142, {10, 10}, {118, 195}},
		{143, {121, 194}},
		{144, {124, 193}},
		{145, {127, 192}},
		{146, {129, 191}},
		{147, {130, 190}},
		{148, {131, 189}},
		{149, {133, 187}},
		{150, {134, 186}},
		{151, {136, 184}},
		{152, {137, 183}},
		{153, {139, 181}},
		{154, {141, 179}},
		{155, {144, 176}},
		{156, {147, 173}},
		{157, {151, 169}},
		{158, {160, 160}},
	}
	local RAVINE = {

	}

	-- Row lookup, built once at load: 95 small arrays rather than a linear
	-- scan per query, because the core composition asks for every one of its
	-- 9 025 columns at least twice.
	local function index(rows)
		local by_z = {}
		for entry = 1, #rows do
			local row = rows[entry]
			by_z[row[1]] = row
		end
		return by_z
	end
	local LAGOON_BY_Z = index(LAGOON)
	local RAVINE_BY_Z = index(RAVINE)

	local function member(by_z, x, z)
		local row = by_z[z]
		if row == nil then return false end
		for entry = 2, #row do
			if x >= row[entry][1] and x <= row[entry][2] then return true end
		end
		return false
	end

	-- Is this column open water?
	function M.lagoon(x, z) return member(LAGOON_BY_Z, x, z) end
	-- Is this column inside the ravine, or on its rim?
	function M.ravine(x, z) return member(RAVINE_BY_Z, x, z) end
	-- Is this column ground the composition may build on?
	function M.pad(x, z)
		return not member(LAGOON_BY_Z, x, z) and not member(RAVINE_BY_Z, x, z)
	end

	-- Does the rectangle stand wholly on the pad? The composition asks this of
	-- every plot before it stamps it, so a part cannot be laid half over the
	-- lake the way a prop once was laid half over another plot at Dawnmere.
	function M.pad_area(x1, z1, x2, z2)
		for z = z1, z2 do
			for x = x1, x2 do
				if not M.pad(x, z) then return false, x, z end
			end
		end
		return true
	end

	-- The shore: a pad column with open water within one node of it. The quay,
	-- the anglers and the stilt platforms all stand on these.
	function M.shore(x, z)
		if not M.pad(x, z) then return false end
		for dz = -1, 1 do
			for dx = -1, 1 do
				if M.lagoon(x + dx, z + dz) then return true end
			end
		end
		return false
	end

	return M
end

return loader
