-- Where Kezamba's fifty-two plots stand, and why they are not a grid.
--
-- HIGHCOURT'S LOTS ARE A GRID AND KEZAMBA'S CANNOT BE. `highcourt_quadrants.lua`
-- authors one nine-lot grid and four fill slots, rotates them into each
-- quadrant and lets the world seed permute which district takes which quadrant.
-- That works because Highcourt's four quadrants are interchangeable ground.
--
-- Kezamba's are not, and the measurement says so rather than the eye:
-- `tools/wp13/kezamba_water.lua` finds an AUTHORED LAKE -- WP40's
-- `hydro_kezamba_cenote` -- filling 11.5 per cent of the 512 envelope and
-- essentially the whole north-east quadrant, in the same columns on all NINE
-- seeds of `tools/wp13/capital_anchor_fixture.lua`. A quadrant permutation over
-- ground like that would put a district in the water in three worlds out of
-- four, so Kezamba's districts are pinned to the ground that exists:
--
--   * `shore`   the market and trades quarter, south-east;
--   * `vine`    the residential and cultural quarter, south-west;
--   * `canopy`  the martial and garrison quarter, west and north-west;
--   * `totem`   the lore and spiritual quarter, on the lake's far bank.
--
-- and the count per district follows the ground too: 9, 9, 11 and 7 building
-- lots -- thirty-six, the Highcourt standard -- plus four fill lots each.
-- `canopy` carries eleven and `totem` seven because the west strip has room for
-- them and the far bank does not: the packer finds only seven legal reach-13
-- centres north of the lake that are not 170 nodes from their own district.
-- That is a measurement (`kezamba_lots.lua pack`), not a preference, and it is
-- the one place Kezamba departs from Highcourt's four-times-nine.
--
-- THE POSITIONS ARE SEARCHED, NOT AUTHORED. Every row below came out of
--
--     luajit tools/wp13/kezamba_lots.lua <repo> pack
--
-- which packs each district's lots nearest-its-spine-first out of the centres
-- that pass `tools/wp13/capital_plots.lua`'s own four rules -- dry, inside the
-- foundation skirt, under its own cleared airspace, off the core, the gate
-- corridors, the avenues and the ring street -- on all nine seeds. And
--
--     luajit tools/wp13/kezamba_lots.lua <repo> check
--
-- is the committed gate that re-asks those questions of exactly this table.
--
-- Plain Lua 5.1, pure, no engine calls, no globals.

local function loader()
	local M = {}

	-- Contract section 2.1's district roles, in the order the districts are
	-- resolved and the manifest's fields are written.
	M.ROLES = {"market_trades", "residential_cultural", "martial_garrison",
		"lore_spiritual"}

	-- The four districts, in that role order. `spine` is only documentation:
	-- it is the point the packer measured its distances from.
	M.DISTRICTS = {
		{key = "shore", role = "market_trades", spine = {x = 128, z = -112}},
		{key = "vine", role = "residential_cultural",
			spine = {x = -128, z = -112}},
		{key = "canopy", role = "martial_garrison", spine = {x = -136, z = 112}},
		{key = "totem", role = "lore_spiritual", spine = {x = 32, z = 184}},
	}

	-- GENERATED by `luajit tools/wp13/kezamba_lots.lua <repo> pack`, and since
	-- 2026-09-16 REPAIRED rather than repacked where the ground moved under it:
	--
	--     luajit tools/wp13/kezamba_lots.lua <repo> repair
	--
	-- keeps every legal lot and moves only an illegal one, which is the right
	-- tool when a terrain package shifts the ground under a city that already
	-- stands (the Highcourt precedent, `docs/research/wp13-capital-terrain.md`
	-- section 3). ONE row is not the packer's: `totem_f2`, which the
	-- `cenote_terrace` apron of 2026-09-16 left looking up a 33-node slope
	-- inside its own clear and which `repair` moved ten nodes and dropped from
	-- a reach of 11 to 8 -- there is no reach-11 centre left on the lake's north
	-- bank, and there was none before the apron either (twelve in the whole
	-- totem band, all of them in the far north-east corner).
	--
	-- `luajit tools/wp13/kezamba_lots.lua <repo> check` re-asks the predicate of
	-- exactly this table on all nine seeds and is the committed gate.
	local LOTS = {
		{id = "shore_1", kind = "plot", x = 124, z = -112, reach = 13},
		{id = "shore_2", kind = "plot", x = 156, z = -112, reach = 13},
		{id = "shore_3", kind = "plot", x = 132, z = -80, reach = 13},
		{id = "shore_4", kind = "plot", x = 92, z = -116, reach = 13},
		{id = "shore_5", kind = "plot", x = 128, z = -156, reach = 13},
		{id = "shore_6", kind = "plot", x = 188, z = -112, reach = 13},
		{id = "shore_7", kind = "plot", x = 128, z = -48, reach = 13},
		{id = "shore_8", kind = "plot", x = 160, z = -148, reach = 13},
		{id = "shore_9", kind = "plot", x = 164, z = -80, reach = 13},
		{id = "shore_f1", kind = "fill", x = 96, z = -148, reach = 11},
		{id = "shore_f2", kind = "fill", x = 60, z = -116, reach = 11},
		{id = "shore_f3", kind = "fill", x = 128, z = -184, reach = 8},
		{id = "shore_f4", kind = "fill", x = 108, z = -88, reach = 5},

		{id = "vine_1", kind = "plot", x = -136, z = -112, reach = 13},
		{id = "vine_2", kind = "plot", x = -104, z = -116, reach = 13},
		{id = "vine_3", kind = "plot", x = -128, z = -80, reach = 13},
		{id = "vine_4", kind = "plot", x = -168, z = -108, reach = 13},
		{id = "vine_5", kind = "plot", x = -128, z = -156, reach = 13},
		{id = "vine_6", kind = "plot", x = -160, z = -144, reach = 13},
		{id = "vine_7", kind = "plot", x = -128, z = -48, reach = 13},
		{id = "vine_8", kind = "plot", x = -96, z = -148, reach = 13},
		{id = "vine_9", kind = "plot", x = -200, z = -112, reach = 13},
		{id = "vine_f1", kind = "fill", x = -72, z = -116, reach = 11},
		{id = "vine_f2", kind = "fill", x = -160, z = -76, reach = 11},
		{id = "vine_f3", kind = "fill", x = -128, z = -184, reach = 8},
		{id = "vine_f4", kind = "fill", x = -84, z = -84, reach = 5},

		{id = "canopy_1", kind = "plot", x = -136, z = 112, reach = 13},
		{id = "canopy_2", kind = "plot", x = -168, z = 112, reach = 13},
		{id = "canopy_3", kind = "plot", x = -136, z = 80, reach = 13},
		{id = "canopy_4", kind = "plot", x = -136, z = 144, reach = 13},
		{id = "canopy_5", kind = "plot", x = -104, z = 116, reach = 13},
		{id = "canopy_6", kind = "plot", x = -200, z = 112, reach = 13},
		{id = "canopy_7", kind = "plot", x = -168, z = 80, reach = 13},
		{id = "canopy_8", kind = "plot", x = -168, z = 144, reach = 13},
		{id = "canopy_9", kind = "plot", x = -136, z = 48, reach = 13},
		{id = "canopy_10", kind = "plot", x = -136, z = 176, reach = 13},
		{id = "canopy_11", kind = "plot", x = -104, z = 148, reach = 13},
		{id = "canopy_f1", kind = "fill", x = -72, z = 116, reach = 11},
		{id = "canopy_f2", kind = "fill", x = -200, z = 80, reach = 11},
		{id = "canopy_f3", kind = "fill", x = -196, z = 140, reach = 8},
		{id = "canopy_f4", kind = "fill", x = -112, z = 92, reach = 5},

		{id = "totem_1", kind = "plot", x = 32, z = 184, reach = 13},
		{id = "totem_2", kind = "plot", x = 68, z = 184, reach = 13},
		{id = "totem_3", kind = "plot", x = -32, z = 184, reach = 13},
		{id = "totem_4", kind = "plot", x = 100, z = 180, reach = 13},
		{id = "totem_5", kind = "plot", x = -64, z = 184, reach = 13},
		{id = "totem_6", kind = "plot", x = -46, z = 152, reach = 13},
		{id = "totem_7", kind = "plot", x = -100, z = 184, reach = 13},
		{id = "totem_f1", kind = "fill", x = 32, z = 214, reach = 11},
		{id = "totem_f2", kind = "fill", x = 60, z = 158, reach = 8},
		{id = "totem_f3", kind = "fill", x = 56, z = 210, reach = 8},
		{id = "totem_f4", kind = "fill", x = 32, z = 160, reach = 5},
	}

	-- The lots of one district, in authored order, building lots first and
	-- then fill lots -- which is the order the district rosters are written in
	-- and the order `kezamba_districts.lua` resolves them in.
	function M.of(key)
		local plots, fill = {}, {}
		for index = 1, #LOTS do
			local lot = LOTS[index]
			if lot.id:sub(1, #key + 1) == key .. "_" then
				if lot.kind == "plot" then plots[#plots + 1] = lot
				else fill[#fill + 1] = lot end
			end
		end
		return plots, fill
	end

	function M.all() return LOTS end

	return M
end

return loader
