-- Canonical material and mining-tier owner (WP43, Round 24; items_crafting.md §3.0).

grug_materials = {}

local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath .. "/registry.lua")
dofile(modpath .. "/mining.lua")

-- THE ROCK TILES, one line per rock (Round 24). Stored textures generated by
-- `tools/r24_art/build_rock_ore_textures.py` (LICENSE-media.md §1, §9).
-- Tier rocks read as the same stone, darker, slightly cooler and more cracked
-- with depth; the decorative rocks are clearly different from stone.
local ROCK_TILES = {
	t2_stone = "grug_materials_t2_stone.png",
	t3_stone = "grug_materials_t3_stone.png",
	t4_stone = "grug_materials_t4_stone.png",
	t5_stone = "grug_materials_t5_stone.png",
	t6_stone = "grug_materials_t6_stone.png",
	slate = "grug_materials_slate.png",
	basalt = "grug_materials_basalt.png",
	granite = "grug_materials_granite.png",
}

-- Tier rocks 2..6 (ruling 1). Tier 1 is `default:stone` (overrides.lua).
-- All drop Cobble, so no player can place hard rock.
for i = 2, #grug_materials.TIERS do
	local tier = grug_materials.TIERS[i]
	local key = tier.node:match("^grug_materials:(.+)$")
	core.register_node(tier.node, {
		description = grug_materials.tier_rock_description(i),
		tiles = {ROCK_TILES[key]},
		groups = {cracky = 3, level = grug_materials.level_for_tier(i),
			grug_natural = 1, grug_stratum = i},
		drop = "default:cobble",
		is_ground_content = true,
		sounds = default.node_sound_stone_defaults(),
	})
end

-- Decorative rocks (ruling 8): any pick, drop themselves, never an ore host.
for _, rock in ipairs(grug_materials.DECORATIVE_ROCKS) do
	core.register_node(rock.node, {
		description = rock.name,
		tiles = {ROCK_TILES[rock.key]},
		groups = {cracky = 3, grug_natural = 1, grug_decorative_rock = 1},
		drop = rock.node,
		is_ground_content = true,
		sounds = default.node_sound_stone_defaults(),
	})
end

dofile(modpath .. "/ores.lua")
dofile(modpath .. "/derivatives.lua")
-- tools.lua first: it moves default's four tool grades into this namespace,
-- and overrides.lua then edits the canonical names.
dofile(modpath .. "/tools.lua")
dofile(modpath .. "/overrides.lua")
dofile(modpath .. "/content_curation.lua")
dofile(modpath .. "/dig_sounds.lua")
dofile(modpath .. "/tool_lifetimes.lua")
-- Round 24 ruling 29: "Requires level N" on every T2+ pick, axe and shovel,
-- after the lifetime pass has written their final descriptions.
grug_materials.apply_tool_level_tooltips()
dofile(modpath .. "/audit.lua")
