-- The Basic recipe catalog (Round 45, round45-plan.md §3 and §4.2): every
-- profession-free recipe as an ingredient list. Converted from the engine
-- grid routes of the base commit by tools/r45_rg/gen_basic_recipes.lua
-- (its --check compares); edit it as data from
-- now on and rerun nothing. registry.lua registers each row in the
-- "basic" area and makes the loop-made families below.
return {
	recipes = {
		{output = "beds:bed_bottom", count = 1, ingredients = {{item = "wool:white", n = 3}, {group = "wood", n = 3}}},
		{output = "beds:fancy_bed_bottom", count = 1, ingredients = {{group = "stick", n = 1}, {item = "wool:white", n = 3}, {group = "wood", n = 3}}},
		{output = "default:acacia_wood", count = 1, ingredients = {{item = "default:acacia_bush_stem", n = 1}}},
		{output = "default:acacia_wood", count = 4, ingredients = {{item = "default:acacia_tree", n = 1}}},
		{output = "default:aspen_wood", count = 4, ingredients = {{item = "default:aspen_tree", n = 1}}},
		{output = "default:book", count = 1, ingredients = {{item = "default:paper", n = 3}}},
		{output = "default:bookshelf", count = 1, ingredients = {{group = "wood", n = 6}, {item = "default:book", n = 3}}},
		{output = "default:brick", count = 1, ingredients = {{item = "default:clay_brick", n = 4}}},
		{output = "default:chest", count = 1, ingredients = {{group = "wood", n = 8}}},
		{output = "default:chest_locked", count = 1, ingredients = {{item = "default:chest", n = 1}, {item = "grug_materials:iron_bar", n = 1}}},
		{output = "default:chest_locked", count = 1, ingredients = {{group = "wood", n = 8}, {item = "grug_materials:iron_bar", n = 1}}},
		{output = "default:clay", count = 1, ingredients = {{item = "default:clay_lump", n = 4}}},
		{output = "default:clay_brick", count = 4, ingredients = {{item = "default:brick", n = 1}}},
		{output = "default:clay_lump", count = 4, ingredients = {{item = "default:clay", n = 1}}},
		{output = "default:coal_lump", count = 9, ingredients = {{item = "default:coalblock", n = 1}}},
		{output = "default:coalblock", count = 1, ingredients = {{item = "default:coal_lump", n = 9}}},
		{output = "default:desert_sand", count = 4, ingredients = {{item = "default:desert_sandstone", n = 1}}},
		{output = "default:desert_sandstone", count = 1, ingredients = {{item = "default:desert_sand", n = 4}}},
		{output = "default:desert_sandstone_block", count = 9, ingredients = {{item = "default:desert_sandstone", n = 9}}},
		{output = "default:desert_sandstone_brick", count = 4, ingredients = {{item = "default:desert_sandstone", n = 4}}},
		{output = "default:desert_stone_block", count = 9, ingredients = {{item = "default:desert_stone", n = 9}}},
		{output = "default:desert_stonebrick", count = 4, ingredients = {{item = "default:desert_stone", n = 4}}},
		{output = "default:emergent_jungle_sapling", count = 1, ingredients = {{item = "default:junglesapling", n = 9}}},
		{output = "default:fence_acacia_wood", count = 4, ingredients = {{item = "default:acacia_wood", n = 4}, {group = "stick", n = 2}}},
		{output = "default:fence_aspen_wood", count = 4, ingredients = {{item = "default:aspen_wood", n = 4}, {group = "stick", n = 2}}},
		{output = "default:fence_junglewood", count = 4, ingredients = {{item = "default:junglewood", n = 4}, {group = "stick", n = 2}}},
		{output = "default:fence_pine_wood", count = 4, ingredients = {{item = "default:pine_wood", n = 4}, {group = "stick", n = 2}}},
		{output = "default:fence_rail_acacia_wood", count = 16, ingredients = {{item = "default:acacia_wood", n = 4}}},
		{output = "default:fence_rail_aspen_wood", count = 16, ingredients = {{item = "default:aspen_wood", n = 4}}},
		{output = "default:fence_rail_junglewood", count = 16, ingredients = {{item = "default:junglewood", n = 4}}},
		{output = "default:fence_rail_pine_wood", count = 16, ingredients = {{item = "default:pine_wood", n = 4}}},
		{output = "default:fence_rail_wood", count = 16, ingredients = {{item = "default:wood", n = 4}}},
		{output = "default:fence_wood", count = 4, ingredients = {{item = "default:wood", n = 4}, {group = "stick", n = 2}}},
		{output = "default:furnace", count = 1, ingredients = {{group = "stone", n = 8}}},
		{output = "default:junglewood", count = 4, ingredients = {{item = "default:jungletree", n = 1}}},
		{output = "default:ladder_wood", count = 5, ingredients = {{group = "stick", n = 7}}},
		{output = "default:large_cactus_seedling", count = 1, ingredients = {{item = "default:cactus", n = 5}}},
		{output = "default:obsidian", count = 1, ingredients = {{item = "default:obsidian_shard", n = 9}}},
		{output = "default:obsidian_block", count = 9, ingredients = {{item = "default:obsidian", n = 9}}},
		{output = "default:obsidian_shard", count = 9, ingredients = {{item = "default:obsidian", n = 1}}},
		{output = "default:obsidianbrick", count = 4, ingredients = {{item = "default:obsidian", n = 4}}},
		{output = "default:paper", count = 1, ingredients = {{item = "default:papyrus", n = 3}}},
		{output = "default:pine_wood", count = 1, ingredients = {{item = "default:pine_bush_stem", n = 1}}},
		{output = "default:pine_wood", count = 4, ingredients = {{item = "default:pine_tree", n = 1}}},
		{output = "default:sand", count = 4, ingredients = {{item = "default:sandstone", n = 1}}},
		{output = "default:sandstone", count = 1, ingredients = {{item = "default:sand", n = 4}}},
		{output = "default:sandstone_block", count = 9, ingredients = {{item = "default:sandstone", n = 9}}},
		{output = "default:sandstonebrick", count = 4, ingredients = {{item = "default:sandstone", n = 4}}},
		{output = "default:sign_wall_wood", count = 3, ingredients = {{group = "wood", n = 6}, {group = "stick", n = 1}}},
		{output = "default:snow", count = 9, ingredients = {{item = "default:snowblock", n = 1}}},
		{output = "default:snowblock", count = 1, ingredients = {{item = "default:snow", n = 9}}},
		{output = "default:stick", count = 4, ingredients = {{group = "wood", n = 2}}},
		{output = "default:stone_block", count = 9, ingredients = {{item = "default:stone", n = 9}}},
		{output = "default:stonebrick", count = 4, ingredients = {{item = "default:stone", n = 4}}},
		{output = "default:torch", count = 4, ingredients = {{item = "default:coal_lump", n = 1}, {group = "stick", n = 1}}},
		{output = "default:wood", count = 1, ingredients = {{item = "default:bush_stem", n = 1}}},
		{output = "default:wood", count = 4, ingredients = {{item = "default:tree", n = 1}}},
		{output = "doors:door_glass", count = 1, ingredients = {{item = "default:glass", n = 6}}},
		{output = "doors:door_obsidian_glass", count = 1, ingredients = {{item = "default:obsidian_glass", n = 6}}},
		{output = "doors:door_wood", count = 1, ingredients = {{group = "wood", n = 6}}},
		{output = "doors:gate_acacia_wood_closed", count = 1, ingredients = {{group = "stick", n = 4}, {item = "default:acacia_wood", n = 2}}},
		{output = "doors:gate_aspen_wood_closed", count = 1, ingredients = {{group = "stick", n = 4}, {item = "default:aspen_wood", n = 2}}},
		{output = "doors:gate_junglewood_closed", count = 1, ingredients = {{group = "stick", n = 4}, {item = "default:junglewood", n = 2}}},
		{output = "doors:gate_pine_wood_closed", count = 1, ingredients = {{group = "stick", n = 4}, {item = "default:pine_wood", n = 2}}},
		{output = "doors:gate_wood_closed", count = 1, ingredients = {{group = "stick", n = 4}, {item = "default:wood", n = 2}}},
		{output = "doors:trapdoor", count = 2, ingredients = {{group = "wood", n = 6}}},
		{output = "dye:black", count = 4, ingredients = {{group = "coal", n = 1}}},
		{output = "dye:blue", count = 2, ingredients = {{item = "dye:cyan", n = 1}, {item = "dye:magenta", n = 1}}},
		{output = "dye:brown", count = 2, ingredients = {{item = "dye:orange", n = 1}, {item = "dye:black", n = 1}}},
		{output = "dye:brown", count = 2, ingredients = {{item = "dye:red", n = 1}, {item = "dye:green", n = 1}}},
		{output = "dye:cyan", count = 2, ingredients = {{item = "dye:green", n = 1}, {item = "dye:blue", n = 1}}},
		{output = "dye:dark_green", count = 2, ingredients = {{item = "dye:green", n = 1}, {item = "dye:black", n = 1}}},
		{output = "dye:dark_grey", count = 2, ingredients = {{item = "dye:grey", n = 1}, {item = "dye:black", n = 1}}},
		{output = "dye:dark_grey", count = 2, ingredients = {{item = "dye:blue", n = 1}, {item = "dye:orange", n = 1}}},
		{output = "dye:dark_grey", count = 2, ingredients = {{item = "dye:yellow", n = 1}, {item = "dye:violet", n = 1}}},
		{output = "dye:green", count = 2, ingredients = {{item = "dye:yellow", n = 1}, {item = "dye:blue", n = 1}}},
		{output = "dye:green", count = 2, ingredients = {{item = "dye:cyan", n = 1}, {item = "dye:yellow", n = 1}}},
		{output = "dye:green", count = 2, ingredients = {{item = "dye:white", n = 1}, {item = "dye:dark_green", n = 1}}},
		{output = "dye:grey", count = 2, ingredients = {{item = "dye:white", n = 1}, {item = "dye:black", n = 1}}},
		{output = "dye:grey", count = 2, ingredients = {{item = "dye:white", n = 1}, {item = "dye:dark_grey", n = 1}}},
		{output = "dye:magenta", count = 2, ingredients = {{item = "dye:pink", n = 1}, {item = "dye:violet", n = 1}}},
		{output = "dye:orange", count = 2, ingredients = {{item = "dye:yellow", n = 1}, {item = "dye:red", n = 1}}},
		{output = "dye:pink", count = 2, ingredients = {{item = "dye:white", n = 1}, {item = "dye:red", n = 1}}},
		{output = "dye:red", count = 2, ingredients = {{item = "dye:yellow", n = 1}, {item = "dye:magenta", n = 1}}},
		{output = "dye:violet", count = 2, ingredients = {{item = "default:blueberries", n = 1}}},
		{output = "dye:violet", count = 2, ingredients = {{item = "dye:magenta", n = 1}, {item = "dye:blue", n = 1}}},
		{output = "dye:violet", count = 2, ingredients = {{item = "dye:red", n = 1}, {item = "dye:blue", n = 1}}},
		{output = "grug_artisans:hardened_wood", count = 1, ingredients = {{item = "grug_artisans:polished_wood", n = 1}, {group = "wood", n = 1}}},
		{output = "grug_artisans:heartwood_wood", count = 1, ingredients = {{item = "grug_artisans:lacquered_wood", n = 1}, {group = "wood", n = 1}}},
		{output = "grug_artisans:inlaid_wood", count = 1, ingredients = {{item = "grug_artisans:hardened_wood", n = 1}, {group = "wood", n = 1}}},
		{output = "grug_artisans:lacquered_wood", count = 1, ingredients = {{item = "grug_artisans:inlaid_wood", n = 1}, {group = "wood", n = 1}}},
		{output = "grug_artisans:polished_wood", count = 1, ingredients = {{item = "grug_artisans:seasoned_wood", n = 1}, {group = "wood", n = 1}}},
		{output = "grug_artisans:seasoned_wood", count = 1, ingredients = {{group = "wood", n = 2}}},
		{output = "grug_farming:empty_iron_bucket", count = 1, ingredients = {{item = "grug_materials:iron_bar", n = 3}}},
		{output = "grug_farming:hoe", count = 1, ingredients = {{group = "wood", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_abyssal_steel", count = 1, ingredients = {{item = "grug_materials:abyssal_steel_bar", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_bronze", count = 1, ingredients = {{item = "grug_materials:bronze_bar", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_embersteel", count = 1, ingredients = {{item = "grug_materials:embersteel_bar", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_iron", count = 1, ingredients = {{item = "grug_materials:iron_bar", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_silversteel", count = 1, ingredients = {{item = "grug_materials:silversteel_bar", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_steel", count = 1, ingredients = {{item = "grug_materials:steel_bar", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:hoe_stone", count = 1, ingredients = {{group = "stone", n = 2}, {item = "default:stick", n = 2}}},
		{output = "grug_farming:seed_bamboo_shoot", count = 2, ingredients = {{item = "grug_cooking:bamboo_shoot", n = 1}}},
		{output = "grug_farming:seed_blightberry", count = 2, ingredients = {{item = "grug_cooking:blightberry", n = 1}}},
		{output = "grug_farming:seed_carrot", count = 2, ingredients = {{item = "grug_cooking:carrot", n = 1}}},
		{output = "grug_farming:seed_cassava", count = 2, ingredients = {{item = "grug_cooking:cassava", n = 1}}},
		{output = "grug_farming:seed_cave_cap", count = 2, ingredients = {{item = "grug_cooking:cave_cap", n = 1}}},
		{output = "grug_farming:seed_corn", count = 2, ingredients = {{item = "grug_gathering:corn", n = 1}}},
		{output = "grug_farming:seed_ember_moss", count = 2, ingredients = {{item = "grug_cooking:ember_moss", n = 1}}},
		{output = "grug_farming:seed_fire_pepper", count = 2, ingredients = {{item = "grug_cooking:fire_pepper", n = 1}}},
		{output = "grug_farming:seed_frost_melon", count = 2, ingredients = {{item = "grug_cooking:frost_melon", n = 1}}},
		{output = "grug_farming:seed_jungle_berry", count = 2, ingredients = {{item = "grug_cooking:jungle_berry", n = 1}}},
		{output = "grug_farming:seed_potato", count = 2, ingredients = {{item = "grug_gathering:potato", n = 1}}},
		{output = "grug_farming:seed_pumpkin", count = 2, ingredients = {{item = "grug_cooking:pumpkin", n = 1}}},
		{output = "grug_farming:seed_salt_crust", count = 2, ingredients = {{item = "grug_cooking:salt_crust", n = 1}}},
		{output = "grug_farming:seed_sugar_cane", count = 2, ingredients = {{item = "grug_cooking:sugar_cane", n = 1}}},
		{output = "grug_farming:seed_sunberry", count = 2, ingredients = {{item = "grug_cooking:sunberry", n = 1}}},
		{output = "grug_farming:seed_wild_grain", count = 2, ingredients = {{item = "grug_cooking:wild_grain", n = 1}}},
		{output = "grug_farming:seed_wild_onion", count = 2, ingredients = {{item = "grug_cooking:wild_onion", n = 1}}},
		{output = "grug_fishing:rod", count = 1, ingredients = {{item = "default:stick", n = 3}, {item = "grug_professions:thread", n = 2}}},
		{output = "grug_gear:arrow", count = 100, ingredients = {{item = "grug_materials:bronze_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:abyssal_crystal", count = 9, ingredients = {{item = "grug_materials:abyssal_crystal_block", n = 1}}},
		{output = "grug_materials:abyssal_crystal_block", count = 1, ingredients = {{item = "grug_materials:abyssal_crystal", n = 9}}},
		{output = "grug_materials:abyssal_steel_bar", count = 9, ingredients = {{item = "grug_materials:abyssal_steel_block", n = 1}}},
		{output = "grug_materials:abyssal_steel_block", count = 1, ingredients = {{item = "grug_materials:abyssal_steel_bar", n = 9}}},
		{output = "grug_materials:axe_abyssal_steel", count = 1, ingredients = {{item = "grug_materials:abyssal_steel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_bronze", count = 1, ingredients = {{item = "grug_materials:bronze_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_embersteel", count = 1, ingredients = {{item = "grug_materials:embersteel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_iron", count = 1, ingredients = {{item = "grug_materials:iron_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_silversteel", count = 1, ingredients = {{item = "grug_materials:silversteel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_steel", count = 1, ingredients = {{item = "grug_materials:steel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_stone", count = 1, ingredients = {{group = "stone", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:axe_wood", count = 1, ingredients = {{group = "wood", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:bronze_bar", count = 9, ingredients = {{item = "grug_materials:bronze_block", n = 1}}},
		{output = "grug_materials:bronze_block", count = 1, ingredients = {{item = "grug_materials:bronze_bar", n = 9}}},
		{output = "grug_materials:citrine_block", count = 1, ingredients = {{item = "grug_materials:cut_citrine", n = 9}}},
		{output = "grug_materials:copper_bar", count = 9, ingredients = {{item = "grug_materials:copper_block", n = 1}}},
		{output = "grug_materials:copper_block", count = 1, ingredients = {{item = "grug_materials:copper_bar", n = 9}}},
		{output = "grug_materials:cut_citrine", count = 9, ingredients = {{item = "grug_materials:citrine_block", n = 1}}},
		{output = "grug_materials:cut_diamond", count = 9, ingredients = {{item = "grug_materials:diamond_block", n = 1}}},
		{output = "grug_materials:cut_garnet", count = 9, ingredients = {{item = "grug_materials:garnet_block", n = 1}}},
		{output = "grug_materials:cut_jade", count = 9, ingredients = {{item = "grug_materials:jade_block", n = 1}}},
		{output = "grug_materials:cut_ruby", count = 9, ingredients = {{item = "grug_materials:ruby_block", n = 1}}},
		{output = "grug_materials:cut_sapphire", count = 9, ingredients = {{item = "grug_materials:sapphire_block", n = 1}}},
		{output = "grug_materials:diamond_block", count = 1, ingredients = {{item = "grug_materials:cut_diamond", n = 9}}},
		{output = "grug_materials:emberglass", count = 9, ingredients = {{item = "grug_materials:emberglass_block", n = 1}}},
		{output = "grug_materials:emberglass_block", count = 1, ingredients = {{item = "grug_materials:emberglass", n = 9}}},
		{output = "grug_materials:embersteel_bar", count = 9, ingredients = {{item = "grug_materials:embersteel_block", n = 1}}},
		{output = "grug_materials:embersteel_block", count = 1, ingredients = {{item = "grug_materials:embersteel_bar", n = 9}}},
		{output = "grug_materials:garnet_block", count = 1, ingredients = {{item = "grug_materials:cut_garnet", n = 9}}},
		{output = "grug_materials:gold_bar", count = 9, ingredients = {{item = "grug_materials:gold_block", n = 1}}},
		{output = "grug_materials:gold_block", count = 1, ingredients = {{item = "grug_materials:gold_bar", n = 9}}},
		{output = "grug_materials:iron_bar", count = 9, ingredients = {{item = "grug_materials:iron_block", n = 1}}},
		{output = "grug_materials:iron_block", count = 1, ingredients = {{item = "grug_materials:iron_bar", n = 9}}},
		{output = "grug_materials:jade_block", count = 1, ingredients = {{item = "grug_materials:cut_jade", n = 9}}},
		{output = "grug_materials:pick_abyssal_steel", count = 1, ingredients = {{item = "grug_materials:abyssal_steel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_bronze", count = 1, ingredients = {{item = "grug_materials:bronze_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_embersteel", count = 1, ingredients = {{item = "grug_materials:embersteel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_iron", count = 1, ingredients = {{item = "grug_materials:iron_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_silversteel", count = 1, ingredients = {{item = "grug_materials:silversteel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_steel", count = 1, ingredients = {{item = "grug_materials:steel_bar", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_stone", count = 1, ingredients = {{group = "stone", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:pick_wood", count = 1, ingredients = {{group = "wood", n = 3}, {group = "stick", n = 2}}},
		{output = "grug_materials:ruby_block", count = 1, ingredients = {{item = "grug_materials:cut_ruby", n = 9}}},
		{output = "grug_materials:sapphire_block", count = 1, ingredients = {{item = "grug_materials:cut_sapphire", n = 9}}},
		{output = "grug_materials:shovel_abyssal_steel", count = 1, ingredients = {{item = "grug_materials:abyssal_steel_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_bronze", count = 1, ingredients = {{item = "grug_materials:bronze_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_embersteel", count = 1, ingredients = {{item = "grug_materials:embersteel_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_iron", count = 1, ingredients = {{item = "grug_materials:iron_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_silversteel", count = 1, ingredients = {{item = "grug_materials:silversteel_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_steel", count = 1, ingredients = {{item = "grug_materials:steel_bar", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_stone", count = 1, ingredients = {{group = "stone", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:shovel_wood", count = 1, ingredients = {{group = "wood", n = 1}, {group = "stick", n = 2}}},
		{output = "grug_materials:silver_bar", count = 9, ingredients = {{item = "grug_materials:silver_block", n = 1}}},
		{output = "grug_materials:silver_block", count = 1, ingredients = {{item = "grug_materials:silver_bar", n = 9}}},
		{output = "grug_materials:silversteel_bar", count = 9, ingredients = {{item = "grug_materials:silversteel_block", n = 1}}},
		{output = "grug_materials:silversteel_block", count = 1, ingredients = {{item = "grug_materials:silversteel_bar", n = 9}}},
		{output = "grug_materials:steel_bar", count = 9, ingredients = {{item = "grug_materials:steel_block", n = 1}}},
		{output = "grug_materials:steel_block", count = 1, ingredients = {{item = "grug_materials:steel_bar", n = 9}}},
		{output = "grug_materials:tin_bar", count = 9, ingredients = {{item = "grug_materials:tin_block", n = 1}}},
		{output = "grug_materials:tin_block", count = 1, ingredients = {{item = "grug_materials:tin_bar", n = 9}}},
		{output = "grug_mobs:heavy_leather", count = 1, ingredients = {{item = "grug_professions:cured_leather", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_mobs:light_leather", count = 1, ingredients = {{item = "mobs:leather", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_mobs:scaled_hide", count = 1, ingredients = {{item = "grug_mobs:heavy_leather", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:bolt_heavy", count = 1, ingredients = {{item = "grug_mobs:heavy_cloth", n = 2}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:bolt_patch", count = 1, ingredients = {{item = "grug_mobs:linen_scrap", n = 2}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:bolt_silk", count = 1, ingredients = {{item = "grug_mobs:spider_silk", n = 2}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:bolt_silkweave", count = 1, ingredients = {{item = "grug_professions:bolt_heavy", n = 1}, {item = "grug_mobs:spider_silk", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:bolt_stormweave", count = 1, ingredients = {{item = "grug_mobs:spider_silk", n = 1}, {item = "grug_gathering:stormkelp", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:bolt_woven", count = 1, ingredients = {{item = "grug_mobs:linen_cloth", n = 2}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:cured_leather", count = 1, ingredients = {{item = "grug_mobs:light_leather", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:metal_rod_abyssal_steel", count = 4, ingredients = {{item = "grug_materials:abyssal_steel_bar", n = 2}}},
		{output = "grug_professions:metal_rod_bronze", count = 4, ingredients = {{item = "grug_materials:bronze_bar", n = 2}}},
		{output = "grug_professions:metal_rod_embersteel", count = 4, ingredients = {{item = "grug_materials:embersteel_bar", n = 2}}},
		{output = "grug_professions:metal_rod_iron", count = 4, ingredients = {{item = "grug_materials:iron_bar", n = 2}}},
		{output = "grug_professions:metal_rod_silversteel", count = 4, ingredients = {{item = "grug_materials:silversteel_bar", n = 2}}},
		{output = "grug_professions:metal_rod_steel", count = 4, ingredients = {{item = "grug_materials:steel_bar", n = 2}}},
		{output = "grug_professions:nightscale_leather", count = 1, ingredients = {{item = "grug_mobs:scaled_hide", n = 1}, {item = "grug_mobs:sleek_pelt", n = 1}}},
		{output = "grug_professions:sleek_leather", count = 1, ingredients = {{item = "grug_mobs:sleek_pelt", n = 1}, {item = "grug_professions:thread", n = 1}}},
		{output = "grug_professions:thread", count = 2, ingredients = {{item = "grug_mobs:linen_scrap", n = 1}}},
		{output = "grug_smelting:dual_furnace", count = 1, ingredients = {{item = "grug_materials:copper_bar", n = 2}, {item = "default:furnace", n = 1}, {item = "grug_materials:tin_bar", n = 1}}},
		{output = "grug_trees:gravewood_wood", count = 4, ingredients = {{item = "grug_trees:gravewood_tree", n = 1}}},
		{output = "grug_trees:silverwood_wood", count = 4, ingredients = {{item = "grug_trees:silverwood_tree", n = 1}}},
		{output = "mobs:fence_top", count = 12, ingredients = {{group = "wood", n = 3}, {item = "default:fence_wood", n = 1}}},
		{output = "mobs:fence_wood", count = 4, ingredients = {{item = "default:fence_wood", n = 4}, {group = "stick", n = 2}}},
		{output = "mobs:meatblock", count = 1, ingredients = {{group = "food_meat", n = 9}}},
		{output = "mobs:meatblock_raw", count = 1, ingredients = {{group = "food_meat_raw", n = 9}}},
		{output = "vessels:drinking_glass", count = 14, ingredients = {{item = "default:glass", n = 7}}},
		{output = "vessels:glass_bottle", count = 10, ingredients = {{item = "default:glass", n = 5}}},
		{output = "vessels:glass_fragments", count = 1, ingredients = {{item = "vessels:drinking_glass", n = 2}}},
		{output = "vessels:glass_fragments", count = 1, ingredients = {{item = "vessels:glass_bottle", n = 2}}},
		{output = "vessels:shelf", count = 1, ingredients = {{group = "wood", n = 6}, {group = "vessel", n = 3}}},
		{output = "wool:black", count = 1, ingredients = {{item = "dye:black", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:blue", count = 1, ingredients = {{item = "dye:blue", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:brown", count = 1, ingredients = {{item = "dye:brown", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:cyan", count = 1, ingredients = {{item = "dye:cyan", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:dark_green", count = 1, ingredients = {{item = "dye:dark_green", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:dark_grey", count = 1, ingredients = {{item = "dye:dark_grey", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:green", count = 1, ingredients = {{item = "dye:green", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:grey", count = 1, ingredients = {{item = "dye:grey", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:magenta", count = 1, ingredients = {{item = "dye:magenta", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:orange", count = 1, ingredients = {{item = "dye:orange", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:pink", count = 1, ingredients = {{item = "dye:pink", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:red", count = 1, ingredients = {{item = "dye:red", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:violet", count = 1, ingredients = {{item = "dye:violet", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:white", count = 1, ingredients = {{item = "dye:white", n = 1}, {group = "wool", n = 1}}},
		{output = "wool:yellow", count = 1, ingredients = {{item = "dye:yellow", n = 1}, {group = "wool", n = 1}}},
		{output = "xpanes:door_steel_bar", count = 1, ingredients = {{item = "xpanes:bar_flat", n = 6}}},
		{output = "xpanes:obsidian_pane_flat", count = 16, ingredients = {{item = "default:obsidian_glass", n = 6}}},
		{output = "xpanes:pane_flat", count = 16, ingredients = {{item = "default:glass", n = 6}}},
		{output = "xpanes:trapdoor_steel_bar", count = 1, ingredients = {{item = "xpanes:bar_flat", n = 4}}},
	},
	-- {subname, block}: 8 stairs and 7 inner stairs from 6 blocks, 6 outer
	-- stairs from 4, 6 slabs from 3, back to 3 blocks from 4 stairs and to
	-- 1 block from 2 slabs.
	stairs = {
		{"acacia_wood", "default:acacia_wood"},
		{"aspen_wood", "default:aspen_wood"},
		{"brick", "default:brick"},
		{"cobble", "default:cobble"},
		{"desert_cobble", "default:desert_cobble"},
		{"desert_sandstone", "default:desert_sandstone"},
		{"desert_sandstone_block", "default:desert_sandstone_block"},
		{"desert_sandstone_brick", "default:desert_sandstone_brick"},
		{"desert_stone", "default:desert_stone"},
		{"desert_stone_block", "default:desert_stone_block"},
		{"desert_stonebrick", "default:desert_stonebrick"},
		{"glass", "default:glass"},
		{"ice", "default:ice"},
		{"junglewood", "default:junglewood"},
		{"mossycobble", "default:mossycobble"},
		{"obsidian", "default:obsidian"},
		{"obsidian_block", "default:obsidian_block"},
		{"obsidian_glass", "default:obsidian_glass"},
		{"obsidianbrick", "default:obsidianbrick"},
		{"pine_wood", "default:pine_wood"},
		{"sandstone", "default:sandstone"},
		{"sandstone_block", "default:sandstone_block"},
		{"sandstonebrick", "default:sandstonebrick"},
		{"snowblock", "default:snowblock"},
		{"stone", "default:stone"},
		{"stone_block", "default:stone_block"},
		{"stonebrick", "default:stonebrick"},
		{"wood", "default:wood"},
	},
	-- {wall, block}: 6 walls from 6 blocks.
	walls = {
		{"walls:cobble", "default:cobble"},
		{"walls:desertcobble", "default:desert_cobble"},
		{"walls:mossycobble", "default:mossycobble"},
	},
}
