grug_core = {}

-- World layout (docs/design/world.md §1): two separate continents, mirrored
-- at z = 0 — Elandor in the south (Accord, z negative) and Kragmar in the
-- north (Throng, z positive). Everything outside the two continent
-- rectangles is ocean: the strait along z = 0, the coastal ocean around
-- each continent and the deadly open sea beyond it (§2b).
--
-- The gameplay rectangle per faction is |x| <= CONTINENT_X_HALF and
-- CONTINENT_Z_MIN <= |z| <= CONTINENT_Z_MAX (3000x1600 by default). It is
-- the LEGAL bound (build rights, level field); the visible coastline is
-- soft and wanders inside it (grug_mapgen).
grug_core.CONTINENT_X_HALF = 1500
grug_core.CONTINENT_Z_MIN = 100 -- strait: |z| < 100 is always water
grug_core.CONTINENT_Z_MAX = 1700

-- Distance from a continent rectangle at which the coastal ocean ends and
-- the open sea (deadly guards, world.md §2b) begins.
grug_core.OCEAN_COASTAL_WIDTH = 1500

-- Derived geometry of one continent (all anchors below hang off the
-- constants above, so a world size change only touches them).
local X_HALF = grug_core.CONTINENT_X_HALF
local Z_MIN = grug_core.CONTINENT_Z_MIN
local Z_MAX = grug_core.CONTINENT_Z_MAX
-- Faction seat / continent center: (0, +-SEAT_Z).
local SEAT_Z = (Z_MIN + Z_MAX) / 2 -- 900
-- The safe core is a belt elongated along x (the three race capitals sit
-- side by side): inside |x| <= CORE_X_HALF the radial field ignores x.
local CORE_X_HALF = 300
-- Radial field scale: n = 1 (level 60) lands just short of the flank and
-- back coastlines, so the outermost land is elite everywhere. The z axis is
-- ASYMMETRIC: on the strait side of the seat the field must stretch (the
-- inner ring reaches down to z ~350, biomes_mobs §1.5 — otherwise players
-- walking to the 20-30 war coast would cross a lvl-35 belt first), while on
-- the back side the coast at dz = 800 has to reach 60.
local FIELD_X = 1150
local FIELD_Z_FRONT = 1000 -- strait side of the seat (|z| < SEAT_Z)
local FIELD_Z_BACK = 775 -- back side (|z| >= SEAT_Z)
-- War coast: the strait-facing band of a continent (world.md §1).
local WAR_COAST_Z = 300
-- The war-coast cap fades out as a ramp up to here, so the capped band
-- joins the radial field without a step (biomes_mobs §1.5: no >5 jumps).
local WAR_COAST_FADE_Z = 600
-- Coast band: the last nodes before a flank (|x|) or back (|z|) shoreline.
local COAST_BAND = 150
-- Below this depth every position counts as underground (cave content).
local UNDERGROUND_Y = -40

-- Race region bands along x within each continent (docs/design/world.md §7).
-- Bands overlap by 200 nodes; in the overlap the biome noise decides, which
-- gives an organic transition instead of a hard line.
grug_core.REGION_WEST_MAX = -500 -- west band: x <= -500
grug_core.REGION_CENTER_MIN = -700 -- center band: -700 <= x <= 700
grug_core.REGION_CENTER_MAX = 700
grug_core.REGION_EAST_MIN = 500 -- east band: x >= 500

-- Spawn camps (placeholder capitals until WP13 ships real structures):
-- a flat platform generated by grug_mapgen at every race capital. The
-- platform HEIGHT is terrain-adaptive: resolved lazily from the engine's
-- spawn level at the anchor (see below), persisted in mod storage — a fixed
-- y buried the camp inside hills (players spawned trapped in a pit).
grug_core.CAMP_HALF = 12 -- platform is (2*12+1)^2 nodes
grug_core.CAMP_PLATFORM_Y = 8 -- fallback/minimum platform y (above water)
grug_core.CAMP_PLATFORM_MAX_Y = 100 -- sanity cap (find_surface scans from 120)
grug_core.CAMP_CLEAR_HEIGHT = 64 -- air cleared this high above the platform

-- Vertical reach of every POI protection (world.md §2): a protected zone
-- starts this far BELOW the POI's base level and then runs upward without a
-- limit — nobody towers over a capital, nobody tunnels in right underneath
-- it, and deep mining below stays free. The horizontal extent belongs to the
-- POI: a spawn platform protects only its own footprint (CAMP_HALF), while
-- the real villages/outposts/capitals of WP13 also protect >= 10 nodes of
-- surrounding terrain.
grug_core.POI_PROTECT_DEPTH = 30

-- Three race capitals per continent (docs/design/world.md §3), all in the
-- safe-core belt: the central one (human/orc) is the faction seat, the
-- other two sit in their race's own band. Players spawn and respawn in
-- their OWN race's capital.
-- NB x/z are the ANCHOR of the capital; y comes from the terrain-adaptive
-- platform height — always go through grug_core.get_spawn_pos().
grug_core.capitals = {
	human = {faction = "accord", x = 0, z = -SEAT_Z, seat = true},
	dwarf = {faction = "accord", x = -550, z = -SEAT_Z},
	elf = {faction = "accord", x = 550, z = -SEAT_Z},
	orc = {faction = "throng", x = 0, z = SEAT_Z, seat = true},
	undead = {faction = "throng", x = -550, z = SEAT_Z},
	troll = {faction = "throng", x = 550, z = SEAT_Z},
}

grug_core.factions = {
	accord = {
		id = "accord",
		name = "Accord",
		color = "#3f6fce",
		seat_race = "human", -- capital of the faction seat (world.md §3)
	},
	throng = {
		id = "throng",
		name = "Throng",
		color = "#c41e3a",
		seat_race = "orc",
	},
}

--
-- Terrain-adaptive camp platform height. Decided exactly once per world and
-- per race capital, then persisted — a platform can never shift once built.
--
-- Source: core.get_spawn_level(x, z), the engine's own "where would a player
-- spawn here" query, resolved LAZILY on the first request. It is a pure
-- function of (x, z) served by the active Mapgen instance (l_mapgen.cpp ->
-- EmergeManager::getSpawnLevelAtPoint -> MapgenV7::getSpawnLevelAtPoint), so
-- it sees our mgv7_np_terrain_* overrides from grug_mapgen/init.lua and,
-- unlike the mapgen heightmap, does not depend on WHICH mapchunk happens to
-- ask, nor on the chunk's y range. That is the whole point: the previous
-- heightmap median could only be measured by the one mapchunk holding the
-- surface, which made both the value and the platform build order-dependent.
--
-- The engine answers with a PLAYER SPAWN level, which sits above the ground:
-- MapgenV7::getSpawnLevelAtPoint returns surface + 1 (allowance for full-node
-- biome 'dust'; + 2 when mgv7 runs with the `nomountains` flag) and
-- l_mapgen.cpp adds another + 1 ("'findSpawnPos()' in server.cpp adds at
-- least 1"). Our platform TOP layer has to end up AT the surface, hence -2.
--
-- nil means "unsuitable spawn point" and for mgv7 that is DETERMINISTIC, not
-- transient: inside a river channel, at/below water level, or wherever the
-- terrain rises above max(np_terrain_base.offset, np_terrain_alt.offset,
-- water_level + 16) — with our offsets that ceiling is y = 17, so a capital
-- on higher ground answers nil forever. Nothing is persisted then; the camp
-- pass falls back to the mapgen heightmap (grug_mapgen/structures.lua) and
-- every other caller keeps its CAMP_PLATFORM_Y fallback.
--
-- NB do not call this at load time: EmergeManager::getSpawnLevelAtPoint has
-- no mapgen before Server::init() runs initMapgens (server.cpp, after the
-- mods are loaded) and then answers 0, which arrives here as a bogus 1.
--

local SPAWN_LEVEL_TO_SURFACE = 2

local storage = core.get_mod_storage()

local function stored_platform_y(race_id)
	local y = storage:get_int("camp_platform_y:" .. race_id)
	if y == 0 then
		return nil -- not decided yet (real values are always >= 4)
	end
	return y
end

function grug_core.get_camp_platform_y(race_id)
	local y = stored_platform_y(race_id)
	if y then
		return y
	end
	local capital = grug_core.capitals[race_id]
	if not capital then
		return nil
	end
	local level = core.get_spawn_level(capital.x, capital.z)
	if not level then
		return nil -- unsuitable point, see above: caller decides what to do
	end
	return grug_core.set_camp_platform_y(race_id,
		level - SPAWN_LEVEL_TO_SURFACE)
end

-- Clamps y into the platform band, persists it (first writer wins — a
-- decided platform never moves) and returns the effective value.
function grug_core.set_camp_platform_y(race_id, y)
	local stored = stored_platform_y(race_id)
	if stored then
		return stored
	end
	y = math.min(math.max(math.floor(y), grug_core.CAMP_PLATFORM_Y),
		grug_core.CAMP_PLATFORM_MAX_Y)
	storage:set_int("camp_platform_y:" .. race_id, y)
	core.log("action",
		("[grug_core] %s capital platform decided at y=%d"):format(race_id, y))
	return y
end

-- Spawn position on the platform of a race capital (top layer + 1). An
-- unknown race — or one of the other faction (admin faction switch) —
-- falls back to the faction seat.
function grug_core.get_spawn_pos(faction_id, race_id)
	local faction = grug_core.factions[faction_id]
	local capital = race_id and grug_core.capitals[race_id]
	if not capital or capital.faction ~= faction_id then
		race_id = faction.seat_race
		capital = grug_core.capitals[race_id]
	end
	local y = grug_core.get_camp_platform_y(race_id)
		or grug_core.CAMP_PLATFORM_Y
	return vector.new(capital.x, y + 1, capital.z)
end

grug_core.faction_ids = {"accord", "throng"}

function grug_core.opposing_faction(faction_id)
	return faction_id == "accord" and "throng" or "accord"
end

--
-- Position fields (docs/design/world.md §1, biomes_mobs.md §1.1).
--

-- "accord" (southern continent), "throng" (northern continent) or "ocean"
-- (strait, coastal ocean, open sea — everything outside both rectangles).
function grug_core.territory_at(pos)
	if math.abs(pos.x) <= X_HALF then
		local z = pos.z
		if z >= Z_MIN and z <= Z_MAX then
			return "throng"
		elseif z <= -Z_MIN and z >= -Z_MAX then
			return "accord"
		end
	end
	return "ocean"
end

-- Radial field value around the faction seat of the nearer continent:
-- 0 at the seat, ~1 at the flank/back coastlines. The core belt is
-- elongated along x, so the three race capitals share one low-level zone;
-- the z axis uses the wider FRONT scale toward the strait (see above).
local function radial_n(pos)
	local az = math.abs(pos.z)
	local dx = math.max(math.abs(pos.x) - CORE_X_HALF, 0)
	local dz = math.abs(az - SEAT_Z)
	local field_z = az < SEAT_Z and FIELD_Z_FRONT or FIELD_Z_BACK
	return math.sqrt((dx / FIELD_X) ^ 2 + (dz / field_z) ^ 2)
end

-- Zone name at pos (the `_grug_spawn_zones` vocabulary, biomes_mobs §1.1):
-- "underground", "ocean", "strait", "war_coast", "coast", "core", "inner"
-- or "outer". Depth wins everywhere — caves are cave content regardless of
-- what lies above them.
function grug_core.zone_at(pos)
	if pos.y < UNDERGROUND_Y then
		return "underground"
	end
	local az = math.abs(pos.z)
	if grug_core.territory_at(pos) == "ocean" then
		if az > Z_MIN then
			return "ocean"
		end
		return "strait"
	end
	if az <= Z_MIN then
		return "strait"
	end
	if az <= WAR_COAST_Z then
		return "war_coast"
	end
	if X_HALF - math.abs(pos.x) <= COAST_BAND or Z_MAX - az <= COAST_BAND then
		return "coast"
	end
	local n = radial_n(pos)
	if n <= 0.30 then
		return "core"
	elseif n <= 0.55 then
		return "inner"
	end
	return "outer"
end

-- Mob level anchors on the radial field (world.md §1): safe core 1-10,
-- inner ring 10-25, outer ring 25-45, flank/back coasts up to 60.
local level_anchors = {
	{n = 0, level = 1},
	{n = 0.30, level = 10},
	{n = 0.55, level = 25},
	{n = 0.90, level = 45},
	{n = 1.00, level = 60},
}

-- Level of the mob field at radial value n, piecewise linear between the
-- anchors; everything beyond the last anchor stays at 60.
local function level_at_n(n)
	for i = 1, #level_anchors - 1 do
		local a, b = level_anchors[i], level_anchors[i + 1]
		if n <= b.n then
			return a.level + (n - a.n) / (b.n - a.n) * (b.level - a.level)
		end
	end
	return level_anchors[#level_anchors].level
end

-- War-coast cap (world.md §1): the strait-facing PvP stage stays at 20-30
-- up to |z| = WAR_COAST_Z, then the cap RAMPS to 60 until WAR_COAST_FADE_Z,
-- where it becomes a no-op. Without that ramp the capped band ended in an
-- 8-30 level step at |z| = 300 (biomes_mobs §1.5: no jumps > 5).
local function war_coast_cap(az)
	if az <= WAR_COAST_Z then
		return 20 + (az - Z_MIN) / (WAR_COAST_Z - Z_MIN) * 10
	end
	return 30 + (az - WAR_COAST_Z) / (WAR_COAST_FADE_Z - WAR_COAST_Z) * 30
end

-- Mob level for a hostile spawned at pos (1..60), or nil on the open water
-- surface (no leveled hostiles there; the deep-sea guards of world.md §2b
-- are hand-set). Radial field from the faction seat, then the two caps of
-- world.md §1 (war coast, strait) and the depth axis of combat_stats.md §3
-- — the safe core is only safe on the surface.
function grug_core.mob_level_at(pos)
	local ocean = grug_core.territory_at(pos) == "ocean"
	local az = math.abs(pos.z)
	-- Open/coastal sea surface only — the strait (|z| <= Z_MIN) keeps its
	-- level so its neutral wildlife (gulls/crabs, 1-5) has one.
	if ocean and az > Z_MIN and pos.y >= 0 then
		return nil
	end
	local level = level_at_n(radial_n(pos))
	if not ocean and az > Z_MIN and az <= WAR_COAST_FADE_Z then
		level = math.min(level, war_coast_cap(az))
	elseif az <= Z_MIN then
		level = math.min(level, 5) -- strait & beaches: harmless wildlife
	end
	if pos.y < 0 then
		level = math.max(level, math.min(60, 1 + math.floor(-pos.y / 20)))
	end
	return math.round(level)
end

-- Guard level at pos (20..70, WP6), or nil in the ocean. Runs INVERSE to
-- the mob field (world.md §1): elite city watch (60+) at the faction seat
-- and in the safe core, ~local mob level + 5 at the war coast — pushing
-- deeper means weaker mobs but ever harder guards.
function grug_core.guard_level_at(pos)
	if grug_core.territory_at(pos) == "ocean" then
		return nil
	end
	local level = math.max(65 - 45 * radial_n(pos),
		(grug_core.mob_level_at(pos) or 0) + 5)
	-- Elite city watch floor: world.md §1/§3 promise 60+ in ALL three race
	-- capitals and across the safe core, but the plain inverse field only
	-- reaches ~55 at the side capitals (x = +-550). zone_at runs on a
	-- SURFACE copy of pos — underground positions report "underground" and
	-- would otherwise lose the floor under the capitals.
	if grug_core.zone_at(vector.new(pos.x, 8, pos.z)) == "core" then
		level = math.max(level, 60)
	end
	return math.round(math.min(70, math.max(20, level)))
end

-- 0 (safe core) .. 1 (elite coasts), defined as (mob_level-1)/59 and
-- clamped; positions without a mob level (open water surface) count as 1.
function grug_core.difficulty_at(pos)
	local level = grug_core.mob_level_at(pos)
	if not level then
		return 1
	end
	return math.min(1, math.max(0, (level - 1) / 59))
end

-- Chebyshev distance from one continent rectangle (0 inside it).
local function rect_distance(pos, z_min, z_max)
	local ddx = math.max(math.abs(pos.x) - X_HALF, 0)
	local ddz = math.max(z_min - pos.z, pos.z - z_max, 0)
	return math.max(ddx, ddz)
end

-- True beyond the coastal ocean of BOTH continents (world.md §2b): the
-- open sea, where the oversized deep-sea guards live.
function grug_core.open_sea_at(pos)
	local d = math.min(rect_distance(pos, Z_MIN, Z_MAX),
		rect_distance(pos, -Z_MAX, -Z_MIN))
	return d > grug_core.OCEAN_COASTAL_WIDTH
end

-- Resolves a player name to a faction id ("throng"/"accord") or nil.
-- Overridden by grug_factions at load time; the stub keeps grug_core free of
-- dependencies on player mods.
function grug_core.get_player_faction(name)
	return nil
end

-- Resolves a player name to a race id ("human", "orc", ...) or nil — used
-- to pick the race capital to spawn at. Overridden by grug_classes at load
-- time (same stub pattern as get_player_faction).
function grug_core.get_player_race(name)
	return nil
end

-- Finds a safe surface position near pos (for spawns/teleports); the camp
-- platform makes this a no-op at race capitals, elsewhere it is a fallback.
function grug_core.find_surface(pos)
	for y = 120, -16, -1 do
		local p = vector.new(pos.x, y, pos.z)
		local node = core.get_node_or_nil(p)
		local below = core.get_node_or_nil(vector.offset(p, 0, -1, 0))
		if node and below and node.name == "air" and
				below.name ~= "air" and below.name ~= "ignore" and
				core.get_item_group(below.name, "liquid") == 0 then
			return p
		end
	end
	return pos
end

local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath .. "/protection.lua")
dofile(modpath .. "/combat.lua")
