grug_core = {}

-- World layout (docs/design/world.md §1): two separate continents, mirrored
-- at z = 0 — Elandor in the south (Accord, z negative) and Kragmar in the
-- north (Throng, z positive). Everything outside the two continent
-- rectangles is ocean: the strait along z = 0, the coastal ocean around
-- each continent and the deadly open sea beyond it (§2b).
--
-- The gameplay rectangle per faction is |x| <= CONTINENT_X_HALF and
-- CONTINENT_Z_MIN <= |z| <= CONTINENT_Z_MAX (3000x1600 by default). It is
-- the LEGAL bound (build rights, level field); the visible coastline is
-- soft and wanders inside it (grug_mapgen).
grug_core.CONTINENT_X_HALF = 1500
grug_core.CONTINENT_Z_MIN = 100 -- strait: |z| < 100 is always water
grug_core.CONTINENT_Z_MAX = 1700

grug_core.NEUTRAL_HALF_WIDTH = 64 -- TEMP: removed by WP18 T4 (biomes.lua rework)

-- Distance from a continent rectangle at which the coastal ocean ends and
-- the open sea (deadly guards, world.md §2b) begins.
grug_core.OCEAN_COASTAL_WIDTH = 1500

-- Derived geometry of one continent (all anchors below hang off the
-- constants above, so a world size change only touches them).
local X_HALF = grug_core.CONTINENT_X_HALF
local Z_MIN = grug_core.CONTINENT_Z_MIN
local Z_MAX = grug_core.CONTINENT_Z_MAX
-- Faction seat / continent center: (0, +-SEAT_Z).
local SEAT_Z = (Z_MIN + Z_MAX) / 2 -- 900
-- The safe core is a belt elongated along x (the three race capitals sit
-- side by side): inside |x| <= CORE_X_HALF the radial field ignores x.
local CORE_X_HALF = 300
-- Radial field scale: n = 1 (level 60) lands just short of the flank and
-- back coastlines, so the outermost land is elite everywhere.
local FIELD_X = 1150
local FIELD_Z = 775
-- War coast: the strait-facing band of a continent (world.md §1).
local WAR_COAST_Z = 300
-- Coast band: the last nodes before a flank (|x|) or back (|z|) shoreline.
local COAST_BAND = 150
-- Below this depth every position counts as underground (cave content).
local UNDERGROUND_Y = -40

-- Race region bands along x within each continent (docs/design/world.md §7).
-- Bands overlap by 200 nodes; in the overlap the biome noise decides, which
-- gives an organic transition instead of a hard line.
grug_core.REGION_WEST_MAX = -500 -- west band: x <= -500
grug_core.REGION_CENTER_MIN = -700 -- center band: -700 <= x <= 700
grug_core.REGION_CENTER_MAX = 700
grug_core.REGION_EAST_MIN = 500 -- east band: x >= 500

-- Spawn camps (placeholder capitals until WP13 ships real structures):
-- a flat platform generated by grug_mapgen at every race capital. The
-- platform HEIGHT is terrain-adaptive: decided once per world from the
-- mapgen heightmap around the capital (grug_mapgen/structures.lua),
-- persisted in mod storage — a fixed y buried the camp inside hills
-- (players spawned trapped in a pit).
grug_core.CAMP_HALF = 12 -- platform is (2*12+1)^2 nodes
grug_core.CAMP_PLATFORM_Y = 8 -- fallback/minimum platform y (above water)
grug_core.CAMP_CLEAR_HEIGHT = 64 -- air cleared this high above the platform
grug_core.CAMP_PROTECT_RADIUS = 20 -- square radius of the protected zone

-- Three race capitals per continent (docs/design/world.md §3), all in the
-- safe-core belt: the central one (human/orc) is the faction seat, the
-- other two sit in their race's own band. Players spawn and respawn in
-- their OWN race's capital.
-- NB x/z are the ANCHOR of the capital; y comes from the terrain-adaptive
-- platform height — always go through grug_core.get_spawn_pos().
grug_core.capitals = {
	human = {faction = "accord", x = 0, z = -SEAT_Z, seat = true},
	dwarf = {faction = "accord", x = -550, z = -SEAT_Z},
	elf = {faction = "accord", x = 550, z = -SEAT_Z},
	orc = {faction = "throng", x = 0, z = SEAT_Z, seat = true},
	undead = {faction = "throng", x = -550, z = SEAT_Z},
	troll = {faction = "throng", x = 550, z = SEAT_Z},
}

grug_core.factions = {
	accord = {
		id = "accord",
		name = "Accord",
		color = "#3f6fce",
		seat_race = "human", -- capital of the faction seat (world.md §3)
	},
	throng = {
		id = "throng",
		name = "Throng",
		color = "#c41e3a",
		seat_race = "orc",
	},
}

--
-- Terrain-adaptive camp platform height. Decided exactly once per world and
-- per race capital (the first mapchunk near the capital measures the
-- surrounding heightmap, see grug_mapgen/structures.lua) and persisted, so
-- a platform can never shift once built.
--

local storage = core.get_mod_storage()

function grug_core.get_camp_platform_y(race_id)
	local y = storage:get_int("camp_platform_y:" .. race_id)
	if y == 0 then
		return nil -- not decided yet (real values are always >= 4)
	end
	return y
end

function grug_core.set_camp_platform_y(race_id, y)
	if not grug_core.get_camp_platform_y(race_id) then
		storage:set_int("camp_platform_y:" .. race_id, y)
	end
end

-- Spawn position on the platform of a race capital (top layer + 1). An
-- unknown race — or one of the other faction (admin faction switch) —
-- falls back to the faction seat.
function grug_core.get_spawn_pos(faction_id, race_id)
	local faction = grug_core.factions[faction_id]
	local capital = race_id and grug_core.capitals[race_id]
	if not capital or capital.faction ~= faction_id then
		race_id = faction.seat_race
		capital = grug_core.capitals[race_id]
	end
	local y = grug_core.get_camp_platform_y(race_id)
		or grug_core.CAMP_PLATFORM_Y
	return vector.new(capital.x, y + 1, capital.z)
end

grug_core.faction_ids = {"accord", "throng"}

function grug_core.opposing_faction(faction_id)
	return faction_id == "accord" and "throng" or "accord"
end

--
-- Position fields (docs/design/world.md §1, biomes_mobs.md §1.1).
--

-- "accord" (southern continent), "throng" (northern continent) or "ocean"
-- (strait, coastal ocean, open sea — everything outside both rectangles).
function grug_core.territory_at(pos)
	if math.abs(pos.x) <= X_HALF then
		local z = pos.z
		if z >= Z_MIN and z <= Z_MAX then
			return "throng"
		elseif z <= -Z_MIN and z >= -Z_MAX then
			return "accord"
		end
	end
	return "ocean"
end

-- Radial field value around the faction seat of the nearer continent:
-- 0 at the seat, ~1 at the flank/back coastlines. The core belt is
-- elongated along x, so the three race capitals share one low-level zone.
local function radial_n(pos)
	local dx = math.max(math.abs(pos.x) - CORE_X_HALF, 0)
	local dz = math.abs(math.abs(pos.z) - SEAT_Z)
	return math.sqrt((dx / FIELD_X) ^ 2 + (dz / FIELD_Z) ^ 2)
end

-- Zone name at pos (the `_grug_spawn_zones` vocabulary, biomes_mobs §1.1):
-- "underground", "ocean", "strait", "war_coast", "coast", "core", "inner"
-- or "outer". Depth wins everywhere — caves are cave content regardless of
-- what lies above them.
function grug_core.zone_at(pos)
	if pos.y < UNDERGROUND_Y then
		return "underground"
	end
	local az = math.abs(pos.z)
	if grug_core.territory_at(pos) == "ocean" then
		if az > Z_MIN then
			return "ocean"
		end
		return "strait"
	end
	if az <= Z_MIN then
		return "strait"
	end
	if az <= WAR_COAST_Z then
		return "war_coast"
	end
	if X_HALF - math.abs(pos.x) <= COAST_BAND or Z_MAX - az <= COAST_BAND then
		return "coast"
	end
	local n = radial_n(pos)
	if n <= 0.30 then
		return "core"
	elseif n <= 0.55 then
		return "inner"
	end
	return "outer"
end

-- Mob level anchors on the radial field (world.md §1): safe core 1-10,
-- inner ring 10-25, outer ring 25-45, flank/back coasts up to 60.
local level_anchors = {
	{n = 0, level = 1},
	{n = 0.30, level = 10},
	{n = 0.55, level = 25},
	{n = 0.90, level = 45},
	{n = 1.00, level = 60},
}

-- Level of the mob field at radial value n, piecewise linear between the
-- anchors; everything beyond the last anchor stays at 60.
local function level_at_n(n)
	for i = 1, #level_anchors - 1 do
		local a, b = level_anchors[i], level_anchors[i + 1]
		if n <= b.n then
			return a.level + (n - a.n) / (b.n - a.n) * (b.level - a.level)
		end
	end
	return level_anchors[#level_anchors].level
end

-- Mob level for a hostile spawned at pos (1..60), or nil on the open water
-- surface (no leveled hostiles there; the deep-sea guards of world.md §2b
-- are hand-set). Radial field from the faction seat, then the two caps of
-- world.md §1 (war coast, strait) and the depth axis of combat_stats.md §3
-- — the safe core is only safe on the surface.
function grug_core.mob_level_at(pos)
	local ocean = grug_core.territory_at(pos) == "ocean"
	local az = math.abs(pos.z)
	-- Open/coastal sea surface only — the strait (|z| <= Z_MIN) keeps its
	-- level so its neutral wildlife (gulls/crabs, 1-5) has one.
	if ocean and az > Z_MIN and pos.y >= 0 then
		return nil
	end
	local level = level_at_n(radial_n(pos))
	if not ocean and az > Z_MIN and az <= WAR_COAST_Z then
		-- War coast: the PvP stage stays mid level (~20-30) even though the
		-- radial field would put it in elite range.
		level = math.min(level,
			20 + (az - Z_MIN) / (WAR_COAST_Z - Z_MIN) * 10)
	elseif az <= Z_MIN then
		level = math.min(level, 5) -- strait & beaches: harmless wildlife
	end
	if pos.y < 0 then
		level = math.max(level, math.min(60, 1 + math.floor(-pos.y / 20)))
	end
	return math.round(level)
end

-- Guard level at pos (20..70, WP6), or nil in the ocean. Runs INVERSE to
-- the mob field (world.md §1): elite city watch (60+) at the faction seat
-- and in the safe core, ~local mob level + 5 at the war coast — pushing
-- deeper means weaker mobs but ever harder guards.
function grug_core.guard_level_at(pos)
	if grug_core.territory_at(pos) == "ocean" then
		return nil
	end
	local level = math.max(65 - 45 * radial_n(pos),
		(grug_core.mob_level_at(pos) or 0) + 5)
	return math.round(math.min(70, math.max(20, level)))
end

-- 0 (safe core) .. 1 (elite coasts), defined as (mob_level-1)/59 and
-- clamped; positions without a mob level (open water surface) count as 1.
function grug_core.difficulty_at(pos)
	local level = grug_core.mob_level_at(pos)
	if not level then
		return 1
	end
	return math.min(1, math.max(0, (level - 1) / 59))
end

-- Chebyshev distance from one continent rectangle (0 inside it).
local function rect_distance(pos, z_min, z_max)
	local ddx = math.max(math.abs(pos.x) - X_HALF, 0)
	local ddz = math.max(z_min - pos.z, pos.z - z_max, 0)
	return math.max(ddx, ddz)
end

-- True beyond the coastal ocean of BOTH continents (world.md §2b): the
-- open sea, where the oversized deep-sea guards live.
function grug_core.open_sea_at(pos)
	local d = math.min(rect_distance(pos, Z_MIN, Z_MAX),
		rect_distance(pos, -Z_MAX, -Z_MIN))
	return d > grug_core.OCEAN_COASTAL_WIDTH
end

-- Resolves a player name to a faction id ("throng"/"accord") or nil.
-- Overridden by grug_factions at load time; the stub keeps grug_core free of
-- dependencies on player mods.
function grug_core.get_player_faction(name)
	return nil
end

-- Resolves a player name to a race id ("human", "orc", ...) or nil — used
-- to pick the race capital to spawn at. Overridden by grug_classes at load
-- time (same stub pattern as get_player_faction).
function grug_core.get_player_race(name)
	return nil
end

-- Finds a safe surface position near pos (for spawns/teleports); the camp
-- platform makes this a no-op at race capitals, elsewhere it is a fallback.
function grug_core.find_surface(pos)
	for y = 120, -16, -1 do
		local p = vector.new(pos.x, y, pos.z)
		local node = core.get_node_or_nil(p)
		local below = core.get_node_or_nil(vector.offset(p, 0, -1, 0))
		if node and below and node.name == "air" and
				below.name ~= "air" and below.name ~= "ignore" and
				core.get_item_group(below.name, "liquid") == 0 then
			return p
		end
	end
	return pos
end

local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath .. "/protection.lua")
dofile(modpath .. "/combat.lua")
