name = grug_food
title = Grudgelands Food
description = Out-of-combat health and mana restoration buffs.
depends = default, mobs, grug_core, grug_classes, grug_abilities, grug_mobs, grug_fishing, grug_gathering
