#!/usr/bin/env python3
"""Round 45 A1: original jewellery pixels by GPT-6 Astra, AI-assisted.

Artwork: CC0-1.0. Generator: GPL-3.0-or-later (repository code licence).
Python 3 + Pillow, no randomness, downloads, external fonts or image service.
Run from anywhere; --check compares all outputs without writing.
Only the labelled comparison tiles load existing art; jewellery is entirely
authored below. The user's picks (PICKS, 2026-10-09) are written to the game's
textures; the three proposal sheets stay as the record of the choice.
"""

import argparse
import hashlib
from io import BytesIO
from pathlib import Path
import re

from PIL import Image, ImageColor, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
TEXTURES = ROOT / "mods/ITEMS/grug_gear/textures"
NEAREST = Image.Resampling.NEAREST
KEYS = (
    "manawell", "last_light", "battlebeat", "apothecary_loop",
    "mercy_seal", "reclaimers_mark",
)
LABELS = (
    ("MANAWELL PENDANT", "AMULET / WATER DROP"),
    ("LAST LIGHT LOCKET", "AMULET / SUN"),
    ("BATTLEBEAT BAND", "RING / BEAT"),
    ("APOTHECARY LOOP", "RING / LEAF"),
    ("MERCY SEAL", "MEDALLION / WINGS"),
    ("RECLAIMER'S MARK", "MEDALLION / RETURN"),
)
# The user's pick per identity (2026-10-09); every tier ships that variant.
PICKS = {
    "manawell": "A", "last_light": "A", "battlebeat": "B",
    "apothecary_loop": "B", "mercy_seal": "A", "reclaimers_mark": "C",
}
TITLES = {"A": "HEIRLOOM", "B": "CUT AND SEAL", "C": "LIVING FILIGREE"}
SUBTITLES = {
    "A": "OPEN CHAINS - SOFT METAL - DEEP CABOCHONS",
    "B": "ANGULAR SETTINGS - COOL METAL - BRIGHT FACETS",
    "C": "CURLED BANDS - WARM HIGHLIGHTS - JEWEL INLAYS",
}
METALS = ("TIN", "IRON", "STEEL", "GOLD", "EMBERSTEEL", "ABYSSAL STEEL")
TRIMS = ("PLAIN", "PLAIN", "COPPER INLAY", "PLAIN", "GOLD FILIGREE", "GOLD FILIGREE")
GEMS = ("CITRINE", "JADE", "GARNET", "SAPPHIRE", "RUBY", "DIAMOND")

# o/s/m/l/h: metal edge, shadow, body, light, glint.
# t/u/v: setting trim shadow/body/light (copper T3, gold T5/T6).
# d/g/c/b/w: gem edge, shadow, body, light, glint.
# p/q: small accessory stones: sapphire at T5, sapphire + ruby at T6;
# lower tiers retain metal studs. Motifs and silhouettes never depend on tier.
# Each map is authored at 16x16, including its transparent border.
PIXELS = {
    "A": {
        "manawell": """
................
.....ollmmo.....
....hl....so....
...ol......so...
...om......so...
....lm....so....
.....lm..so.....
......lvuo......
......vwbo......
.....uvbcgt.....
....ovwbcgto....
....olbcggso....
.....umcgto.....
......umto......
.......o........
................
""",
        "last_light": """
................
....ohllmmo.....
...ol.....so....
...om.....so....
....lm...so.....
.....lvuso......
.....ohmo.......
....ovlvuo......
...ovdvbduo.....
...lldwcgtmo....
...olvcuvsmo....
...omgcggsso....
....omuuuso.....
.....osso.......
................
................
""",
        "battlebeat": """
................
................
......otttto....
.....ovwwcut....
....ovbbuucto...
...ohldvvvcto...
..olmldgcggto...
..ol..ouutso....
..om....omsso...
..om.....slso...
..om.....slso...
...lm...slso....
...ohlmmlso.....
....osssso......
................
................
""",
        "apothecary_loop": """
................
................
.........vo.....
.......ovbto....
......ovwcto....
.....ovbvcgo....
....olcuugo.....
...olotggo......
..ohm.omso......
..ol...omso.....
..om....slso....
..om....slso....
...lm..slso.....
....hllmso......
.....osso.......
................
""",
        "mercy_seal": """
................
......olmo......
......o.oo......
.....ohluuo.....
....olppuqso....
...olmmmmmuso...
..olhhmmmmmmso..
..ohslloollhso..
..olmtlwwltmso..
..olmttbcgtmso..
..olmmocgomuso..
...olmuuuumso...
....olmmmsso....
.....osssoo.....
................
................
""",
        "reclaimers_mark": """
................
......olmo......
......o.oo......
.....ohluuo.....
....oluumuuso...
...ovpmmmmquo...
...olbbbbbmuo...
..ohlbddddcgso..
..olmbdmmmcgso..
..olmmmvdmcgso..
..olmmvvbccuso..
...omvvvggmso...
....omvvumso....
.....ovtsoo.....
................
................
""",
    },
    "B": {
        "manawell": """
................
...ohllmmmso....
...ol.....so....
....lm...so.....
.....lm.so......
......lvo.......
......vwto......
.....ovbcgo.....
....ovbbccto....
....olbcgcso....
.....lbcgto.....
.....olcgso.....
......lcto......
.......vo.......
.......o........
................
""",
        "last_light": """
................
.....ohllmso....
....ol....so....
....om....so....
.....lm..so.....
......huso......
....olvvvuuo....
...ohucvcgguo...
...olbvvvcgso...
...olvvwvvuso...
...olbcvcggso...
...olgcvcggso...
....omuuuuso....
.....osssso.....
................
................
""",
        "battlebeat": """
................
................
....olvvvvuo....
...ohlwbcggto...
...olbwvcugto...
...olbwvcugto...
...olmuuutso....
...hl...omso....
...lm....slso...
...lm....slso...
...lm....slso...
...ohlmmmlso....
....olmmmsso....
.....osssoo.....
................
................
""",
        "apothecary_loop": """
................
................
........ovvo....
.......ovbcso...
......ovbvctso..
.....ovbvccgto..
....olcvccgto...
...ohmuuguto....
...ol.om.so.....
...lm..om.so....
...lm...omso....
....lm...mso....
.....hlllso.....
......osso......
................
................
""",
        "mercy_seal": """
................
......olmo......
......o.oo......
....ohvvvvuo....
...ohpmmmmmqo...
..olmmmmmummso..
..olhvmomhvmso..
..olmtvbvtmuso..
..olmttbctmuso..
..olmmocgmmuso..
...olmmmmmuso...
....olmmmuso....
.....ouuuso.....
......osso......
................
................
""",
        "reclaimers_mark": """
................
......olmo......
......o.oo......
....ohvvvvuo....
...olpmmmmmqo...
..olmbbbbbmmso..
..olmbdddcguso..
..olmbmmmcguso..
..olmmmvmcguso..
..olmmvvbcguso..
..olmvvvggmmso..
...olmvmmmuso...
....omvuuuso....
.....osssoo.....
................
................
""",
    },
    "C": {
        "manawell": """
................
....ohllmmo.....
...oh.....so....
...ol.....so....
....lm...so.....
.....lvuso......
....ov.wb.o.....
...ov.vbcg.vo...
...olvbccgtso...
...olbcggggso...
....lvggggto....
....olutttso....
.....oluvso.....
......ovso......
.......o........
................
""",
        "last_light": """
................
....ohllmmo.....
...ol.....so....
...om.....so....
....lm...so.....
.....lvuso......
...vo.hv.o......
...olvvvuuvo....
..ohvbbbgguo....
...lbbwbgguvo...
..ohvbvcgguo....
...ovgcgguvso...
....ovuvuto.....
...ov.oo.uo.....
................
................
""",
        "battlebeat": """
................
................
....ovv...vo....
...ovwbvovwto...
...olbcbvbcgo...
....olbcgggo....
...olouvuto.....
..ol..o.omso....
..ol.....slso...
..om.....slso...
...lm...slso....
...ohlmmlso.....
....olmmso......
.....osso.......
................
................
""",
        "apothecary_loop": """
................
................
........ovvo....
.......ovwbto...
......ovbvcgo...
.....olcvggso...
...ovvluuto.....
..ovwbvo.so.....
..olbcgo..so....
..olugto..so....
...lm.o..slso...
...olmmmllso....
....olmmuso.....
.....ossso......
................
................
""",
        "mercy_seal": """
................
......olmo......
......o.oo......
....ovolvuvo....
...ovpumuquvo...
..ovlmmmmmvuvo..
..ohvlmoumlhso..
...lvvlwvlvso...
..ohmtbcgtmuso..
..olmmttgmmuso..
...olmuumuuso...
....ovmmmuvo....
.....ovvuuo.....
......osso......
................
................
""",
        "reclaimers_mark": """
................
......olmo......
......o.oo......
....ovlvuuvo....
...ovpbbbbquo...
..ovlbcddcguso..
..ohmbd..dcguo..
..olmb..v.cgso..
..ol...vvbcguo..
..ol..vvvcguso..
...olv.vgguso...
....ov.vuuvo....
.....otttto.....
......osso......
................
................
""",
    },
}

# Authored ramps track the material families of item_tiers.md / goldsmith.lua.
# Unlike the reference samples, no source sprite's pixels are used here.
# Five colours per ramp, darkest first; each variant has its own finish.
METAL_RAMPS = {
    "A": (
        "464b4b 727775 a7aaa2 d1d4c9 f1f1df",
        "333331 51514b 797970 a3a393 c9c9b6",
        "3d4750 697480 9da9b2 cdd8dd eff5f3",
        "644318 997025 c99c37 ebc85d fff0a1",
        "351d1c 632e24 a3482d d77340 f9b65b",
        "2d233c 4e395f 795991 a98bc0 ddc9ed",
    ),
    "B": (
        "35444b 637880 9caeb2 cedee0 f3ffff",
        "292f34 414e54 697b80 94adb0 c6d8d7",
        "2c3d50 556c82 8da6bc c2d7e6 f0faff",
        "634916 967727 c5ab49 e7d781 fff3bb",
        "291d23 532a2d 8c3e32 cc6639 ffb858",
        "25243f 414365 65638c 9897c4 d7dafb",
    ),
    "C": (
        "565047 857e6e b8b3a1 ded9c6 fff8dc",
        "393834 5d5c51 8c8b77 b9b8a0 e1dec5",
        "434650 717680 abb2be dce1e9 fffaf4",
        "735020 a8772e d9ad49 f2d87e fff5c4",
        "3e2227 723b35 b76342 e8965c ffda90",
        "3c294a 624375 9266a2 c799ca f5d7f5",
    ),
}
GEM_RAMPS = {
    "A": (
        "614119 9e6b21 d6a131 efce65 fff0ae",
        "183d2c 276443 489666 7ec48e c9edbd",
        "471e2b 772b41 a74a58 d07b7f f4b6ad",
        "162f59 264b91 407dcc 83b8ee c7e5ff",
        "4d182a 8f253f c64053 ed7781 ffc0bd",
        "24565d 3d9096 6dc6c6 b1e9df effff5",
    ),
    "B": (
        "4f3514 986719 d4a52b f0d255 fff3b4",
        "123b32 1d6950 37a674 79d7a1 d3ffe1",
        "42172f 79233f b03753 e16d84 ffb7c7",
        "182253 233e95 3a6fce 75b0fa d6eaff",
        "451523 8d1c36 cf3655 f76b81 ffc8d0",
        "174a61 287f9b 5bbbd0 a2e2ee efffff",
    ),
    "C": (
        "654022 a97327 e4ad42 f8d880 fff7cb",
        "244633 3b7752 6bb483 a7deb2 e7ffda",
        "532333 8d3b50 bd6270 e99a9e ffdbca",
        "253963 3f5fa0 658fdb a6cbff e7f5ff",
        "572135 9f3852 d95c75 f49ea9 ffe0dc",
        "3b6370 5995a4 8acdd4 c6eff0 f8fffa",
    ),
}
COPPER = {
    "A": "86502e c1824c ebbb7f",
    "B": "804630 bd7a50 f0b885",
    "C": "9c563a d89366 ffd0a1",
}


def colours(ramp):
    return [ImageColor.getcolor("#" + value, "RGBA") for value in ramp.split()]


def palette(variant, tier):
    metal = colours(METAL_RAMPS[variant][tier - 1])
    gem = colours(GEM_RAMPS[variant][tier - 1])
    trim = metal[1:4]
    if tier == 3:
        trim = colours(COPPER[variant])
    elif tier in (5, 6):
        trim = colours(METAL_RAMPS[variant][3])[1:4]
    p = dict(zip("osmlh", metal))
    p.update(zip("d g c b w".split(), gem))
    p.update(zip("tuv", trim))
    p["p"] = colours(GEM_RAMPS[variant][3])[3] if tier >= 5 else metal[3]
    p["q"] = colours(GEM_RAMPS[variant][4])[2] if tier == 6 else p["p"]
    p["."] = (0, 0, 0, 0)
    return p


def icon(variant, key, tier):
    rows = PIXELS[variant][key].strip().splitlines()
    assert len(rows) == 16 and all(len(row) == 16 for row in rows), (variant, key)
    p = palette(variant, tier)
    im = Image.new("RGBA", (16, 16))
    im.putdata([p[pixel] for row in rows for pixel in row])
    return im


# Original small caption alphabet; no system font or font download is used.
GLYPHS = dict(zip(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'-/.:+",
    (
        "010/101/111/101/101", "110/101/110/101/110", "011/100/100/100/011",
        "110/101/101/101/110", "111/100/110/100/111", "111/100/110/100/100",
        "011/100/101/101/011", "101/101/111/101/101", "111/010/010/010/111",
        "001/001/001/101/010", "101/101/110/101/101", "100/100/100/100/111",
        "101/111/111/101/101", "101/111/111/111/101", "010/101/101/101/010",
        "110/101/110/100/100", "010/101/101/111/011", "110/101/110/101/101",
        "011/100/010/001/110", "111/010/010/010/010", "101/101/101/101/111",
        "101/101/101/101/010", "101/101/111/111/101", "101/101/010/101/101",
        "101/101/010/010/010", "111/001/010/100/111", "111/101/101/101/111",
        "010/110/010/010/111", "110/001/010/100/111", "110/001/010/001/110",
        "101/101/111/001/001", "111/100/110/001/110", "011/100/110/101/010",
        "111/001/010/010/010", "010/101/010/101/010", "010/101/011/001/110",
        "010/010/000/000/000", "000/000/111/000/000", "001/001/010/100/100",
        "000/000/000/000/010", "000/010/000/010/000", "000/010/111/010/000",
    ),
))


def text(im, xy, value, colour="#d9dedb", scale=2):
    draw = ImageDraw.Draw(im)
    x, y = xy
    for char in value:
        if char != " ":
            for j, row in enumerate(GLYPHS[char].split("/")):
                for i, bit in enumerate(row):
                    if bit == "1":
                        draw.rectangle((x + i * scale, y + j * scale,
                                        x + (i + 1) * scale - 1,
                                        y + (j + 1) * scale - 1), fill=colour)
        x += 4 * scale


def centre(im, x, y, value, colour="#d9dedb", scale=2):
    text(im, (x - (len(value) * 4 - 1) * scale // 2, y), value, colour, scale)


def sample(im, sprite, xy, scale=4):
    im.alpha_composite(sprite.resize((16 * scale, 16 * scale), NEAREST), xy)


def references():
    base = ROOT / "mods/BASE/default/textures"
    gear = ROOT / "mods/ITEMS/grug_gear/textures"
    bar = Image.open(base / "default_gold_ingot.png").convert("RGBA")
    gem = Image.open(base / "default_diamond.png").convert("RGBA")
    # cut_diamond's registered ^[colorize:#ffffff:20 (reference tile only).
    pixels = [gem.getpixel((x, y)) for y in range(16) for x in range(16)]
    gem.putdata([tuple((c * 235 + 255 * 20) // 255 for c in pixel[:3])
                 + (pixel[3],) for pixel in pixels])
    sword = Image.open(gear / "grug_gear_item_sword_steel.png").convert("RGBA")
    apple = Image.open(base / "default_apple.png").convert("RGBA")
    return (("GOLD BAR", bar), ("CUT DIAMOND", gem), ("STEEL SWORD", sword), ("APPLE", apple))


def sheet(variant, sprites):
    im = Image.new("RGBA", (1000, 1056), "#20272c")
    draw = ImageDraw.Draw(im)
    text(im, (28, 24), "GRUDGELANDS / R45 A1", "#8cabae")
    text(im, (28, 54), variant + " / " + TITLES[variant], "#f0dfb0", 4)
    text(im, (28, 92), SUBTITLES[variant], "#b7c2c1")
    text(im, (28, 116), "16 X 16 RGBA / NATIVE PIXELS / ALL LARGE SAMPLES AT 4X", "#899c9f")
    for tier in range(1, 7):
        cx = 278 + (tier - 1) * 128
        centre(im, cx, 157, "T" + str(tier), "#f0dfb0", 3)
        centre(im, cx, 182, METALS[tier - 1], scale=2)
        centre(im, cx, 201, TRIMS[tier - 1], "#899c9f", 1)
        gem = palette(variant, tier)["b"]
        centre(im, cx, 216, GEMS[tier - 1], gem, 2)
    for row, key in enumerate(KEYS):
        y = 248 + row * 80
        text(im, (28, y + 21), LABELS[row][0], scale=2)
        text(im, (28, y + 42), LABELS[row][1], "#899c9f", 1)
        for tier in range(1, 7):
            cx = 278 + (tier - 1) * 128
            draw.rectangle((cx - 37, y, cx + 36, y + 73), fill="#343b40")
            sample(im, sprites[(key, tier)], (cx - 32, y + 5))
    draw.line((28, 744, 970, 744), fill="#506064")
    text(im, (28, 766), "INVENTORY COMPARISON / IDENTICAL 4X SCALE", "#f0dfb0")
    choices = [("MANAWELL T4", sprites[("manawell", 4)]),
               ("BATTLEBEAT T2", sprites[("battlebeat", 2)]),
               ("MERCY T6", sprites[("mercy_seal", 6)])] + list(references())
    for i, (label, sprite) in enumerate(choices):
        x = 40 + i * 134
        draw.rectangle((x, 794, x + 119, 883), fill="#343b40")
        sample(im, sprite, (x + 28, 800))
        centre(im, x + 60, 872, label, "#c6d1d0", 1)
    text(im, (28, 904), "NATIVE 1X / T4", "#8cabae", 2)
    for i, key in enumerate(KEYS):
        x = 230 + i * 72
        draw.rectangle((x, 898, x + 29, 927), fill="#343b40")
        draw.rectangle((x + 30, 898, x + 59, 927), fill="#d9d2bf")
        sample(im, sprites[(key, 4)], (x + 7, 905), 1)
        sample(im, sprites[(key, 4)], (x + 37, 905), 1)
    text(im, (28, 954), "ORIGINAL JEWELLERY / GPT-6 ASTRA / AI-ASSISTED / CC0 1.0", "#adbfc0")
    text(im, (28, 978), "REFERENCE TILES KEEP THEIR SOURCE LICENCES - SEE LICENSE-MEDIA.MD", "#899c9f", 1)
    text(im, (28, 999), "PROPOSALS ONLY / USER SELECTION PENDING", "#d2b979", 2)
    return im


def final_sheet(sprites):
    """The shipped set: each identity's picked variant at every tier."""
    im = Image.new("RGBA", (1000, 856), "#20272c")
    draw = ImageDraw.Draw(im)
    text(im, (28, 24), "GRUDGELANDS / R45 A1", "#8cabae")
    text(im, (28, 54), "FINAL JEWELLERY", "#f0dfb0", 4)
    text(im, (28, 92), "THE USER'S PICK PER IDENTITY / ALL SIX TIERS", "#b7c2c1")
    text(im, (28, 116), "16 X 16 RGBA / NATIVE PIXELS / LARGE SAMPLES AT 4X", "#899c9f")
    for tier in range(1, 7):
        cx = 278 + (tier - 1) * 128
        centre(im, cx, 157, "T" + str(tier), "#f0dfb0", 3)
        centre(im, cx, 182, METALS[tier - 1], scale=2)
        centre(im, cx, 201, TRIMS[tier - 1], "#899c9f", 1)
        centre(im, cx, 216, GEMS[tier - 1], scale=2)
    for row, key in enumerate(KEYS):
        y = 248 + row * 80
        text(im, (28, y + 21), LABELS[row][0], scale=2)
        variant = PICKS[key]
        text(im, (28, y + 42), "VARIANT " + variant + " / " + TITLES[variant],
             "#899c9f", 1)
        for tier in range(1, 7):
            cx = 278 + (tier - 1) * 128
            draw.rectangle((cx - 37, y, cx + 36, y + 73), fill="#343b40")
            sample(im, sprites[(key, tier)], (cx - 32, y + 5))
    text(im, (28, 744), "NATIVE 1X / T1 TO T6", "#8cabae", 2)
    for row, key in enumerate(KEYS):
        x = 28 + row * 158
        draw.rectangle((x, 768, x + 149, 783), fill="#343b40")
        draw.rectangle((x, 784, x + 149, 799), fill="#d9d2bf")
        for tier in range(1, 7):
            sample(im, sprites[(key, tier)], (x + 3 + (tier - 1) * 24, 768), 1)
            sample(im, sprites[(key, tier)], (x + 3 + (tier - 1) * 24, 784), 1)
    text(im, (28, 822), "ORIGINAL JEWELLERY / GPT-6 ASTRA / AI-ASSISTED / CC0 1.0", "#adbfc0")
    return im


def png_bytes(im):
    out = BytesIO()
    im.save(out, format="PNG", optimize=False, compress_level=9)
    return out.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()
    source = (ROOT / "mods/ITEMS/grug_gear/trinkets.lua").read_text()
    assert tuple(re.findall(r'\{key = "([a-z_]+)"', source)) == KEYS, "identity roster changed"
    assert set(PICKS) == set(KEYS), "every identity needs a pick"
    hashes = set()
    outputs = {}
    shipped = {}
    for variant in "ABC":
        sprites = {(key, tier): icon(variant, key, tier)
                   for key in KEYS for tier in range(1, 7)}
        for (key, tier), im in sprites.items():
            name = f"grug_gear_trinket_{key}_t{tier}.png"
            assert im.size == (16, 16) and im.mode == "RGBA", name
            assert set(im.getchannel("A").tobytes()) == {0, 255}, name
            digest = hashlib.sha256(im.tobytes()).hexdigest()
            assert digest not in hashes, "duplicate icon: " + variant + " " + name
            hashes.add(digest)
            if PICKS[key] == variant:
                shipped[(key, tier)] = im
                outputs[TEXTURES / name] = im
        # Only the comparison sheet stays per proposal; the unpicked icons
        # are not kept as files (this generator reproduces them).
        outputs[HERE / "variants" / variant / "sheet.png"] = sheet(variant, sprites)
    outputs[HERE / "final_sheet.png"] = final_sheet(shipped)
    if args.check:
        for variant in "ABC":
            folder = HERE / "variants" / variant
            assert {p.name for p in folder.glob("*.png")} == {"sheet.png"}, folder
        on_disk = {p for p in TEXTURES.glob("grug_gear_trinket_*.png")}
        assert on_disk == {p for p in outputs if p.parent == TEXTURES}, \
            "trinket texture roster differs"
    for path, im in outputs.items():
        data = png_bytes(im)
        if args.check:
            assert path.read_bytes() == data, "stale output: " + str(path)
            with Image.open(path) as saved:
                assert saved.mode == im.mode and saved.size == im.size, path
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(f"{'Verified' if args.check else 'Wrote'} {len(outputs)} PNGs: "
          f"{len(shipped)} shipped trinket icons (16x16 RGBA, binary alpha, "
          "picked from 108 unique proposals); 3 proposal sheets; the final sheet.")


if __name__ == "__main__":
    main()
