#!/usr/bin/env bash
# Static gates for the WP13 round-2 weapon-ladder increment, the same set every
# WP13 increment runs: parser and SETGLOBAL per changed file and tree-wide, the
# five plain-5.1 sweeps scoped to the changed Lua and then tree-wide over
# mods/*/grug_* and tools, the fresh-server audit, plus this lane's own media
# gates (every generated sprite is licensed and reproducible, and every item
# image a mod names exists on disk).
set -uo pipefail
export LC_ALL=C
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd -P)"
cd "$repo"
LUAC="$repo/tools/bin/luac51"

CHANGED=(
	mods/ITEMS/grug_gear/init.lua
	mods/ITEMS/grug_materials/init.lua
	mods/ITEMS/grug_materials/tools.lua
	mods/ITEMS/grug_materials/overrides.lua
	mods/ITEMS/grug_materials/content_curation.lua
	mods/PLAYER/grug_visuals/compose.lua
	mods/PLAYER/grug_visuals/wield_geometry.lua
	mods/PLAYER/grug_visuals/apply.lua
	mods/PLAYER/grug_inventory/equipment.lua
	mods/PLAYER/grug_factions/init.lua
	mods/ENTITIES/grug_traders/stock.lua
	tools/wp13/gear_catalogue_kat.lua
	tools/wp13/character_visuals_kat.lua
	tools/wp13/wield_transform_kat.lua
	tools/wp13/weapon_probe/init.lua
	tools/wp43/materials_test.lua
)

echo "== parser and SETGLOBAL on every Lua file this increment changed =="
for file in "${CHANGED[@]}"; do
	if "$LUAC" -p "$file" >/dev/null 2>&1; then
		globals="$("$LUAC" -p -l "$file" | grep -c SETGLOBAL)"
		echo "$file parser PASS; SETGLOBAL [$globals]"
	else
		echo "$file parser FAIL"
	fi
done

echo "== whole tree parses =="
find mods -name '*.lua' -path 'mods/*/grug_*' -print0 |
	xargs -0 "$LUAC" -p && echo "mods/*/grug_* parser PASS"
find tools -name '*.lua' -print0 | xargs -0 "$LUAC" -p &&
	echo "tools parser PASS"

sweeps() {
	local index=1
	for pattern in \
		'(^|[^[:alnum:]_.:])goto[[:space:](]|::[A-Za-z_]+::' \
		'\\u\{|\\x[0-9A-Fa-f]|\\z' \
		'table\.(unpack|pack|move)|rawlen|coroutine\.isyieldable|math\.(type|tointeger)|utf8\.' \
		'[^:/]//|[[:alnum:]_)"] *(&|\||<<|>>) *[[:alnum:]_("]' \
		'\brequire[[:space:]]*\(|io\.popen|os\.(execute|exit)|\bminetest\.'; do
		echo "SWEEP $index"
		grep -rnE "$pattern" "$@" --include=*.lua
		index=$((index + 1))
	done
	echo "SWEEPS DONE (no output above a SWEEP line means zero hits)"
}

echo "== five plain-5.1 sweeps, scoped to the Lua this increment changed =="
sweeps "${CHANGED[@]}"

echo "== the same five sweeps over all of mods/*/grug_* and tools =="
sweeps mods/*/grug_* tools

echo "== fresh server check =="
python3 tools/check_fresh_server.py

echo "== the sprite ladder is reproducible from its generator =="
before="$(sha256sum mods/ITEMS/grug_gear/textures/*.png \
	mods/ITEMS/grug_materials/textures/*.png | sha256sum)"
python3 tools/wp13/gen_weapon_ladder.py
after="$(sha256sum mods/ITEMS/grug_gear/textures/*.png \
	mods/ITEMS/grug_materials/textures/*.png | sha256sum)"
if [[ "$before" == "$after" ]]; then
	echo "weapon ladder regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi

echo "== the armor art and the mob/trader icons are unchanged by this lane =="
before="$(sha256sum mods/ENTITIES/grug_mobs/textures/*.png \
	mods/ENTITIES/grug_traders/textures/*.png | sha256sum)"
python3 tools/gen_mob_item_textures.py >/dev/null
after="$(sha256sum mods/ENTITIES/grug_mobs/textures/*.png \
	mods/ENTITIES/grug_traders/textures/*.png | sha256sum)"
if [[ "$before" == "$after" ]]; then
	echo "mob/trader icons regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi

echo "== every media file has a LICENSE-media.md row =="
missing=0
for png in mods/ITEMS/grug_gear/textures/*.png; do
	name="$(basename "$png")"
	# Weapon rows are written per FAMILY with a `<material>` placeholder (six
	# files per row), so the pattern is matched, not the whole file name.
	stem="$(echo "$name" | sed -E 's/_(bronze|iron|steel|silversteel|embersteel|abyssal_steel)\.png$/_<material>.png/')"
	if grep -qF "$name" mods/ITEMS/grug_gear/LICENSE-media.md ||
			grep -qF "$stem" mods/ITEMS/grug_gear/LICENSE-media.md ||
			grep -qF "${stem%_<material>.png}_{bronze,iron,steel,silversteel,embersteel,abyssal_steel}.png" \
				mods/ITEMS/grug_gear/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
for png in mods/ITEMS/grug_materials/textures/*.png; do
	name="$(basename "$png")"
	family="$(echo "$name" | sed -E 's/^grug_materials_tool_(bronze|iron|steel|silversteel|embersteel|abyssal_steel)//; s/\.png$//')"
	material="$(echo "$name" | sed -E 's/^grug_materials_tool_//; s/(pick|axe|shovel)\.png$//')"
	if grep -qF "$name" mods/ITEMS/grug_materials/LICENSE-media.md ||
			grep -qF "_${material}${family}.png" mods/ITEMS/grug_materials/LICENSE-media.md ||
			grep -q "grug_materials_tool_${material}" mods/ITEMS/grug_materials/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
echo "media rows missing: $missing"

echo "== every inventory_image a grug mod names exists on disk =="
python3 - <<'PYTHON'
import os
import re
import sys

missing = []
checked = 0
# The two mods this lane gives stored sprites to. Their `inventory_image`
# values are plain literals, so a regex is enough and no engine is needed.
# A literal is resolved against the mod that OWNS its prefix -- `default_*`
# names are vendored minetest_game media and live in default's own directory,
# which is exactly how the engine resolves them (one flat media pool).
OWNERS = {
    "grug_gear_": "mods/ITEMS/grug_gear/textures",
    "grug_materials_": "mods/ITEMS/grug_materials/textures",
    "default_": "mods/BASE/default/textures",
}
for mod, directory in (
        ("grug_gear", "mods/ITEMS/grug_gear"),
        ("grug_materials", "mods/ITEMS/grug_materials")):
    for root, _dirs, files in os.walk(directory):
        if "textures" in root:
            continue
        for name in files:
            if not name.endswith(".lua"):
                continue
            body = open(os.path.join(root, name)).read()
            for literal in re.findall(r'"([A-Za-z0-9_]+\.png)"', body):
                where = None
                for prefix, folder in OWNERS.items():
                    if literal.startswith(prefix):
                        where = folder
                if where is None:
                    missing.append("%s: %s (no owning mod)" % (mod, literal))
                    continue
                checked += 1
                if not os.path.exists(os.path.join(where, literal)):
                    missing.append("%s: %s" % (mod, literal))
print("texture literals checked: %d" % checked)
print("missing: %s" % (", ".join(sorted(set(missing))) or "none"))
PYTHON
