#!/usr/bin/env bash
# Static gates for the WP13 round-2 weapon-ladder increment, the same set every
# WP13 increment runs: parser and SETGLOBAL per changed file and tree-wide, the
# five plain-5.1 sweeps scoped to the changed Lua and then tree-wide over
# mods/*/grug_* and tools, the fresh-server audit, plus this lane's own media
# gates (every generated sprite is licensed and reproducible, and every item
# image a mod names exists on disk).
set -uo pipefail
export LC_ALL=C
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd -P)"
cd "$repo"
LUAC="$repo/tools/bin/luac51"

CHANGED=(
	mods/ITEMS/grug_gear/init.lua
	mods/ITEMS/grug_materials/init.lua
	mods/ITEMS/grug_materials/tools.lua
	mods/ITEMS/grug_materials/overrides.lua
	mods/ITEMS/grug_materials/content_curation.lua
	mods/PLAYER/grug_visuals/compose.lua
	mods/PLAYER/grug_visuals/wield_geometry.lua
	mods/PLAYER/grug_visuals/apply.lua
	mods/PLAYER/grug_inventory/equipment.lua
	mods/PLAYER/grug_inventory/pages.lua
	mods/PLAYER/grug_factions/init.lua
	mods/ENTITIES/grug_traders/stock.lua
	tools/wp13/gear_catalogue_kat.lua
	tools/wp13/character_visuals_kat.lua
	tools/wp13/wield_transform_kat.lua
	tools/wp13/weapon_probe/init.lua
	tools/wp43/materials_test.lua
)

echo "== parser and SETGLOBAL on every Lua file this increment changed =="
for file in "${CHANGED[@]}"; do
	if "$LUAC" -p "$file" >/dev/null 2>&1; then
		globals="$("$LUAC" -p -l "$file" | grep -c SETGLOBAL)"
		echo "$file parser PASS; SETGLOBAL [$globals]"
	else
		echo "$file parser FAIL"
	fi
done

echo "== whole tree parses =="
find mods -name '*.lua' -path 'mods/*/grug_*' -print0 |
	xargs -0 "$LUAC" -p && echo "mods/*/grug_* parser PASS"
find tools -name '*.lua' -print0 | xargs -0 "$LUAC" -p &&
	echo "tools parser PASS"

sweeps() {
	local index=1
	for pattern in \
		'(^|[^[:alnum:]_.:])goto[[:space:](]|::[A-Za-z_]+::' \
		'\\u\{|\\x[0-9A-Fa-f]|\\z' \
		'table\.(unpack|pack|move)|rawlen|coroutine\.isyieldable|math\.(type|tointeger)|utf8\.' \
		'[^:/]//|[[:alnum:]_)"] *(&|\||<<|>>) *[[:alnum:]_("]' \
		'\brequire[[:space:]]*\(|io\.popen|os\.(execute|exit)|\bminetest\.'; do
		echo "SWEEP $index"
		grep -rnE "$pattern" "$@" --include=*.lua
		index=$((index + 1))
	done
	echo "SWEEPS DONE (no output above a SWEEP line means zero hits)"
}

echo "== five plain-5.1 sweeps, scoped to the Lua this increment changed =="
sweeps "${CHANGED[@]}"

echo "== the same five sweeps over all of mods/*/grug_* and tools =="
sweeps mods/*/grug_* tools

echo "== fresh server check =="
python3 tools/check_fresh_server.py

echo "== the sprite ladder is reproducible from its generator =="
before="$(sha256sum mods/ITEMS/grug_gear/textures/*.png \
	mods/ITEMS/grug_materials/textures/*.png | sha256sum)"
python3 tools/wp13/gen_weapon_ladder.py
after="$(sha256sum mods/ITEMS/grug_gear/textures/*.png \
	mods/ITEMS/grug_materials/textures/*.png | sha256sum)"
if [[ "$before" == "$after" ]]; then
	echo "weapon ladder regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi

echo "== the armor art and the mob/trader icons are unchanged by this lane =="
before="$(sha256sum mods/ENTITIES/grug_mobs/textures/*.png \
	mods/ENTITIES/grug_traders/textures/*.png | sha256sum)"
python3 tools/gen_mob_item_textures.py >/dev/null
after="$(sha256sum mods/ENTITIES/grug_mobs/textures/*.png \
	mods/ENTITIES/grug_traders/textures/*.png | sha256sum)"
if [[ "$before" == "$after" ]]; then
	echo "mob/trader icons regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi

echo "== every media file has a LICENSE-media.md row =="
missing=0
for png in mods/ITEMS/grug_gear/textures/*.png; do
	name="$(basename "$png")"
	# Weapon rows are written per FAMILY with a `<material>` placeholder (six
	# files per row), so the pattern is matched, not the whole file name.
	stem="$(echo "$name" | sed -E 's/_(bronze|iron|steel|silversteel|embersteel|abyssal_steel)\.png$/_<material>.png/')"
	if grep -qF "$name" mods/ITEMS/grug_gear/LICENSE-media.md ||
			grep -qF "$stem" mods/ITEMS/grug_gear/LICENSE-media.md ||
			grep -qF "${stem%_<material>.png}_{bronze,iron,steel,silversteel,embersteel,abyssal_steel}.png" \
				mods/ITEMS/grug_gear/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
for png in mods/ITEMS/grug_materials/textures/*.png; do
	name="$(basename "$png")"
	family="$(echo "$name" | sed -E 's/^grug_materials_tool_(bronze|iron|steel|silversteel|embersteel|abyssal_steel)//; s/\.png$//')"
	material="$(echo "$name" | sed -E 's/^grug_materials_tool_//; s/(pick|axe|shovel)\.png$//')"
	if grep -qF "$name" mods/ITEMS/grug_materials/LICENSE-media.md ||
			grep -qF "_${material}${family}.png" mods/ITEMS/grug_materials/LICENSE-media.md ||
			grep -q "grug_materials_tool_${material}" mods/ITEMS/grug_materials/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
echo "media rows missing: $missing"

echo "== every .png literal under mods/*/grug_* resolves to a real file =="
# Deleting a sprite that another mod still names is invisible on the server: the
# client reports `generateImagePart` and draws nothing, and the log says nothing
# at all. That is how WP13 round 2's first pass left the character page's empty
# weapon-slot ghost pointing at a file the art commit had just removed. The scan
# is therefore TREE-WIDE over every grug mod, not just the two this lane gives
# sprites to.
python3 - <<'PYTHON'
import glob
import os
import re

# Luanti's media pool is flat: every `textures/` (and `models/`) directory of
# every loaded mod, vendored ones included, resolves a bare file name.
pool = set()
for root, _dirs, files in os.walk("mods"):
    if os.path.basename(root) not in ("textures", "models"):
        continue
    for name in files:
        if name.endswith(".png"):
            pool.add(name)

# Literals that are NOT file names. Each one is a string-concatenation fragment
# or a documentation example, verified by hand; the list is explicit so a real
# miss can never hide behind a pattern.
WHITELIST = {
    # `texture .. "_side.png"` -- the tail of a built name, never used alone.
    "_side.png",
    # `texture = {"a.png", "b.png"}` in the rares.lua doc comment.
    "a.png",
    "b.png",
}

missing = {}
checked = 0
for mod in sorted(glob.glob("mods/*/grug_*")):
    for root, _dirs, files in os.walk(mod):
        if "textures" in root.split(os.sep):
            continue
        for name in sorted(files):
            if not name.endswith(".lua"):
                continue
            path = os.path.join(root, name)
            for number, line in enumerate(open(path), 1):
                # A literal may carry texture modifiers ("x.png^[multiply:#fff")
                # or be one half of a composed string, so the file names are
                # pulled out of the quoted span rather than matched whole.
                for span in re.findall(r'"([^"\n]*)"', line):
                    for literal in re.findall(r'[A-Za-z0-9_]+\.png', span):
                        if literal in WHITELIST:
                            continue
                        checked += 1
                        if literal not in pool:
                            missing.setdefault(literal, []).append(
                                "%s:%d" % (path, number))
print("texture literals checked: %d (whitelisted fragments: %d)"
      % (checked, len(WHITELIST)))
if missing:
    for literal in sorted(missing):
        print("MISSING %s at %s" % (literal, ", ".join(missing[literal])))
else:
    print("missing: none")
PYTHON
