#!/usr/bin/env bash
# Static gates for WP26 (task card gates 5, 6 and 7), the same set every WP13
# increment ran: parser and SETGLOBAL per changed file and tree-wide, the five
# plain-5.1 sweeps scoped to the changed Lua and then tree-wide over
# mods/*/grug_* and tools, the fresh-server audit, the scope grep, the media
# licence rows and the texture generator's own reproducibility check.
set -uo pipefail
export LC_ALL=C
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd -P)"
cd "$repo"
LUAC="$repo/tools/bin/luac51"

CHANGED=(
	mods/ITEMS/grug_smelting/init.lua
	mods/ITEMS/grug_smelting/alloys.lua
	mods/ITEMS/grug_smelting/node.lua
	mods/ITEMS/grug_smelting/recipes.lua
	mods/ENTITIES/grug_traders/init.lua
	mods/ENTITIES/grug_traders/audit_alloys.lua
	tools/wp26/smelting_kat.lua
	tools/wp26/smelt_probe/init.lua
)

echo "== parser and SETGLOBAL on every Lua file this increment changed =="
for file in "${CHANGED[@]}"; do
	if "$LUAC" -p "$file" >/dev/null 2>&1; then
		globals="$("$LUAC" -p -l "$file" | grep -c SETGLOBAL)"
		echo "$file parser PASS; SETGLOBAL [$globals]"
	else
		echo "$file parser FAIL"
	fi
done

echo "== whole tree parses =="
find mods -name '*.lua' -path 'mods/*/grug_*' -print0 |
	xargs -0 "$LUAC" -p && echo "mods/*/grug_* parser PASS"
find tools -name '*.lua' -print0 | xargs -0 "$LUAC" -p &&
	echo "tools parser PASS"

sweeps() {
	local index=1
	for pattern in \
		'(^|[^[:alnum:]_.:])goto[[:space:](]|::[A-Za-z_]+::' \
		'\\u\{|\\x[0-9A-Fa-f]|\\z' \
		'table\.(unpack|pack|move)|rawlen|coroutine\.isyieldable|math\.(type|tointeger)|utf8\.' \
		'[^:/]//|[[:alnum:]_)"] *(&|\||<<|>>) *[[:alnum:]_("]' \
		'\brequire[[:space:]]*\(|io\.popen|os\.(execute|exit)|\bminetest\.'; do
		echo "SWEEP $index"
		grep -rnE "$pattern" "$@" --include=*.lua
		index=$((index + 1))
	done
	echo "SWEEPS DONE (no output above a SWEEP line means zero hits)"
}

echo "== five plain-5.1 sweeps, scoped to the Lua this increment changed =="
sweeps "${CHANGED[@]}"

echo "== the same five sweeps over all of mods/*/grug_* and tools =="
sweeps mods/*/grug_* tools

echo "== fresh server check =="
python3 tools/check_fresh_server.py

echo "== no globalstep, no detached inventory, no ABM (gate 6) =="
grep -rnE 'register_globalstep|create_detached_inventory|register_abm|register_lbm' \
	mods/ITEMS/grug_smelting mods/ENTITIES/grug_traders/audit_alloys.lua \
	--include=*.lua && echo "FOUND ONE (see above)" ||
	echo "none: node timers only, no detached inventory"

echo "== scope grep: no gem, cultural, trinket, gear or pick id (gate 5) =="
# Grepping the SOURCE would hit the audit code, which has to name the very
# stems it forbids. So the grep runs over the surface the KAT prints -- the
# itemstrings actually registered, one per line.
surface="$(mktemp)"
luajit -e 'io.write(dofile("tools/wp26/smelting_kat.lua")("."))' |
	grep -E '^(wp26_cook|wp26_alloy|wp26_storage|wp26_station)' >"$surface"
echo "surface lines: $(wc -l <"$surface")"
if grep -nE 'rough_|cut_|citrine|garnet|jade|diamond|sapphire|ruby|sunwax|runeslate|moonresin|red_ochre|spirit_resin|gravesalt|trophy|crown|trinket|grug_gear:|:pick_|:sword_|:axe_|:shovel_|emberglass_shard' "$surface"; then
	echo "FOUND ONE (see above)"
else
	echo "none: the registered surface names no gem, culture, trophy, gear or pick id"
fi
rm -f "$surface"

echo "== no price field added or changed (gate 4) =="
grep -rn '_grug_sell_price\|grug_traders.set_price' mods/ITEMS/grug_smelting \
	mods/ENTITIES/grug_traders/audit_alloys.lua && echo "FOUND ONE (see above)" ||
	echo "none: WP26 adds no price"

echo "== every media file of the new mod has a LICENSE-media.md row (gate 7) =="
missing=0
for png in mods/ITEMS/grug_smelting/textures/*.png; do
	name="$(basename "$png")"
	if grep -qF "\`$name\`" mods/ITEMS/grug_smelting/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
echo "media rows missing: $missing"

echo "== no CC BY-SA lottblocks media in the tree (gate 7) =="
count="$(find mods -iname 'lott*' | wc -l)"
if [[ "$count" -gt 0 ]]; then
	find mods -iname 'lott*' -print
fi
echo "lottblocks files shipped: $count"

echo "== the fronts are reproducible from their generator =="
before="$(sha256sum mods/ITEMS/grug_smelting/textures/*.png | sha256sum)"
python3 tools/wp26/gen_dual_furnace_textures.py --check
after="$(sha256sum mods/ITEMS/grug_smelting/textures/*.png | sha256sum)"
if [[ "$before" == "$after" ]]; then
	echo "regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi

echo "== VENDOR.md carries the port row =="
grep -c 'mods/ITEMS/grug_smelting' VENDOR.md
