name = grug_artisans
title = Grudgelands Woodcarving and Goldsmithing
description = Woodcarver and Goldsmith material, gear and enchant catalogs.
depends = default, grug_core, grug_jobs, grug_inventory, grug_gear, grug_materials, grug_professions, grug_quality, grug_mobs, grug_gathering
