-- Enchant colours (docs/planning/round31-plan.md §2.2).
--
-- One fixed colour per affix stat (the nine stats of grug_quality's AFFIX
-- table): the prefix stat colours group A of an item's texture (accents),
-- the suffix stat group B (fittings). The nine are chosen to stay apart for
-- normal vision and red-green colour blindness (deuteranopia and protanopia;
-- tools/r31_b/build_preview.py measures the CIEDE2000 distances).
--
-- Here and not in grug_quality: grug_gear is the one mod both grug_quality
-- (per-stack inventory and wield images) and grug_visuals (the worn armour
-- composition) depend on, and it ships the textures and their masks.
--
-- The masks (`<texture>_ench.png`, generated by
-- tools/r31_b/gen_enchant_masks.py) hold group A in the top frame and group B
-- in the bottom frame, as opaque greyscale shading on transparency.

grug_gear.ENCHANT_COLORS = {
	str = "#9a2b10",                  -- Strength: deep red
	dex = "#20dea2",                  -- Dexterity: mint green
	int = "#4648a0",                  -- Intelligence: indigo
	max_hp_percent = "#b55370",       -- maximum HP: rose
	max_mana_percent = "#40dafd",     -- maximum Mana: sky blue
	crit_percent = "#eede22",         -- Crit: yellow
	attack_speed_percent = "#e0803c", -- attack speed: orange
	dodge_percent = "#937ffc",        -- Dodge: lavender
	armor_rating = "#ffffff",         -- armor rating: white
}

-- How strongly a group takes the shaded stat colour: 255 replaces the pixels,
-- 128 (the user's ruling, round31-plan.md §6 item 7) lays it over at 50 %,
-- so the material shows through.
grug_gear.ENCHANT_OPACITY = 128

-- The legend's order (the order of grug_quality's affix table).
grug_gear.ENCHANT_ORDER = {"str", "dex", "int", "max_hp_percent", "max_mana_percent",
	"crit_percent", "attack_speed_percent", "dodge_percent", "armor_rating"}

-- One coloured group: the mask frame, shaded by the stat colour.
local function layer(mask, frame, color)
	local out = "(" .. mask .. "^[verticalframe:2:" .. frame .. "^[multiply:" .. color
	if grug_gear.ENCHANT_OPACITY < 255 then
		out = out .. "^[opacity:" .. grug_gear.ENCHANT_OPACITY
	end
	return out .. ")"
end

local function mask_of(image)
	local stem = type(image) == "string" and image:match("^([%w_%-]+)%.png")
	return stem and stem .. "_ench.png" or nil
end

-- Just the coloured layers for `image` -- "(A)", "(B)" or "(A)^(B)", nil
-- without a known stat -- for a caller that places them itself (the worn
-- armour seam `armor_layers` of grug_visuals.compose). `image` is a texture
-- string whose first part is the source file ("grug_gear_bow_birch.png^[hsl:
-- 0:-20:16" is fine); `prefix` and `suffix` are stat ids or nil.
function grug_gear.enchant_layers(image, prefix, suffix)
	local a = prefix and grug_gear.ENCHANT_COLORS[prefix]
	local b = suffix and grug_gear.ENCHANT_COLORS[suffix]
	local mask = mask_of(image)
	if not mask or (not a and not b) then return nil end
	if a and b then return layer(mask, 0, a) .. "^" .. layer(mask, 1, b) end
	return a and layer(mask, 0, a) or layer(mask, 1, b)
end

-- The whole image. Without a known stat it comes back unchanged, byte for
-- byte, so an unenchanted item never gains a modifier.
function grug_gear.enchant_image(image, prefix, suffix)
	local layers = grug_gear.enchant_layers(image, prefix, suffix)
	return layers and image .. "^" .. layers or image
end

-- The image without its colour layers: for art drawn from an item's image
-- string on another shape (the Scout's bow draw stages), where the item's
-- masks do not fit.
function grug_gear.strip_enchant(image)
	local mask = mask_of(image)
	if not mask then return image end
	local at = image:find("^(" .. mask, 1, true)
	return at and image:sub(1, at - 1) or image
end

-- Only items registered with `_grug_enchant_masks = true` (grug_gear's
-- weapons, offhands and armour, whose textures ship masks) are coloured.
function grug_gear.has_enchant_masks(def)
	return type(def) == "table" and def._grug_enchant_masks == true and
		mask_of(def.inventory_image) ~= nil
end
