-- Vendor bracket gear (docs/design/items_crafting.md §3.8, curves §3.1/§3.2,
-- prices §8.2). Six catalogs, one per ten character levels; a player sees
-- their own bracket and every bracket below it.
--
-- Everything in here is GENERATED from the design curves, never hand-listed:
-- 6 weapon families x 6 brackets = 36 tools, plus 3 armor lines x 4 slots x
-- 6 brackets = 72 armor items and 12 offhands. All Common, therefore without enchants
-- (§3.8) and 10-15% behind crafted gear of the same era by construction.
--
-- ---------------------------------------------------------------------------
-- ITEM-LEVEL INTERFACE
-- ---------------------------------------------------------------------------
--   _grug_ilvl     The item level of the bracket. grug_inventory enforces it
--                  as the minimum level for the weapon slot
--                  (inventory_equipment.md §2, items_crafting.md §6.1).
--                  Items without an ilvl, including the starter weapons and
--                  tool-ladder axes, remain unrestricted.
--   _grug_quality  1 = Common for every item registered here. WP5 owns
--                  quality > 1, the enchant roll ranges behind it (§6.2/§6.3)
--                  and the colored display names that come with it. Nothing
--                  in WP7 rolls quality; the x3-priced rotating Uncommon of
--                  §3.8 is the trader task's job on top of WP5's roller.
-- ---------------------------------------------------------------------------
--
-- Trader interface (consumed by the vendor task): grug_gear.BRACKETS,
-- grug_gear.bracket_for_level, grug_gear.get_price, grug_gear.get_sell_price
-- and grug_gear.catalog. Rotation, vendors and UI live there, not here.
--
-- Textures: 16px originals of this project (CC0), generated by
-- tools/gen_mob_item_textures.py -- see LICENSE-media.md.

grug_gear = {}

--
-- Brackets. Prices are the §8.2 ladder VERBATIM: the x1.4 step is already
-- baked into the published numbers, and recomputing it from the bracket-1
-- anchor produces off-by-one rounding drift against the doc table.
--

grug_gear.BRACKETS = {
	{min_level =  1, max_level = 10, ilvl =  3, price = {weapon =  50, chest =  40, other =  25}},
	{min_level = 11, max_level = 20, ilvl = 10, price = {weapon =  70, chest =  56, other =  35}},
	{min_level = 21, max_level = 30, ilvl = 20, price = {weapon =  98, chest =  78, other =  49}},
	{min_level = 31, max_level = 40, ilvl = 30, price = {weapon = 137, chest = 110, other =  69}},
	{min_level = 41, max_level = 50, ilvl = 40, price = {weapon = 192, chest = 154, other =  96}},
	{min_level = 51, max_level = 60, ilvl = 50, price = {weapon = 269, chest = 215, other = 134}},
}

local NUM_BRACKETS = #grug_gear.BRACKETS

-- Bracket for a character level: ceil(level/10), clamped to the table.
function grug_gear.bracket_for_level(level)
	if type(level) ~= "number" then
		return 1
	end
	return math.max(1, math.min(NUM_BRACKETS, math.ceil(level / 10)))
end

--
-- Presentation. ONE ITEM PER CONCEPT (items_crafting.md §3.0.3, binding): the
-- six brackets are the six MATERIAL tiers and the items are named after their
-- material, not after a bracket adjective. The WP7 catalog's
-- Crude/Plain/Tempered/Reinforced/Superior/Grand is retired here (WP13 playtest
-- round 2, 2026-09-15), and so are the two `default` swords the ladder now
-- covers -- `grug_materials/content_curation.lua` unregisters those.
--
-- Nothing about the GENERATOR changed with the rename: the brackets, the ilvl
-- anchors, the prices, the damage curve and the armor curve are the same
-- numbers WP7 shipped.
--
-- Three naming ladders, one per line:
--   * metal   -- the six universal metals of §3.0.1, which are also the six
--                weapon materials and the six pick tiers;
--   * cloth   -- the Tailor's six bolt grades (§3.5); the doc's "T2 linen
--                cloth -> woven bolt" becomes the adjective `Woven`;
--   * leather -- the six leather grades (§3.4), registered alongside metal
--                and cloth as universal base armor; Leatherworkers refine
--                these base items through their profession recipes.
--
grug_gear.MATERIALS = {
	{metal = {key = "bronze", name = "Bronze"},
		cloth = {key = "patch", name = "Patch"},
		leather = {key = "light", name = "Light"}},
	{metal = {key = "iron", name = "Iron"},
		cloth = {key = "woven", name = "Woven"},
		leather = {key = "cured", name = "Cured"}},
	{metal = {key = "steel", name = "Steel"},
		cloth = {key = "heavy", name = "Heavy"},
		leather = {key = "heavy", name = "Heavy"}},
	{metal = {key = "silversteel", name = "Silversteel"},
		cloth = {key = "silkweave", name = "Silkweave"},
		leather = {key = "scaled", name = "Scaled"}},
	{metal = {key = "embersteel", name = "Embersteel"},
		cloth = {key = "silk", name = "Silk"},
		leather = {key = "sleek", name = "Sleek"}},
	{metal = {key = "abyssal_steel", name = "Abyssal Steel"},
		cloth = {key = "stormweave", name = "Stormweave"},
		leather = {key = "nightscale", name = "Nightscale"}},
}

-- Published, not local: grug_visuals tints the armor OVERLAYS on the player
-- model with the same six colours, and a second copy of this table would
-- drift the moment one of them is retuned.
--
-- WEAPONS NO LONGER USE IT. Every weapon family now ships one sprite per
-- material (`tools/wp13/gen_weapon_ladder.py`), so a Bronze Sword is bronze
-- because it is drawn bronze, not because a grey sprite is multiplied. The
-- tint survives for the two armor lines, which still share one silhouette per
-- slot -- `[multiply:#ffffff` is a no-op, so the sixth tier shows untinted art.
grug_gear.BRACKET_TINT = {"#8a7f6a", "#a89478", "#c0b088", "#d8cc9a",
	"#e8dcb0", "#ffffff"}
local BRACKET_TINT = grug_gear.BRACKET_TINT

-- Round 11 presentation is kept beside the catalog it dresses. These are
-- licensed inventory sprites, not gameplay identities or recipe routing.
local BOW_IMAGE = {
	"grug_gear_bow_lebethron.png",
	"grug_gear_bow_birch.png",
	"grug_gear_bow_birch.png^[hsl:0:-20:16",
	"grug_gear_bow_mallorn.png",
	"grug_gear_bow_alder.png^[colorize:#b94a24:38",
	"grug_gear_bow_birch.png^[colorize:#69458c:92",
}
local SHIELD_IMAGE = {
	"grug_gear_shield_bronze.png",
	"grug_gear_shield_iron.png^[hsl:0:-100:-12",
	"grug_gear_shield_steel.png", "grug_gear_shield_silversteel.png",
	"grug_gear_shield_embersteel.png^[colorize:#9f2418:112",
	"grug_gear_shield_abyssal_steel.png",
}
local BOOK_IMAGE = "grug_gear_spellbook.png"

-- Item description (§6.1): name, item level, then the BASE stat line -- the
-- number the item actually contributes, so a player can compare two pieces
-- without doing the curve in their head. Grey, because it is derived data
-- rather than part of the name.
--
-- WP5 NOTE: when the enchant roller starts regenerating descriptions from
-- meta, it must KEEP these two lines and append one line per enchant below
-- them (§6.1) -- the base stat does not live in meta and cannot be
-- reconstructed from the roll.
--
-- No colorize on the name itself: Common is plain white, WP5 owns the
-- quality colors.
local STAT_COLOR = "#9aa0a6"

local function describe(material, noun, ilvl, stat_line)
	local name = noun and (material .. " " .. noun) or material
	local level_line = ilvl and ("\nItem level " .. ilvl) or ""
	return name .. level_line ..
		"\n" .. core.colorize(STAT_COLOR, stat_line)
end

-- "5 damage, 1.0 s swing" -- full_punch_interval is the authoritative
-- soft-lock clock interval for swing abilities and the native fraction's
-- denominator for ordinary tools/fists (combat_stats.md §2), so it belongs
-- next to the damage number: a dagger
-- doing less per swing but swinging faster is otherwise invisible.
--
-- Two-handed weapons say so HERE as well as in the equip refusal (B4): the
-- rule costs a greataxe user their offhand torch, and combat_stats.md §7 wants
-- that to be a decision, not a surprise. The refusal explains it at the moment
-- it bites; this line lets a player see it before they buy the thing.
local function weapon_stats(damage, fpi, hands)
	local line = string.format("%d damage, %.1f s swing", damage, fpi)
	if hands >= 2 then
		line = line .. ", two-handed"
	end
	return line
end

local ARMOR_LABELS = {[1] = "Cloth", [2] = "Leather", [3] = "Metal"}

local function armor_stats(armor)
	return string.format("%d armor rating", armor)
end

--
-- Weapons (§3.2). Base 1H damage curve; the family factor multiplies the
-- ROUNDED 1H value, exactly as the §3.2 table is built.
--
-- Verified against the §3.8 row: ilvl 3/10/20/30/40/50 -> 5/8/11/15/18/22.
--
-- How damage reaches a mob (WP38): a swing ability builds one authoritative
-- full hit from this fleshy value + floor(Str/10) at this interval, then armor
-- and one crit roll. Ordinary wielded tools/fists keep mobs_redo's proportional
-- `clamp(tflp/fpi, 0, 1)` path. `full_punch_interval` is therefore both the
-- ability clock and the ordinary path's damage-scaler denominator;
-- `damage_groups.fleshy` is one full swing's base strength.
--

-- `hands` is published as `_grug_hands` and enforced by grug_inventory's equip
-- filter (weapon-slot design B4, combat_stats.md §7): a two-handed weapon
-- needs an empty offhand and blocks the offhand while equipped. It is a
-- DECLARATION here, never a check -- grug_gear registers items, the equipment
-- lists are the only place that knows what a free hand is.
--
-- greataxe and staff are the two-handers; sword, dagger and every caster 1H
-- family are one-handed. Anything
-- that does not declare the field at all counts as one-handed, which is what
-- keeps the rule additive for torches, shields and every future offhand item.
local WEAPONS = {
	-- `fixed` = always on sale; the rest are the rotation pool of §3.8.
	{key = "sword",    noun = "Sword",    fpi = 1.0, factor = 1.0, hands = 1, group = "sword", fixed = true},
	{key = "dagger",   noun = "Dagger",   fpi = 0.7, factor = 0.7, hands = 1, group = "sword"},
	{key = "greataxe", noun = "Battle Axe", fpi = 1.4, factor = 1.5, hands = 2, group = "axe"},
	{key = "staff",    noun = "Staff",    fpi = 1.4, factor = 1.2, hands = 2, group = "staff"},
	{key = "wand",     noun = "Wand",     fpi = 1.0, factor = 1.0, hands = 1, group = "wand", caster = true},
	{key = "bow",      noun = "Bow",      fpi = 1.0, factor = 1.0, hands = 2,
		group = "bow", bow = true},
}

function grug_gear.weapon_damage_at_level(ilvl, family)
	local factor = 1
	for _, weapon in ipairs(WEAPONS) do
		if weapon.key == family then
			factor = weapon.factor
			break
		end
	end
	local one_hand = math.floor(4 + 0.35 * ilvl + 0.5)
	return math.max(1, math.floor(one_hand * factor + 0.5))
end

--
-- Armor (§3.1). Set totals are linear fits through the tier table
-- (T1..T4 at ilvl 12/27/42/57), verified in Lua before the coefficients were
-- committed to:
--
--   metal   ilvl 12/27/42/57 -> 16.00 / 29.00 / 42.00 / 55.00  (doc 16/29/42/55) exact
--   cloth   ilvl 12/27/42/57 ->  5.00 /  8.33 / 11.67 / 15.00  (doc  5/ 8/11/15)
--   leather ilvl 12/27/42/57 -> 11.00 / 20.67 / 30.33 / 40.00  (doc 11/20/30/40)
--
-- Two doc cells do not round to their table value: cloth at ilvl 42 rounds
-- to 12 (doc 11) and leather at ilvl 27 rounds to 21 (doc 20). Both are
-- interior points of a fit anchored on T1/T4 -- reported as findings; the
-- vendor brackets stop at ilvl 50 and none of them touches those cells.
--
-- Round 10 registers all three material lines across six tiers. Universal
-- base recipes include leather; class armor-rank eligibility still governs
-- wearing a piece independently of who can craft it.
--

local ARMOR_LINES = {
	{key = "metal", rank = 3, base = 5.6, per_ilvl = 0.86667, register = true,
		nouns = {head = "Helm", chest = "Chestplate", legs = "Greaves", feet = "Sabatons"}},
	{key = "leather", rank = 2, base = 3.2667, per_ilvl = 0.64444, register = true,
		nouns = {head = "Hood", chest = "Jerkin", legs = "Pants", feet = "Boots"}},
	{key = "cloth", rank = 1, base = 2.3333, per_ilvl = 0.22222, register = true,
		nouns = {head = "Cowl", chest = "Robe", legs = "Leggings", feet = "Slippers"}},
}

-- Per-piece split of the set total (§3.1: chest/legs/head/feet 35/27/22/16%).
local ARMOR_SLOTS = {
	{key = "head",  share = 0.22},
	{key = "chest", share = 0.35},
	{key = "legs",  share = 0.27},
	{key = "feet",  share = 0.16},
}

-- Public description-regeneration seam for grug_quality. It returns every
-- definition-derived line below the display name, recomputing the base stat at
-- a per-stack ilvl instead of copying a bracket anchor. Affixes and name
-- coloring remain grug_quality's per-stack work.
function grug_gear.describe_stack_base(stack, ilvl)
	local def = stack:get_definition() or {}
	local groups = def.groups or {}
	if (groups.grug_equip_trinket or 0) > 0 then
		local special = stack:get_meta():get_string("grug_trinket_special")
		if special == "" then special = tostring(def._grug_trinket_special or "") end
		-- Trinkets keep the item-level line above their authored special
		-- (review finding, R9-PROF-B): the special alone hid the ilvl.
		local trinket_lines = {}
		if ilvl then trinket_lines[#trinket_lines + 1] = "Item level " .. ilvl end
		if special == "" then return trinket_lines, {} end
		trinket_lines[#trinket_lines + 1] = core.colorize(STAT_COLOR, special)
		return trinket_lines, {trinket_special = special}
	end
	local lines = {}
	if ilvl then lines[#lines + 1] = "Item level " .. ilvl end
	if (groups.grug_equip_weapon or 0) > 0 then
		local family = stack:get_name():match("^grug_gear:([a-z]+)_")
		local base_caps = def.tool_capabilities or {}
		local damage = family and grug_gear.weapon_damage_at_level(ilvl or
			def._grug_ilvl or 1, family) or
			(base_caps.damage_groups and base_caps.damage_groups.fleshy or 0)
		if damage > 0 then
			lines[#lines + 1] = core.colorize(STAT_COLOR, weapon_stats(damage,
				base_caps.full_punch_interval or 1.4, def._grug_hands or 1))
		end
		return lines, {damage = damage,
			full_punch_interval = base_caps.full_punch_interval or 1.4}
	end
	if (groups.grug_shield or 0) > 0 then
		local rating = tonumber(def._grug_armor) or 0
		if ilvl then
			rating = 0
			local line = ARMOR_LINES[1]
			for _, slot in ipairs(ARMOR_SLOTS) do
				rating = rating + math.max(1, math.floor(
					(line.base + line.per_ilvl * ilvl) * slot.share + 0.5))
			end
		end
		lines[#lines + 1] = core.colorize(STAT_COLOR, rating .. " armor rating")
		return lines, {armor = rating}
	end
	if (groups.grug_spellbook or 0) > 0 then
		local mana = tonumber(def._grug_max_mana_percent) or 0
		lines[#lines + 1] = core.colorize(STAT_COLOR,
			"+" .. string.format("%.2g", mana) .. "% maximum Mana")
		return lines, {max_mana_percent = mana}
	end
	local rank = tonumber(groups.grug_armor_class)
	if rank then
		lines[#lines + 1] = core.colorize(STAT_COLOR, ARMOR_LABELS[rank] or "Armor")
		local line_key = rank == 3 and "metal" or rank == 2 and "leather" or
			"cloth"
		local slot_key
		for _, slot in ipairs(ARMOR_SLOTS) do
			if (groups["grug_equip_" .. slot.key] or 0) > 0 then
				slot_key = slot.key
				break
			end
		end
		local line
		for _, candidate in ipairs(ARMOR_LINES) do
			if candidate.key == line_key then line = candidate break end
		end
		local share
		for _, candidate in ipairs(ARMOR_SLOTS) do
			if candidate.key == slot_key then share = candidate.share break end
		end
		local armor
		if line and share and ilvl then
			armor = math.max(1, math.floor((line.base + line.per_ilvl * ilvl)
				* share + 0.5))
		else
			armor = tonumber(def._grug_armor) or 0
		end
		if armor > 0 then
			lines[#lines + 1] = core.colorize(STAT_COLOR, armor_stats(armor))
		end
		return lines, {armor = armor}
	end
	local description = tostring(def.description or "")
	for line in description:gmatch("[^\n]+") do
		if line ~= description:match("^[^\n]+") and
				not line:match("^Effective at level %d+:") then
			lines[#lines + 1] = line
		end
	end
	return lines, {}
end

--
-- Prices. `get_price` is what the player pays a vendor, `get_sell_price` the
-- vendor buy-back at 25% (also mirrored into `_grug_sell_price`, the field
-- every trader already reads on mob drops).
--

local buy_price = {}
local sell_price = {}

local function buyback(price)
	return math.max(1, math.floor(price * 0.25))
end

-- copper, or nil for anything that is not vendor gear
function grug_gear.get_price(itemname)
	return buy_price[itemname]
end

function grug_gear.get_sell_price(itemname)
	return sell_price[itemname]
end

local REPAIR_STARTER_PRICE = {
	["default:pick_wood"] = 5, ["default:shovel_wood"] = 5,
	["default:axe_wood"] = 5,
	["grug_farming:hoe"] = 5,
	["default:pick_stone"] = 10, ["default:shovel_stone"] = 10,
	["default:axe_stone"] = 10, ["grug_farming:hoe_stone"] = 10,
	["grug_inventory:quiver"] = grug_gear.BRACKETS[1].price.other,
}
local REPAIR_TIER_TOOL = {}
for tier, names in ipairs({
	{"default:pick_bronze", "default:axe_bronze", "default:shovel_bronze", "grug_farming:hoe_bronze"},
	{"grug_materials:pick_iron", "grug_materials:axe_iron", "grug_materials:shovel_iron", "grug_farming:hoe_iron"},
	{"default:pick_steel", "default:axe_steel", "default:shovel_steel", "grug_farming:hoe_steel"},
	{"grug_materials:pick_silversteel", "grug_materials:axe_silversteel", "grug_materials:shovel_silversteel", "grug_farming:hoe_silversteel"},
	{"grug_materials:pick_embersteel", "grug_materials:axe_embersteel", "grug_materials:shovel_embersteel", "grug_farming:hoe_embersteel"},
	{"grug_materials:pick_abyssal_steel", "grug_materials:axe_abyssal_steel", "grug_materials:shovel_abyssal_steel", "grug_farming:hoe_abyssal_steel"},
}) do
	for _, itemname in ipairs(names) do REPAIR_TIER_TOOL[itemname] = tier end
end

-- Canonical regular-purchase reference price for the repair service. This is
-- independent of vendor rotation and never derives a sell-back price.
function grug_gear.reference_purchase_price(item)
	local stack = type(item) == "string" and ItemStack(item) or item
	if not stack or stack:is_empty() then return nil end
	local itemname = stack:get_name()
	local base = buy_price[itemname] or REPAIR_STARTER_PRICE[itemname]
	local tool_tier = REPAIR_TIER_TOOL[itemname]
	if not base and tool_tier then
		base = grug_gear.BRACKETS[tool_tier].price.weapon
	end
	if not base then
		local bracket = tonumber((stack:get_definition() or {})._grug_bracket)
		local groups = (stack:get_definition() or {}).groups or {}
		if bracket and grug_gear.BRACKETS[bracket] and
				((groups.pickaxe or 0) > 0 or (groups.axe or 0) > 0 or
				(groups.shovel or 0) > 0 or (groups.hoe or 0) > 0) then
			base = grug_gear.BRACKETS[bracket].price.weapon
		end
	end
	if not base then return nil end
	local quality = stack:get_meta():get_int("grug_quality")
	if quality == 0 then quality = tonumber((stack:get_definition() or {})._grug_quality) or 1 end
	return base * (({[1] = 1, [2] = 3, [3] = 6})[quality] or 1)
end

--
-- Generation.
--

grug_gear.catalog = {}

-- The one place an item NAME is built from a family and a tier. Every consumer
-- that knows a family and a bracket -- grug_visuals' `weapon_family` shorthand
-- for the guards and bandits, the gear-catalogue KAT, a later drop table --
-- asks here instead of concatenating `_b<n>` (which is exactly what this round
-- renamed away).
function grug_gear.weapon_item(family, bracket)
	local material = grug_gear.MATERIALS[bracket]
	if type(family) ~= "string" or not material then
		return nil
	end
	return "grug_gear:" .. family .. "_" .. material.metal.key
end

function grug_gear.armor_item(slot, line, bracket)
	local material = grug_gear.MATERIALS[bracket]
	if type(slot) ~= "string" or not material or not material[line] then
		return nil
	end
	return "grug_gear:" .. slot .. "_" .. line .. "_" .. material[line].key
end

local tool_count, craftitem_count = 0, 0

for bracket, br in ipairs(grug_gear.BRACKETS) do
	local cat = {fixed = {}, extras = {}, all = {}}
	grug_gear.catalog[bracket] = cat

	local metal = grug_gear.MATERIALS[bracket].metal

	for _, w in ipairs(WEAPONS) do
		local itemname = grug_gear.weapon_item(w.key, bracket)
		local damage = grug_gear.weapon_damage_at_level(br.ilvl, w.key)
		-- Every weapon family is weapon-slot eligible (weapon-slot design B3).
		-- No class gate: weapon families are class FLAVOR, not a power ladder
		-- (§8.2), so a Mage may equip a greataxe and simply gains nothing from
		-- it; the only gate on the slot is the `_grug_ilvl` minimum. The slot
		-- itself is family-agnostic, which is how the future bow family joins
		-- without a second slot.
		local groups = {grug_gear = 1, grug_equip_weapon = 1}
		groups[w.group] = 1
		if w.caster then groups.grug_caster_weapon = 1 end
		if w.bow then groups.grug_bow = 1 end
		local image = "grug_gear_item_" .. w.key .. "_" .. metal.key .. ".png"
		if w.bow then image = BOW_IMAGE[bracket] end
		core.register_tool(itemname, {
			description = describe(metal.name, w.noun, br.ilvl,
				weapon_stats(damage, w.fpi, w.hands)),
			-- One sprite per family AND material, all in the one diagonal
			-- convention (grip bottom-left) the wield transform is derived for.
			inventory_image = image,
			groups = groups,
			stack_max = 1,
			tool_capabilities = {
				full_punch_interval = w.fpi,
				damage_groups = {fleshy = damage},
				max_drop_level = 0,
				groupcaps = {},
			},
			_grug_ilvl = br.ilvl,
			_grug_req_level = bracket == 1 and 1 or br.ilvl,
			_grug_bracket = bracket,
			_grug_quality = 1,
			_grug_hands = w.hands,
			_grug_bow_draw_time = w.bow and 0.5 or nil,
			_grug_bow_range = w.bow and 25 or nil,
			_grug_sell_price = buyback(br.price.weapon),
		})
		buy_price[itemname] = br.price.weapon
		sell_price[itemname] = buyback(br.price.weapon)
		table.insert(w.fixed and cat.fixed or cat.extras, itemname)
		tool_count = tool_count + 1
	end

	-- Offhands use the matching bracket's "other" purchase reference. A shield's
	-- base rating equals the complete same-ilvl unrefined metal set; spellbooks
	-- carry only their authored mana line before ordinary affixes.
	local metal_line = ARMOR_LINES[1]
	local shield_rating = 0
	for _, slot in ipairs(ARMOR_SLOTS) do
		shield_rating = shield_rating + math.max(1, math.floor(
			(metal_line.base + metal_line.per_ilvl * br.ilvl) * slot.share + 0.5))
	end
	local shield = "grug_gear:shield_" .. metal.key
	core.register_craftitem(shield, {
		description = describe(metal.name, "Shield", br.ilvl,
			shield_rating .. " armor rating"),
		inventory_image = SHIELD_IMAGE[bracket],
		groups = {grug_gear = 1, grug_equip_offhand = 1, grug_shield = 1},
		stack_max = 1, _grug_armor = shield_rating, _grug_ilvl = br.ilvl,
		_grug_bracket = bracket, _grug_quality = 1, _grug_hands = 1,
		_grug_quality_family = "shield", _grug_sell_price = buyback(br.price.other),
	})
	buy_price[shield], sell_price[shield] = br.price.other, buyback(br.price.other)
	local mana = math.ceil(bracket / 2)
	local book = "grug_gear:spellbook_" .. metal.key
	core.register_craftitem(book, {
		description = describe(metal.name, "Spellbook", br.ilvl,
			"+" .. mana .. "% maximum Mana"),
		inventory_image = BOOK_IMAGE .. "^[colorize:" .. BRACKET_TINT[bracket] .. ":48",
		groups = {grug_gear = 1, grug_equip_offhand = 1, grug_spellbook = 1},
		stack_max = 1, _grug_max_mana_percent = mana, _grug_ilvl = br.ilvl,
		_grug_bracket = bracket, _grug_quality = 1, _grug_hands = 1,
		_grug_quality_family = "spellbook", _grug_sell_price = buyback(br.price.other),
	})
	buy_price[book], sell_price[book] = br.price.other, buyback(br.price.other)

	for _, line in ipairs(ARMOR_LINES) do
		if line.register then
			local total = line.base + line.per_ilvl * br.ilvl
			local grade = grug_gear.MATERIALS[bracket][line.key]
			for _, slot in ipairs(ARMOR_SLOTS) do
				local itemname = grug_gear.armor_item(slot.key, line.key, bracket)
				-- max(1) is a deliberate deviation from the raw split: at the
				-- low cloth brackets the 16% foot share rounds to 0, and a
				-- 0-armor boot is a bug, not a design statement.
				local armor = math.max(1, math.floor(total * slot.share + 0.5))
				local price = br.price.other
				if slot.key == "chest" then
					price = br.price.chest
				end
				local armor_image = "grug_gear_item_" .. slot.key .. "_" ..
					line.key .. "_" .. grade.key .. ".png"
				if line.key == "metal" and grade.key == "silversteel" then
					armor_image = armor_image .. "^[hsl:0:-90:5"
				end
				core.register_craftitem(itemname, {
					description = describe(grade.name, line.nouns[slot.key],
						br.ilvl, ARMOR_LABELS[line.rank] .. "\n" .. armor_stats(armor)),
					inventory_image = armor_image,
					groups = {
						["grug_equip_" .. slot.key] = 1,
						grug_armor_class = line.rank,
						grug_gear = 1,
					},
					stack_max = 1,
					_grug_armor = armor,
					_grug_ilvl = br.ilvl,
					_grug_bracket = bracket,
					_grug_quality = 1,
					_grug_sell_price = buyback(price),
				})
				buy_price[itemname] = price
				sell_price[itemname] = buyback(price)
				table.insert(cat.fixed, itemname)
				craftitem_count = craftitem_count + 1
			end
		end
	end

	-- `all` = the full bracket (15 items), the pool the Uncommon roll of
	-- §3.8 draws from; fixed first so the order stays stable for the UI.
	for _, itemname in ipairs(cat.fixed) do
		table.insert(cat.all, itemname)
	end
	for _, itemname in ipairs(cat.extras) do
		table.insert(cat.all, itemname)
	end
end

-- Class starter equipment uses the first ordinary material tier.
grug_gear.STARTER_STAFF = "grug_gear:staff_bronze"
grug_gear.STARTER_BOW = "grug_gear:bow_bronze"
grug_gear.STARTER_SWORD = "grug_gear:sword_bronze"

core.register_craftitem("grug_gear:arrow", {
	description = "Arrow", inventory_image = "grug_gear_arrow.png",
	groups = {grug_arrow = 1}, stack_max = 200, _grug_sell_price = 1,
})
dofile(core.get_modpath("grug_gear") .. "/trinkets.lua")

core.log("action", "[grug_gear] " .. NUM_BRACKETS .. " bracket catalogs: " ..
	tool_count .. " weapons + " .. craftitem_count .. " armor pieces")

-- Refresh weapon descriptions after all item registrations.
core.register_on_mods_loaded(function()
	for itemname, def in pairs(core.registered_items) do
		if def.groups and def.groups.grug_equip_weapon then
			local caps = def.tool_capabilities or {}
			local damage_groups = caps.damage_groups or {}
			local damage = damage_groups.fleshy
			if type(damage) == "number" and damage > 0 then
				local label = ((def.description or itemname):gsub("\n.*", ""))
				local stat_line = weapon_stats(damage,
					caps.full_punch_interval or 1.4, def._grug_hands or 1)
				core.override_item(itemname, {
					description = describe(label, nil, def._grug_ilvl, stat_line),
				})
			end
		end
	end
end)

-- Apply the player-specific effective line to one concrete weapon stack.
-- Item level already changes the weapon's authored base damage; there is no
-- second ilvl multiplier here or in the combat pipeline. Returns true only
-- when the caller has a changed ItemStack copy to write or hand on.
function grug_gear.initialize_weapon_tooltip(stack, player)
	local class_api = rawget(_G, "grug_classes")
	local xp_api = rawget(_G, "grug_xp")
	if not class_api or not xp_api or not stack or stack:is_empty() then
		return false
	end
	local meta = stack:get_meta()
	local original_description = meta:get_string("description")
	local quality_api = rawget(_G, "grug_items")
	if quality_api and
			type(quality_api.regenerate_description) == "function" then
		quality_api.regenerate_description(stack, player)
	end
	local def = stack:get_definition()
	if not def or not def.groups or (def.groups.grug_equip_weapon or 0) <= 0 then
		return meta:get_string("description") ~= original_description
	end
	local caps = stack:get_tool_capabilities() or {}
	local damage = caps.damage_groups and caps.damage_groups.fleshy or 0
	if type(damage) ~= "number" or damage <= 0 then
		return meta:get_string("description") ~= original_description
	end
	local level = xp_api.get_level(player)
	local effective = math.max(1, math.floor(
		(damage + class_api.get_melee_bonus(player))
		* grug_core.level_scale(level)))
	local base = meta:get_string("description")
	if base == "" then
		base = def.description or stack:get_name()
	end
	base = base:gsub("\nEffective at level %d+: %d+ damage per swing", "")
	local desired = base ..
		("\nEffective at level %d: %d damage per swing"):format(level, effective)
	if meta:get_string("description") == desired then
		return desired ~= original_description
	end
	meta:set_string("description", desired)
	return desired ~= original_description
end

-- Refresh every weapon stack the player can see, including the one just moved
-- out of the equipment slot; otherwise a traded or levelled unequipped weapon
-- would retain somebody else's effective line.
local function refresh_weapon_descriptions(player)
	local inventory_api = rawget(_G, "grug_inventory")
	if not inventory_api then
		return
	end
	local inventory = player:get_inventory()
	local lists = inventory:get_lists()
	local equipment_changed = false
	for listname, stacks in pairs(lists) do
		for index = 1, #stacks do
			local stack = inventory:get_stack(listname, index)
			if grug_gear.initialize_weapon_tooltip(stack, player) then
				inventory:set_stack(listname, index, stack)
				if listname == "grug_weapon" then
					equipment_changed = true
				end
			end
		end
	end
	if equipment_changed then
		inventory_api.equipment_changed(player, "grug_weapon")
	end
end

-- One acquisition initializer, used by each engine-owned acquisition boundary.
-- Crafting can replace its output directly. Item pickup must perform builtin's
-- add itself only for a changed weapon because returning a callback result
-- suppresses builtin's default add. Trader purchases call the same initializer
-- immediately before their direct add_item write.
core.register_on_craft(function(itemstack, player)
	if grug_gear.initialize_weapon_tooltip(itemstack, player) then
		return itemstack
	end
end)

core.register_on_item_pickup(function(itemstack, picker)
	if not picker or not picker.is_player or not picker:is_player() or
			not grug_gear.initialize_weapon_tooltip(itemstack, picker) then
		return
	end
	local inventory = picker:get_inventory()
	return inventory and inventory:add_item("main", itemstack) or itemstack
end)

core.register_on_mods_loaded(function()
	local inventory_api = rawget(_G, "grug_inventory")
	local xp_api = rawget(_G, "grug_xp")
	if not inventory_api or not xp_api or
			type(inventory_api.equipment_changed) ~= "function" or
			type(xp_api.register_on_level_change) ~= "function" then
		return
	end
	grug_core.register_on_equipment_change(function(player, listname)
		if listname == nil or listname == "grug_weapon" then
			refresh_weapon_descriptions(player)
		end
	end)
	xp_api.register_on_level_change(function(player, old_level)
		if old_level ~= nil then
			refresh_weapon_descriptions(player)
		end
	end)
end)
