-- Vendor bracket gear (docs/design/items_crafting.md §3.8, curves §3.1/§3.2,
-- prices §8.2). Six catalogs, one per ten character levels; a player sees
-- their own bracket and every bracket below it.
--
-- Everything in here is GENERATED from the design curves, never hand-listed:
-- 4 weapon families x 6 brackets = 24 tools, plus 2 armor lines x 4 slots x
-- 6 brackets = 48 craftitems. All Common, therefore all without enchants
-- (§3.8) and 10-15% behind crafted gear of the same era by construction.
--
-- ---------------------------------------------------------------------------
-- WP5 INTERFACE -- deliberately NOT implemented in WP7
-- ---------------------------------------------------------------------------
--   _grug_ilvl     The item level of the bracket. WP5 turns this into the
--                  per-stack item-meta `grug_req_level` and enforces it in
--                  the equip filter (inventory_equipment.md §2,
--                  items_crafting.md §6.1). WP7 only publishes the number:
--                  there is no level check anywhere in this mod, and none in
--                  grug_inventory's equip filter either.
--   _grug_quality  1 = Common for every item registered here. WP5 owns
--                  quality > 1, the enchant roll ranges behind it (§6.2/§6.3)
--                  and the colored display names that come with it. Nothing
--                  in WP7 rolls quality; the x3-priced rotating Uncommon of
--                  §3.8 is the trader task's job on top of WP5's roller.
-- ---------------------------------------------------------------------------
--
-- Trader interface (consumed by the vendor task): grug_gear.BRACKETS,
-- grug_gear.bracket_for_level, grug_gear.get_price, grug_gear.get_sell_price
-- and grug_gear.catalog. Rotation, vendors and UI live there, not here.
--
-- Textures: 16px originals of this project (CC0), generated by
-- tools/gen_mob_item_textures.py -- see LICENSE-media.md.

grug_gear = {}

--
-- Brackets. Prices are the §8.2 ladder VERBATIM: the x1.4 step is already
-- baked into the published numbers, and recomputing it from the bracket-1
-- anchor produces off-by-one rounding drift against the doc table.
--

grug_gear.BRACKETS = {
	{min_level =  1, max_level = 10, ilvl =  3, price = {weapon =  50, chest =  40, other =  25}},
	{min_level = 11, max_level = 20, ilvl = 10, price = {weapon =  70, chest =  56, other =  35}},
	{min_level = 21, max_level = 30, ilvl = 20, price = {weapon =  98, chest =  78, other =  49}},
	{min_level = 31, max_level = 40, ilvl = 30, price = {weapon = 137, chest = 110, other =  69}},
	{min_level = 41, max_level = 50, ilvl = 40, price = {weapon = 192, chest = 154, other =  96}},
	{min_level = 51, max_level = 60, ilvl = 50, price = {weapon = 269, chest = 215, other = 134}},
}

local NUM_BRACKETS = #grug_gear.BRACKETS

-- Bracket for a character level: ceil(level/10), clamped to the table.
function grug_gear.bracket_for_level(level)
	if type(level) ~= "number" then
		return 1
	end
	return math.max(1, math.min(NUM_BRACKETS, math.ceil(level / 10)))
end

--
-- Presentation. One art per family/slot, differentiated per bracket by a
-- texture modifier instead of six PNGs each -- `[multiply:#ffffff` is a
-- no-op, so bracket 6 shows the untinted art.
--

local BRACKET_TINT = {"#8a7f6a", "#a89478", "#c0b088", "#d8cc9a", "#e8dcb0", "#ffffff"}
local BRACKET_ADJECTIVE = {"Crude", "Plain", "Tempered", "Reinforced", "Superior", "Grand"}

-- Item description (§6.1): name, item level, then the BASE stat line -- the
-- number the item actually contributes, so a player can compare two pieces
-- without doing the curve in their head. Grey, because it is derived data
-- rather than part of the name.
--
-- WP5 NOTE: when the enchant roller starts regenerating descriptions from
-- meta, it must KEEP these two lines and append one line per enchant below
-- them (§6.1) -- the base stat does not live in meta and cannot be
-- reconstructed from the roll.
--
-- No colorize on the name itself: Common is plain white, WP5 owns the
-- quality colors.
local STAT_COLOR = "#9aa0a6"

local function describe(bracket, noun, ilvl, stat_line)
	return BRACKET_ADJECTIVE[bracket] .. " " .. noun ..
		"\nItem level " .. ilvl ..
		"\n" .. core.colorize(STAT_COLOR, stat_line)
end

-- "5 damage, 1.0 s swing" -- full_punch_interval IS the auto-attack cadence
-- (combat_stats.md §2), so it belongs next to the damage number: a dagger
-- doing less per swing but swinging faster is otherwise invisible.
--
-- Two-handed weapons say so HERE as well as in the equip refusal (B4): the
-- rule costs a greataxe user their offhand torch, and combat_stats.md §7 wants
-- that to be a decision, not a surprise. The refusal explains it at the moment
-- it bites; this line lets a player see it before they buy the thing.
local function weapon_stats(damage, fpi, hands)
	local line = string.format("%d damage, %.1f s swing", damage, fpi)
	if hands >= 2 then
		line = line .. ", two-handed"
	end
	return line
end

-- "3 armor (-3% damage taken)" -- 1 armor point = 1% reduction
-- (items_crafting.md §3.1), capped at 60% across all four pieces.
local function armor_stats(armor)
	return string.format("%d armor (-%d%% damage taken)", armor, armor)
end

--
-- Weapons (§3.2). Base 1H damage curve; the family factor multiplies the
-- ROUNDED 1H value, exactly as the §3.2 table is built.
--
-- Verified against the §3.8 row: ilvl 3/10/20/30/40/50 -> 5/8/11/15/18/22.
--
-- How the damage actually reaches a mob (mobs/api.lua on_punch, WP38
-- proportional melee): fleshy damage × clamp(tflp/fpi, 0, 1) + floor(Str/10),
-- scaled by the mob's armor group, then the melee crit roll. The
-- `full_punch_interval` is therefore BOTH the damage-scaler denominator and
-- the swing time of the Strike loop, and `damage_groups.fleshy` is the
-- strength of one full swing. Those two fields are the whole contract;
-- nothing else in tool_capabilities is read.
--

local function dmg1h(ilvl)
	return math.floor(4 + 0.35 * ilvl + 0.5)
end

-- `hands` is published as `_grug_hands` and enforced by grug_inventory's equip
-- filter (weapon-slot design B4, combat_stats.md §7): a two-handed weapon
-- needs an empty offhand and blocks the offhand while equipped. It is a
-- DECLARATION here, never a check -- grug_gear registers items, the equipment
-- lists are the only place that knows what a free hand is.
--
-- greataxe and staff are the two-handers; sword and dagger are one-handed, and
-- so is the caster 1H (wand/tome) once §3.2's caster family exists. Anything
-- that does not declare the field at all counts as one-handed, which is what
-- keeps the rule additive for torches, shields and every future offhand item.
local WEAPONS = {
	-- `fixed` = always on sale; the rest are the rotation pool of §3.8.
	{key = "sword",    noun = "Sword",    fpi = 1.0, factor = 1.0, hands = 1, group = "sword", fixed = true},
	{key = "dagger",   noun = "Dagger",   fpi = 0.7, factor = 0.7, hands = 1, group = "sword"},
	{key = "greataxe", noun = "Greataxe", fpi = 1.4, factor = 1.5, hands = 2, group = "axe"},
	{key = "staff",    noun = "Staff",    fpi = 1.4, factor = 1.2, hands = 2, group = "staff"},
}

--
-- Armor (§3.1). Set totals are linear fits through the tier table
-- (T1..T4 at ilvl 12/27/42/57), verified in Lua before the coefficients were
-- committed to:
--
--   metal   ilvl 12/27/42/57 -> 16.00 / 29.00 / 42.00 / 55.00  (doc 16/29/42/55) exact
--   cloth   ilvl 12/27/42/57 ->  5.00 /  8.33 / 11.67 / 15.00  (doc  5/ 8/11/15)
--   leather ilvl 12/27/42/57 -> 11.00 / 20.67 / 30.33 / 40.00  (doc 11/20/30/40)
--
-- Two doc cells do not round to their table value: cloth at ilvl 42 rounds
-- to 12 (doc 11) and leather at ilvl 27 rounds to 21 (doc 20). Both are
-- interior points of a fit anchored on T1/T4 -- reported as findings; the
-- vendor brackets stop at ilvl 50 and none of them touches those cells.
--
-- Only metal and cloth ship (decided 2026-08-07): the MVP classes are
-- Warrior (rank 3) / Mage (rank 1) / Priest (rank 1), so nothing can wear
-- rank 2 and 24 leather items would be dead weight. The leather curve stays
-- here so the coefficients never have to be re-derived -- it is registered
-- with the Rogue (Phase 2) / the WP5 drop tables.
--

local ARMOR_LINES = {
	{key = "metal", rank = 3, base = 5.6, per_ilvl = 0.86667, register = true,
		nouns = {head = "Helm", chest = "Chestplate", legs = "Greaves", feet = "Sabatons"}},
	{key = "leather", rank = 2, base = 3.2667, per_ilvl = 0.64444, register = false,
		nouns = {head = "Hood", chest = "Jerkin", legs = "Pants", feet = "Boots"}},
	{key = "cloth", rank = 1, base = 2.3333, per_ilvl = 0.22222, register = true,
		nouns = {head = "Cowl", chest = "Robe", legs = "Leggings", feet = "Slippers"}},
}

-- Per-piece split of the set total (§3.1: chest/legs/head/feet 35/27/22/16%).
local ARMOR_SLOTS = {
	{key = "head",  share = 0.22},
	{key = "chest", share = 0.35},
	{key = "legs",  share = 0.27},
	{key = "feet",  share = 0.16},
}

--
-- Prices. `get_price` is what the player pays a vendor, `get_sell_price` the
-- vendor buy-back at 25% (also mirrored into `_grug_sell_price`, the field
-- every trader already reads on mob drops).
--

local buy_price = {}
local sell_price = {}

local function buyback(price)
	return math.max(1, math.floor(price * 0.25))
end

-- copper, or nil for anything that is not vendor gear
function grug_gear.get_price(itemname)
	return buy_price[itemname]
end

function grug_gear.get_sell_price(itemname)
	return sell_price[itemname]
end

--
-- Generation.
--

grug_gear.catalog = {}

local tool_count, craftitem_count = 0, 0

for bracket, br in ipairs(grug_gear.BRACKETS) do
	local cat = {fixed = {}, extras = {}, all = {}}
	grug_gear.catalog[bracket] = cat

	local tint = "^[multiply:" .. BRACKET_TINT[bracket]
	local base_damage = dmg1h(br.ilvl)

	for _, w in ipairs(WEAPONS) do
		local itemname = "grug_gear:" .. w.key .. "_b" .. bracket
		local damage = math.max(1, math.floor(base_damage * w.factor + 0.5))
		-- Every weapon family is weapon-slot eligible (weapon-slot design B3).
		-- No class gate: weapon families are class FLAVOR, not a power ladder
		-- (§8.2), so a Mage may equip a greataxe and simply gains nothing from
		-- it; the only gate on the slot is WP5's grug_req_level. The slot
		-- itself is family-agnostic, which is how the future bow family joins
		-- without a second slot.
		local groups = {grug_gear = 1, grug_equip_weapon = 1}
		groups[w.group] = 1
		core.register_tool(itemname, {
			description = describe(bracket, w.noun, br.ilvl,
				weapon_stats(damage, w.fpi, w.hands)),
			inventory_image = "grug_gear_item_" .. w.key .. ".png" .. tint,
			groups = groups,
			stack_max = 1,
			tool_capabilities = {
				full_punch_interval = w.fpi,
				damage_groups = {fleshy = damage},
				max_drop_level = 0,
				groupcaps = {},
			},
			_grug_ilvl = br.ilvl,
			_grug_bracket = bracket,
			_grug_quality = 1,
			_grug_hands = w.hands,
			_grug_sell_price = buyback(br.price.weapon),
		})
		buy_price[itemname] = br.price.weapon
		sell_price[itemname] = buyback(br.price.weapon)
		table.insert(w.fixed and cat.fixed or cat.extras, itemname)
		tool_count = tool_count + 1
	end

	for _, line in ipairs(ARMOR_LINES) do
		if line.register then
			local total = line.base + line.per_ilvl * br.ilvl
			for _, slot in ipairs(ARMOR_SLOTS) do
				local itemname = "grug_gear:" .. slot.key .. "_" .. line.key ..
					"_b" .. bracket
				-- max(1) is a deliberate deviation from the raw split: at the
				-- low cloth brackets the 16% foot share rounds to 0, and a
				-- 0-armor boot is a bug, not a design statement.
				local armor = math.max(1, math.floor(total * slot.share + 0.5))
				local price = br.price.other
				if slot.key == "chest" then
					price = br.price.chest
				end
				core.register_craftitem(itemname, {
					description = describe(bracket, line.nouns[slot.key],
						br.ilvl, armor_stats(armor)),
					inventory_image = "grug_gear_item_" .. slot.key .. "_" ..
						line.key .. ".png" .. tint,
					groups = {
						["grug_equip_" .. slot.key] = 1,
						grug_armor_class = line.rank,
						grug_gear = 1,
					},
					stack_max = 1,
					_grug_armor = armor,
					_grug_ilvl = br.ilvl,
					_grug_bracket = bracket,
					_grug_quality = 1,
					_grug_sell_price = buyback(price),
				})
				buy_price[itemname] = price
				sell_price[itemname] = buyback(price)
				table.insert(cat.fixed, itemname)
				craftitem_count = craftitem_count + 1
			end
		end
	end

	-- `all` = the full bracket (12 items), the pool the Uncommon roll of
	-- §3.8 draws from; fixed first so the order stays stable for the UI.
	for _, itemname in ipairs(cat.fixed) do
		table.insert(cat.all, itemname)
	end
	for _, itemname in ipairs(cat.extras) do
		table.insert(cat.all, itemname)
	end
end

core.log("action", "[grug_gear] " .. NUM_BRACKETS .. " bracket catalogs: " ..
	tool_count .. " weapons + " .. craftitem_count .. " armor pieces")

--
-- The vendored `default` swords and axes are weapon-slot eligible too
-- (weapon-slot design B3, decided 2026-08-08).
--
-- WHY, since these are not our items: with the no-fallback rule of B1 the
-- weapon slot is the ONLY source of melee damage, and a fresh character owns
-- exactly one weapon — the `default:sword_stone` of the starter kit
-- (grug_factions). Without this list that character would have no melee
-- damage at all until their first vendor visit.
--
-- PICKAXES AND SHOVELS ARE DELIBERATELY ABSENT: mining tools stay mining
-- tools, and punching a mob with a pick keeps working through the ordinary
-- wielded-item path either way.
--
-- TEMPORARY BY CONSTRUCTION: WP28 deletes the mese and diamond tool tiers and
-- WP29 folds the rest into the material ladder, so this list only ever
-- shrinks — hence a loop over names instead of hand-copied override blocks.
--
-- `core.override_item` REPLACES a named field wholesale, it does not merge
-- (AGENTS.md, learned in WP25): handing it `groups = {grug_equip_weapon = 1}`
-- would drop `sword`/`axe`/`flammable` and break every recipe and burn time
-- that reads them. The current table is therefore read back off the
-- registration and copied — which also means this survives WP29's re-tiering
-- of those groups without anyone remembering to update a hand-copied literal.
--
-- ALL TWELVE ARE ONE-HANDED, the vendored axes included (B4, decided here).
-- The tempting reading is "an axe is two-handed", but a `default:` axe is a
-- hatchet, not our Greataxe: it hits for 4 fleshy at a 1.0 s interval where
-- the sword of the same tier hits for 6 at 0.8 s (default/tools.lua:265-278
-- vs :359-372), i.e. it is strictly WORSE in combat and could not pay for the
-- offhand it would block. It is also the woodcutting tool every character
-- carries permanently, so a 2H axe would take the torch away from anyone who
-- owns one — an arbitrary tax, not the deliberate trade combat_stats.md §7
-- asks for. The two-handed statement belongs to the family that is actually
-- paid for by ×1.5 damage: grug_gear's Greataxe. The field is still written
-- explicitly rather than left to the "no field = one-handed" default, so the
-- decision is visible at the site it applies to.
local VENDORED_WEAPONS = {
	"default:sword_wood", "default:sword_stone", "default:sword_bronze",
	"default:sword_steel", "default:sword_mese", "default:sword_diamond",
	"default:axe_wood", "default:axe_stone", "default:axe_bronze",
	"default:axe_steel", "default:axe_mese", "default:axe_diamond",
}

for _, itemname in ipairs(VENDORED_WEAPONS) do
	local def = core.registered_items[itemname]
	if not def then
		-- Not fatal: the list shrinks with WP28/WP29, and a stale entry must
		-- say so rather than crash the game.
		core.log("warning", "[grug_gear] cannot make " .. itemname ..
			" weapon-slot eligible: no such item")
	else
		local groups = table.copy(def.groups or {})
		groups.grug_equip_weapon = 1
		core.override_item(itemname, {groups = groups, _grug_hands = 1})
	end
end
