name = grug_skills
title = Grudgelands Skills Catalogue
description = Recoverable character ability and mount representations.
depends = grug_core, grug_factions, grug_classes, grug_abilities, grug_mounts, grug_inventory, sfinv
optional_depends = creative
