fixed_map_seed = 40200517
num_emerge_threads = 1
liquid_update = 86400
server_announce = false
enable_ipv6 = false
bind_address = 127.0.0.1
port = 32004
secure.trusted_mods = grug_wp40_t5_probe
grug_wp40_t5_probe.arm = B
grug_wp40_t5_probe.order = O2
