-- Disposable Round 30 P4 probe (never shipped): after every mod has loaded,
-- writes the registered profession recipes, their ingredient tiers and the
-- group ratings their group tokens need to <world>/r30_p4_recipe_corpus.lua,
-- the input of tools/r30_p4/portable_test.lua (section C). Run it through
-- tools/r30_p4/dump_corpus.sh.
local P = "[r30p4_probe] "
local function log(text) core.log("action", P .. text) end

local function literal(value, indent)
	local kind = type(value)
	if kind == "string" then return ("%q"):format(value) end
	if kind == "number" or kind == "boolean" then return tostring(value) end
	if kind ~= "table" then error("cannot write " .. kind) end
	local keys = {}
	for key in pairs(value) do keys[#keys + 1] = key end
	table.sort(keys, function(a, b)
		if type(a) == type(b) then return a < b end
		return type(a) == "number"
	end)
	local inner = indent .. "\t"
	local parts = {}
	for _, key in ipairs(keys) do
		local name = type(key) == "number" and ("[" .. key .. "]") or
			(key:match("^[%a_][%w_]*$") and key or ("[" .. ("%q"):format(key) .. "]"))
		parts[#parts + 1] = inner .. name .. " = " .. literal(value[key], inner)
	end
	if #parts == 0 then return "{}" end
	return "{\n" .. table.concat(parts, ",\n") .. ",\n" .. indent .. "}"
end

local FIELDS = {"profession", "tier", "station", "inputs", "output_name", "hint",
	"time", "in_place", "material", "operation", "family", "shapeless",
	"mastery_required", "existing_engine_recipe", "progress"}

local function dump()
	local recipes, items, groups = {}, {}, {}
	for index, recipe in ipairs(grug_jobs.recipes) do
		local row = {}
		for _, field in ipairs(FIELDS) do row[field] = recipe[field] end
		recipes[index] = row
		for _, token in ipairs(recipe.flat_inputs) do
			local wanted = token:match("^group:(.+)$")
			if wanted then
				for group in wanted:gmatch("[^,]+") do groups[group] = true end
			else
				items[token] = true
			end
		end
		items[recipe.output_name] = true
	end
	local tiers, ratings = {}, {}
	for name in pairs(core.registered_items) do
		local tier = grug_jobs.ingredient_tier(name)
		if tier then tiers[name] = tier end
		local own
		for group in pairs(groups) do
			local rating = core.get_item_group(name, group)
			if rating > 0 then
				own = own or {}
				own[group] = rating
			end
		end
		if own then ratings[name] = own end
	end
	-- Group tokens may be ingredients with a tier too ("group:wood").
	for group in pairs(groups) do
		local tier = grug_jobs.ingredient_tier("group:" .. group)
		if tier then tiers["group:" .. group] = tier end
	end
	local corpus = {recipes = recipes, tiers = tiers, groups = ratings}
	local path = core.get_worldpath() .. "/r30_p4_recipe_corpus.lua"
	local file = assert(io.open(path, "w"))
	file:write("-- Generated by tools/r30_p4/dump_corpus.sh (grug_probe_r30_p4).\n")
	file:write("return " .. literal(corpus, "") .. "\n")
	file:close()
	local stations = {}
	for _, recipe in ipairs(recipes) do
		stations[recipe.station] = (stations[recipe.station] or 0) + 1
	end
	local parts = {}
	for station, count in pairs(stations) do parts[#parts + 1] = station .. "=" .. count end
	table.sort(parts)
	log(("RESULT PASS recipes=%d (%s) group-rated items=%d"):format(#recipes,
		table.concat(parts, " "), (function()
			local n = 0
			for _ in pairs(ratings) do n = n + 1 end
			return n
		end)()))
	core.request_shutdown("r30 p4 probe done", false, 0)
end

-- grug_jobs finalizes its recipe authority on the first server step.
core.register_on_mods_loaded(function()
	core.after(1, dump)
end)
