-- Server-driven crosshair feedback (classes.md §2b "Crosshair feedback").
--
-- The game ships its own crosshair.png and a byte-identical
-- object_crosshair.png (textures/, generated by
-- tools/pt_fixes/lane_b/gen_crosshair_textures.py), so the engine's native
-- "pointing at an object" switch is invisible: skill items keep a four-node
-- native range for hand digging, which would otherwise mark only targets
-- within 4 m. All target feedback comes from this module instead:
--
-- * a state overlay, the crosshair image itself tinted by `^[multiply`, drawn
--   over the engine crosshair: hostile (red) and friendly (green) when the
--   selected skill's own aim authority (`grug_abilities.aimed_target`, the
--   ray and target rule the real cast uses, without its Target Frame memory
--   or diagnostics) finds a valid target in the skill's effective range;
--   otherwise interact (light blue) when contextual input would interact
--   with the first thing within hand reach (`input.aims_at_interactive`);
-- * one progress ring, one frame per sixteenth, shared by two owners: the
--   bow draw (scout.lua; warm white, a gold frame when full) and eating
--   (contextual input's food hold; the same frames tinted green, no full
--   frame). Each owner hides it on every one of its end paths.
--
-- Everything is refreshed from the existing 0.05 s pass (init.lua) and sends
-- a HUD packet only when the drawn texture changes. The weapon-ready ring
-- (init.lua) sits between the two: state overlay z 1, ready ring z 2, draw
-- ring z 3.
--
-- Integer scale. The engine draws the crosshair at floor(hud_scaling x display
-- density) (src/client/hud.cpp drawCrosshair) but a Lua image element at the
-- unrounded factor (hud.cpp HUD_ELEM_IMAGE). The client reports that factor as
-- `real_hud_scaling`, so when it is fractional the elements here are scaled
-- by floor(f) / f and land on the crosshair's own pixels. The factor is read
-- only when an element becomes visible, never per pass.
return function(api)
	local C = {}
	local STATE_TEXTURE = {
		hostile = "crosshair.png^[multiply:#ff3b3b",
		friendly = "crosshair.png^[multiply:#4be060",
		interact = "crosshair.png^[multiply:#7fd4ff",
	}
	local RING_FRAMES = 16
	local RING_FULL = "grug_abilities_draw_ring_full.png"
	-- Per-owner frame tint; only the bow has a full frame.
	local RING_TINT = {bow = "", food = "^[multiply:#7de36a"}
	C.Z_STATE, C.Z_READY, C.Z_RING = 1, 2, 3
	-- player name -> {state = hud rec, ring = hud rec, ring_owner = owner?}
	local huds = {}

	local function ring_texture(frame, owner)
		if frame == nil then return "" end
		if frame == "full" then return RING_FULL end
		return ("grug_abilities_draw_ring_%02d.png"):format(frame) .. RING_TINT[owner]
	end

	-- floor(f) / f for a fractional client HUD factor f, else 1. The small
	-- margin keeps the engine's float-to-int size conversion from rounding a
	-- 21 px sprite down to 20.
	local function integer_scale(player)
		local info = core.get_player_window_information(player:get_player_name())
		local factor = info and tonumber(info.real_hud_scaling)
		if not factor or factor <= 0 then return 1 end
		local whole = math.max(1, math.floor(factor))
		if math.abs(whole - factor) < 1e-6 then return 1 end
		return whole / factor * 1.001
	end

	-- One element: text changes only on a real change; the scale follows the
	-- client factor whenever the element becomes visible.
	local function show(player, rec, text)
		if rec.text == text then return end
		rec.text = text
		if text ~= "" then
			local scale = integer_scale(player)
			if scale ~= rec.scale then
				rec.scale = scale
				player:hud_change(rec.id, "scale", {x = scale, y = scale})
			end
		end
		player:hud_change(rec.id, "text", text)
	end

	local function add(player, z_index)
		return {text = "", scale = 1, id = player:hud_add(
			grug_core.hud_layout.image_element("reticle", {
				text = "", z_index = z_index, scale = {x = 1, y = 1}}))}
	end

	function C.join(player)
		huds[player:get_player_name()] = {
			state = add(player, C.Z_STATE),
			ring = add(player, C.Z_RING),
		}
	end

	function C.leave(player)
		huds[player:get_player_name()] = nil
	end

	C.skipped_skill_rays = 0 -- probe counter: skill rays proven unnecessary

	-- The state this player's crosshair should show now: "hostile",
	-- "friendly", "interact" or nil. A skill state takes precedence over the
	-- neutral interact state; self-target skills have no skill state.
	--
	-- One eye position feeds both rays. The hand-reach ray runs first: when
	-- its first hit is a walkable node, no object lies in front of that node,
	-- so the skill's combat ray (which stops only at walkable nodes and
	-- objects) would end there without a target and is skipped. Every other
	-- first hit (object, non-walkable node such as a sign or grass, nothing)
	-- still takes the skill ray.
	function C.state(player)
		if player:get_hp() <= 0 then return nil end
		local eye = grug_core.combat_eye_pos(player)
		if not eye then return nil end
		local input = grug_abilities.input
		local interact, walled = false, false
		if input then
			interact, walled = input.aims_at_interactive(player, eye)
		end
		local def = api.selected(player)
		if def and (def.target_kind == "hostile" or def.target_kind == "friendly")
				and grug_abilities.is_unlocked(player, def.id) then
			if walled then
				C.skipped_skill_rays = C.skipped_skill_rays + 1
			elseif grug_abilities.aimed_target(player, def, eye) then
				return def.target_kind
			end
		end
		return interact and "interact" or nil
	end

	-- The 0.05 s pass.
	function C.update(player)
		local rec = huds[player:get_player_name()]
		if not rec then return end
		local state = C.state(player)
		show(player, rec.state, state and STATE_TEXTURE[state] or "")
	end

	-- Progress ring for `owner` ("bow" or "food"): `fraction` in [0, 1]
	-- shows it, nil hides it. The single element belongs to one owner at a
	-- time: a free ring is claimed by the first show, a hide by any other
	-- owner is a no-op, and a show by another owner is refused (false) until
	-- the current owner hides it. Owners that keep calling while active (the
	-- bow draw loop, the eating step) therefore take the ring over on their
	-- next call once it is free, and neither can clear the other's frames.
	function C.set_ring(player, fraction, owner)
		local rec = huds[player:get_player_name()]
		if not rec or not RING_TINT[owner] then return false end
		if rec.ring_owner and rec.ring_owner ~= owner then return false end
		local frame
		if fraction then
			if fraction >= 1 and owner == "bow" then
				frame = "full"
			else
				frame = math.max(0, math.min(RING_FRAMES - 1,
					math.floor(fraction * RING_FRAMES)))
			end
			rec.ring_owner = owner
		else
			rec.ring_owner = nil
		end
		show(player, rec.ring, ring_texture(frame, owner))
		return true
	end

	-- Read-only view for the headless probe.
	function C.debug_view(player)
		local rec = huds[player:get_player_name()]
		if not rec then return nil end
		return {state = rec.state.text, ring = rec.ring.text,
			ring_owner = rec.ring_owner,
			state_id = rec.state.id, ring_id = rec.ring.id}
	end

	C.STATE_TEXTURE = STATE_TEXTURE
	core.register_on_joinplayer(C.join)
	core.register_on_leaveplayer(C.leave)
	return C
end
