wob_core = {}

-- World layout (docs/design/world.md §1): Alliance territory in the south
-- (z < -64), Horde in the north (z > 64), neutral borderland in between.
-- Difficulty grows with |z| (distance to the border).
wob_core.BORDER_Z = 0
wob_core.NEUTRAL_HALF_WIDTH = 64 -- neutral borderland: |z| <= 64
wob_core.WORLD_HALF_WIDTH_X = 2000 -- soft east-west border (mountain wall)
wob_core.HOUSING_Z = 2400 -- housing frontier: |z| > 2400

-- Race region bands along x within each territory (docs/design/world.md §7).
-- Bands overlap by 200 nodes; in the overlap the biome noise decides, which
-- gives an organic transition instead of a hard line.
wob_core.REGION_WEST_MAX = -500 -- west band: x <= -500
wob_core.REGION_CENTER_MIN = -700 -- center band: -700 <= x <= 700
wob_core.REGION_CENTER_MAX = 700
wob_core.REGION_EAST_MIN = 500 -- east band: x >= 500

-- Spawn camps (placeholder capitals until WP13 ships real structures):
-- a flat platform generated by wob_mapgen at z = ±200. The platform HEIGHT
-- is terrain-adaptive: decided once per world from the mapgen heightmap
-- around the camp (wob_mapgen/structures.lua), persisted in mod storage —
-- a fixed y buried the camp inside hills (players spawned trapped in a pit).
wob_core.CAMP_HALF = 12 -- platform is (2*12+1)^2 nodes
wob_core.CAMP_PLATFORM_Y = 8 -- fallback/minimum platform y (above water)
wob_core.CAMP_CLEAR_HEIGHT = 64 -- air cleared this high above the platform
wob_core.CAMP_PROTECT_RADIUS = 20 -- square radius of the protected zone

-- NB `spawn` is the x/z ANCHOR of the camp; its y is only the fallback
-- until the terrain-adaptive platform height is decided — always go
-- through wob_core.get_spawn_pos() for actual teleports.
wob_core.factions = {
	alliance = {
		id = "alliance",
		name = "Alliance",
		color = "#3f6fce",
		spawn = vector.new(0, wob_core.CAMP_PLATFORM_Y + 1, -200),
	},
	horde = {
		id = "horde",
		name = "Horde",
		color = "#c41e3a",
		spawn = vector.new(0, wob_core.CAMP_PLATFORM_Y + 1, 200),
	},
}

--
-- Terrain-adaptive camp platform height. Decided exactly once per world
-- (first mapchunk near the camp measures the surrounding heightmap, see
-- wob_mapgen/structures.lua) and persisted, so the platform can never
-- shift once built.
--

local storage = core.get_mod_storage()

function wob_core.get_camp_platform_y(faction_id)
	local y = storage:get_int("camp_platform_y:" .. faction_id)
	if y == 0 then
		return nil -- not decided yet (real values are always >= 4)
	end
	return y
end

function wob_core.set_camp_platform_y(faction_id, y)
	if not wob_core.get_camp_platform_y(faction_id) then
		storage:set_int("camp_platform_y:" .. faction_id, y)
	end
end

-- Actual spawn position on the camp platform (top layer + 1).
function wob_core.get_spawn_pos(faction_id)
	local anchor = wob_core.factions[faction_id].spawn
	local y = wob_core.get_camp_platform_y(faction_id)
		or wob_core.CAMP_PLATFORM_Y
	return vector.new(anchor.x, y + 1, anchor.z)
end

wob_core.faction_ids = {"alliance", "horde"}

function wob_core.opposing_faction(faction_id)
	return faction_id == "alliance" and "horde" or "alliance"
end

-- Difficulty rings (docs/design/world.md §1, combat_stats.md §3): |z| anchors
-- with mob level anchors, piecewise linear in between. Each entry starts the
-- zone that runs until the next anchor; beyond the last anchor lies the
-- housing frontier (no hostile mobs).
wob_core.rings = {
	{z = 0, level = 1, zone = "borderland"},
	{z = 64, level = 5, zone = "starter"},
	{z = 400, level = 10, zone = "midlands"},
	{z = 1000, level = 30, zone = "heartland"},
	{z = 1800, level = 50, zone = "deep_heartland"},
	{z = 2400, level = 60, zone = "housing"},
}

-- "horde", "alliance" or "neutral" (borderland).
function wob_core.territory_at(pos)
	if pos.z > wob_core.NEUTRAL_HALF_WIDTH then
		return "horde"
	elseif pos.z < -wob_core.NEUTRAL_HALF_WIDTH then
		return "alliance"
	end
	return "neutral"
end

-- Zone name at pos: "borderland", "starter", "midlands", "heartland",
-- "deep_heartland" or "housing".
function wob_core.zone_at(pos)
	local d = math.abs(pos.z)
	local rings = wob_core.rings
	for i = #rings, 1, -1 do
		if d >= rings[i].z then
			return rings[i].zone
		end
	end
	return rings[1].zone
end

-- Mob level for a hostile spawned at pos (1..60), or nil in the housing
-- frontier (no hostiles there). Guards use this +5 (WP6).
function wob_core.mob_level_at(pos)
	local d = math.abs(pos.z)
	local rings = wob_core.rings
	if d >= rings[#rings].z then
		return nil -- housing frontier
	end
	for i = #rings - 1, 1, -1 do
		local a, b = rings[i], rings[i + 1]
		if d >= a.z then
			local t = (d - a.z) / (b.z - a.z)
			return math.round(a.level + t * (b.level - a.level))
		end
	end
	return rings[1].level
end

-- 0 (border) .. 1 (deep heartland), defined as (mob_level-1)/59 and clamped;
-- keeps returning 1 beyond the last ring.
function wob_core.difficulty_at(pos)
	local level = wob_core.mob_level_at(pos)
	if not level then
		return 1
	end
	return math.min(1, math.max(0, (level - 1) / 59))
end

-- Resolves a player name to a faction id ("horde"/"alliance") or nil.
-- Overridden by wob_factions at load time; the stub keeps wob_core free of
-- dependencies on player mods.
function wob_core.get_player_faction(name)
	return nil
end

-- Finds a safe surface position near pos (for spawns/teleports); the camp
-- platform makes this a no-op at faction spawns, elsewhere it is a fallback.
function wob_core.find_surface(pos)
	for y = 120, -16, -1 do
		local p = vector.new(pos.x, y, pos.z)
		local node = core.get_node_or_nil(p)
		local below = core.get_node_or_nil(vector.offset(p, 0, -1, 0))
		if node and below and node.name == "air" and
				below.name ~= "air" and below.name ~= "ignore" and
				core.get_item_group(below.name, "liquid") == 0 then
			return p
		end
	end
	return pos
end

local modpath = core.get_modpath(core.get_current_modname())
dofile(modpath .. "/protection.lua")
dofile(modpath .. "/combat.lua")
