wob_core = {}

-- World layout (docs/design/world.md §1): Alliance territory in the south
-- (z < -64), Horde in the north (z > 64), neutral borderland in between.
-- Difficulty grows with |z| (distance to the border).
wob_core.BORDER_Z = 0
wob_core.NEUTRAL_HALF_WIDTH = 64 -- neutral borderland: |z| <= 64
wob_core.WORLD_HALF_WIDTH_X = 2000 -- soft east-west border (mountain wall)
wob_core.HOUSING_Z = 2400 -- housing frontier: |z| > 2400

-- Race region bands along x within each territory (docs/design/world.md §7).
-- Bands overlap by 200 nodes; in the overlap the biome noise decides, which
-- gives an organic transition instead of a hard line.
wob_core.REGION_WEST_MAX = -500 -- west band: x <= -500
wob_core.REGION_CENTER_MIN = -700 -- center band: -700 <= x <= 700
wob_core.REGION_CENTER_MAX = 700
wob_core.REGION_EAST_MIN = 500 -- east band: x >= 500

-- Spawn camps (placeholder capitals until WP13 ships real structures):
-- a flat platform generated by wob_mapgen at z = ±200.
wob_core.CAMP_HALF = 12 -- platform is (2*12+1)^2 nodes
wob_core.CAMP_PLATFORM_Y = 8 -- y of the top platform layer
wob_core.CAMP_CLEAR_TOP = 72 -- air is cleared above the platform up to here
wob_core.CAMP_PROTECT_RADIUS = 20 -- square radius of the protected zone

wob_core.factions = {
	alliance = {
		id = "alliance",
		name = "Alliance",
		color = "#3f6fce",
		spawn = vector.new(0, wob_core.CAMP_PLATFORM_Y + 1, -200),
	},
	horde = {
		id = "horde",
		name = "Horde",
		color = "#c41e3a",
		spawn = vector.new(0, wob_core.CAMP_PLATFORM_Y + 1, 200),
	},
}

wob_core.faction_ids = {"alliance", "horde"}

function wob_core.opposing_faction(faction_id)
	return faction_id == "alliance" and "horde" or "alliance"
end

-- Difficulty rings (docs/design/world.md §1, combat_stats.md §3): |z| anchors
-- with mob level anchors, piecewise linear in between. Each entry starts the
-- zone that runs until the next anchor; beyond the last anchor lies the
-- housing frontier (no hostile mobs).
wob_core.rings = {
	{z = 0, level = 1, zone = "borderland"},
	{z = 64, level = 5, zone = "starter"},
	{z = 400, level = 10, zone = "midlands"},
	{z = 1000, level = 30, zone = "heartland"},
	{z = 1800, level = 50, zone = "deep_heartland"},
	{z = 2400, level = 60, zone = "housing"},
}

-- "horde", "alliance" or "neutral" (borderland).
function wob_core.territory_at(pos)
	if pos.z > wob_core.NEUTRAL_HALF_WIDTH then
		return "horde"
	elseif pos.z < -wob_core.NEUTRAL_HALF_WIDTH then
		return "alliance"
	end
	return "neutral"
end

-- Zone name at pos: "borderland", "starter", "midlands", "heartland",
-- "deep_heartland" or "housing".
function wob_core.zone_at(pos)
	local d = math.abs(pos.z)
	local rings = wob_core.rings
	for i = #rings, 1, -1 do
		if d >= rings[i].z then
			return rings[i].zone
		end
	end
	return rings[1].zone
end

-- Mob level for a hostile spawned at pos (1..60), or nil in the housing
-- frontier (no hostiles there). Guards use this +5 (WP6).
function wob_core.mob_level_at(pos)
	local d = math.abs(pos.z)
	local rings = wob_core.rings
	if d >= rings[#rings].z then
		return nil -- housing frontier
	end
	for i = #rings - 1, 1, -1 do
		local a, b = rings[i], rings[i + 1]
		if d >= a.z then
			local t = (d - a.z) / (b.z - a.z)
			return math.round(a.level + t * (b.level - a.level))
		end
	end
	return rings[1].level
end

-- 0 (border) .. 1 (deep heartland), defined as (mob_level-1)/59 and clamped;
-- keeps returning 1 beyond the last ring.
function wob_core.difficulty_at(pos)
	local level = wob_core.mob_level_at(pos)
	if not level then
		return 1
	end
	return math.min(1, math.max(0, (level - 1) / 59))
end

-- Resolves a player name to a faction id ("horde"/"alliance") or nil.
-- Overridden by wob_factions at load time; the stub keeps wob_core free of
-- dependencies on player mods.
function wob_core.get_player_faction(name)
	return nil
end

-- Finds a safe surface position near pos (for spawns/teleports); the camp
-- platform makes this a no-op at faction spawns, elsewhere it is a fallback.
function wob_core.find_surface(pos)
	for y = 80, -16, -1 do
		local p = vector.new(pos.x, y, pos.z)
		local node = core.get_node_or_nil(p)
		local below = core.get_node_or_nil(vector.offset(p, 0, -1, 0))
		if node and below and node.name == "air" and
				below.name ~= "air" and below.name ~= "ignore" and
				core.get_item_group(below.name, "liquid") == 0 then
			return p
		end
	end
	return pos
end

dofile(core.get_modpath(core.get_current_modname()) .. "/protection.lua")
