-- Round 20 NPC bindings. Coordinates remain owned by authored actor sockets.
local Q = grug_quests
local actors = {
	{"r20_anchor_014_host", "r20_anchor_014", "quest_host", "Edda Tarnmantle"},
	{"r20_anchor_016_host", "r20_anchor_016", "quest_host", "Merren Oakstamp"},
	{"r20_anchor_018_host", "r20_anchor_018", "quest_host", "Ilwen Petalmeasure"},
	{"r20_anchor_020_host", "r20_anchor_020", "quest_host", "Sovel Namekeeper"},
	{"r20_anchor_022_host", "r20_anchor_022", "quest_host", "Brakka Jarward"},
	{"r20_anchor_024_host", "r20_anchor_024", "quest_host", "Taleko Drycord"},
	{"r20_anchor_026_host", "r20_anchor_026", "quest_host", "Hedra Rimebell"},
	{"r20_anchor_027_host", "r20_anchor_027", "quest_host", "Borin Splitbolt"},
	{"r20_anchor_028_host", "r20_anchor_028", "quest_host", "Alna Archsight"},
	{"r20_anchor_030_host", "r20_anchor_030", "quest_host", "Jessa Axlewright"},
	{"r20_anchor_031_host", "r20_anchor_031", "quest_host", "Toren Waterbarrel"},
	{"r20_anchor_032_host", "r20_anchor_032", "quest_host", "Nella Hedgeward"},
	{"r20_anchor_034_host", "r20_anchor_034", "quest_host", "Orya Petalward"},
	{"r20_anchor_035_host", "r20_anchor_035", "quest_host", "Lethen Moonledger"},
	{"r20_anchor_036_host", "r20_anchor_036", "quest_host", "Faeris Rootbinder"},
	{"r20_anchor_038_host", "r20_anchor_038", "quest_host", "Mereth Rubbinghand"},
	{"r20_anchor_039_host", "r20_anchor_039", "quest_host", "Vaska Ashlistener"},
	{"r20_anchor_040_host", "r20_anchor_040", "quest_host", "Orrel Hollowstep"},
	{"r20_anchor_042_host", "r20_anchor_042", "quest_host", "Morga Cutgrass"},
	{"r20_anchor_043_host", "r20_anchor_043", "quest_host", "Drek Rampbinder"},
	{"r20_anchor_044_host", "r20_anchor_044", "quest_host", "Yarra Standardmender"},
	{"r20_anchor_046_host", "r20_anchor_046", "quest_host", "Enashi Reedvoice"},
	{"r20_anchor_047_host", "r20_anchor_047", "quest_host", "Tokai Knotreader"},
	{"r20_anchor_048_host", "r20_anchor_048", "quest_host", "Rumela Stormstep"},
	{"r20_anchor_061_host", "r20_anchor_061", "quest_host", "Kelda Screesort"},
	{"r20_anchor_062_host", "r20_anchor_062", "quest_host", "Halen Chalkthumb"},
	{"r20_anchor_063_host", "r20_anchor_063", "quest_host", "Saevin Rootscribe"},
	{"r20_anchor_064_host", "r20_anchor_064", "quest_host", "Neris Fossilhand"},
	{"r20_anchor_065_host", "r20_anchor_065", "quest_host", "Gorren Redpick"},
	{"r20_anchor_066_host", "r20_anchor_066", "quest_host", "Zali Runoff"},
	{"r20_dwarf_start_cook", "hearthpine", "quest_cook", "Hilda Hearthspoon"},
	{"r20_dwarf_capital_cook", "dur_brannoc", "terrace_bakehouse/terrace_bakehouse_quest_cook", "Varda Copperpan"},
	{"r20_dwarf_capital_envoy", "dur_brannoc", "ancestor_hall_quest", "Dorrin Gateledger"},
	{"r20_human_start_cook", "dawnmere", "quest_cook", "Bess Honeycrust"},
	{"r20_human_capital_cook", "highcourt", "homes_bakehouse/homes_bakehouse_quest_cook", "Ansel Ovenward"},
	{"r20_human_capital_envoy", "highcourt", "chapel_quest", "Mariel Waybook"},
	{"r20_elf_start_cook", "silverleaf", "quest_cook", "Liora Dewpot"},
	{"r20_elf_capital_cook", "lethariel", "market_bakehouse/market_bakehouse_quest_cook", "Mirael Petalpot"},
	{"r20_elf_capital_envoy", "lethariel", "star_hall_quest", "Eriath Boughwarden"},
	{"r20_undead_start_cook", "stillgrave", "quest_cook", "Neral Saltkeeper"},
	{"r20_undead_capital_cook", "nhal_veyr", "homes_mourners_hall/homes_mourners_hall_quest_cook", "Velis Mourningbowl"},
	{"r20_undead_capital_envoy", "nhal_veyr", "vigil_hall_quest", "Ossa Quietregister"},
	{"r20_orc_start_cook", "sunscar", "quest_cook", "Ugra Brothstone"},
	{"r20_orc_capital_cook", "gor_drazhak", "warren_cook_court/warren_cook_court_quest_cook", "Gorla Longladle"},
	{"r20_orc_capital_envoy", "gor_drazhak", "skull_hall_quest", "Thorga Roadspeaker"},
	{"r20_troll_start_cook", "kapok", "quest_cook", "Zemi Sweetroot"},
	{"r20_troll_capital_cook", "kezamba", "shore_smokehouse/shore_smokehouse_quest_cook", "Teshani Smokereed"},
	{"r20_troll_capital_envoy", "kezamba", "shrine_quest", "Nalo Pathdrum"},
}
for _, row in ipairs(actors) do
	Q.register_npc(row[1], {settlement = row[2], socket = row[3], title = row[4]})
end
