grug_quests = {}
local path = core.get_modpath(core.get_current_modname())
dofile(path .. "/registry.lua")
dofile(path .. "/state.lua")
dofile(path .. "/labels.lua")
dofile(path .. "/npc.lua")
dofile(path .. "/npcs.lua")
dofile(path .. "/validate.lua")
dofile(path .. "/loader.lua")
dofile(path .. "/ui.lua")
dofile(path .. "/hud.lua")
core.register_on_mods_loaded(function()
	grug_quests.resolve_npc_factions()
	grug_quests.validate_quest_data()
	grug_quests.validate_registry()
end)
