-- Copper retort: A copper still feeds a blue receiver through a squared swan-neck pipe above a small burner.
-- Original proposal; generated by tools/r45_a2/generate.py.
-- Front: -Z. Tiles: +Y, -Y, +X, -X, +Z, -Z; node-coordinate UVs.
return {
 boxes = {
  {-0.4375, -0.5, -0.375, 0.4375, -0.375, 0.375},
  {-0.3125, -0.375, -0.125, -0.0625, -0.3125, 0.125},
  {-0.25, -0.3125, -0.0625, -0.125, -0.25, 0.0625},
  {-0.25, -0.25, -0.0625, -0.125, -0.1875, 0.0625},
  {-0.375, -0.375, -0.125, -0.3125, 0, 0.125},
  {-0.0625, -0.375, -0.125, 0, 0, 0.125},
  {-0.375, -0.0625, -0.1875, 0, 0.1875, 0.1875},
  {-0.3125, 0.1875, -0.125, -0.0625, 0.25, 0.125},
  {-0.25, 0.25, -0.0625, -0.125, 0.4375, 0.0625},
  {-0.125, 0.375, -0.0625, 0.3125, 0.4375, 0.0625},
  {0.25, 0.125, -0.0625, 0.3125, 0.375, 0.0625},
  {0.1875, -0.375, -0.125, 0.3125, -0.3125, 0.125},
  {0.125, -0.3125, -0.125, 0.375, 0, 0.125},
  {0.1875, 0, -0.0625, 0.3125, 0.0625, 0.0625},
  {0.1875, 0.0625, -0.0625, 0.3125, 0.125, 0.0625},
 },
 tiles = {
  "grug_r45_a2_brewing_stand_a_top.png",
  "grug_r45_a2_brewing_stand_a_bottom.png",
  "grug_r45_a2_brewing_stand_a_right.png",
  "grug_r45_a2_brewing_stand_a_left.png",
  "grug_r45_a2_brewing_stand_a_back.png",
  "grug_r45_a2_brewing_stand_a_front.png",
 },
}
