name = grug_professions
title = Grudgelands Primary Profession Catalogs
description = Weaponsmith, Armorsmith, Leatherworker and Tailor improvement catalogs.
depends = default, mobs, grug_core, grug_jobs, grug_inventory, grug_gear, grug_materials, grug_mobs, grug_gathering, grug_traders
optional_depends = grug_farming
