name = grug_professions
title = Grudgelands Primary Profession Catalogs
description = Blacksmith, Leatherworker and Tailor material and refinement catalogs.
depends = default, mobs, grug_core, grug_jobs, grug_inventory, grug_gear, grug_materials, grug_mobs, grug_gathering, grug_traders
