#!/usr/bin/env python3
"""Generates the 16x16 mob-material item icons of grug_mobs.

Grudgelands project, **CC0 1.0** - original pixel art, NOT derived from any
vendored or third-party asset. Fully deterministic (no randomness), so
re-running the script reproduces every PNG byte-for-byte.

Every icon is authored as a 16x16 ASCII map plus a per-icon palette, which
makes the art reviewable in the diff instead of only in a binary blob.

Usage:
    python3 tools/gen_mob_item_textures.py [outdir]

Default outdir: mods/ENTITIES/grug_mobs/textures
"""

import os
import sys

from PIL import Image

TRANSPARENT = (0, 0, 0, 0)


def rgba(hexstr):
    hexstr = hexstr.lstrip("#")
    return (int(hexstr[0:2], 16), int(hexstr[2:4], 16), int(hexstr[4:6], 16), 255)


def build(name, art, palette, outdir):
    rows = art.strip("\n").split("\n")
    assert len(rows) == 16, "%s: %d rows" % (name, len(rows))
    img = Image.new("RGBA", (16, 16), TRANSPARENT)
    px = img.load()
    for y, row in enumerate(rows):
        assert len(row) == 16, "%s: row %d has %d cols" % (name, y, len(row))
        for x, ch in enumerate(row):
            if ch != ".":
                assert ch in palette, "%s: unmapped char %r" % (name, ch)
                px[x, y] = rgba(palette[ch])
    path = os.path.join(outdir, name)
    img.save(path)
    return path


# ---------------------------------------------------------------- shared art

HIDE = """
................
....ooo...ooo...
...obbbo.obbbo..
..obbbbbobbbbbo.
..obbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..obbbbbbbbbbo..
..obbbbbbbbbo...
...obbbbbbbo....
...obbbbbbbo....
..obbbbbbbbbo...
..obbbo.obbbo...
...ooo...ooo....
................
"""

HIDE_STACK = """
................
................
..oooooooooooo..
.obbbbbbbbbbbbo.
.obhhbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..oooooooooooo..
..oooooooooooo..
.occcccccccccco.
.occcccccccccco.
.occhhcccccccco.
.occcccccccccco.
..oooooooooooo..
................
................
"""

SCALED = """
................
....ooo...ooo...
...obsbo.obsbo..
..obsbsbobsbsbo.
..obbsbsbsbsbbo.
.obsbsbsbsbsbso.
.obbsbsbsbsbsbo.
.obsbsbsbsbsbso.
..obbsbsbsbsbo..
..obsbsbsbsbo...
...obbsbsbbo....
...obsbsbsbo....
..obbsbsbsbbo...
..obsbo.obsbo...
...ooo...ooo....
................
"""

PELT = """
................
.....oooo.......
....obbbbo......
...obbhhbbo.....
..obbbbbbbbo....
..obbbbbbbbo....
.obbbhhbbbbbo...
.obbbbbbbbbbo...
.obbbbbbbbbbo...
..obbbbbbbbo....
..obbbhhbbbo....
...obbbbbbo.....
....obbbbo......
.....obbbo......
......ooo.......
................
"""

SCRAP = """
................
................
....oo..ooo.....
...obbooobbo....
..obbbbbbbbo....
..obbbbbbbbbo...
.obbbbbbbbbbo...
.obbbbbbbbbo....
.obbbbbbbbbbo...
..obbbbbbbbo....
..obbbobbbo.....
...obbo.obo.....
....oo...o......
................
................
................
"""

BOLT = """
................
................
..oooooooooooo..
.obbbbbbbbbbbbo.
.obhhbbbbbbbbbo.
.obbbbbbbbbbbbo.
.oaaaaaaaaaaaao.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.oaaaaaaaaaaaao.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..oooooooooooo..
................
................
................
"""

SKEIN = """
................
......oooo......
.....owwwwo.....
....owwwwwwo....
...owwhwwwwo....
...owwwwwwwwo...
..owwwwwwwwwo...
..owwwwwwwwwo...
..owwwwwwwwo....
...owwwwwwwo....
...owwwwwwo.....
....owwwwo......
.....oooo.......
.......ww.......
........w.......
................
"""

ORGAN = """
................
.......oo.......
......oggo......
.....oggggo.....
....oghhgggo....
...oghhggggo....
...oggggggggo...
..oggggggggggo..
..oggggggggggo..
..oggggggggggo..
...oggggggggo...
....oggggggo....
.....oggggo.....
......oggo......
.......oo.......
................
"""

TEARDROP = """
................
.......o........
......ogo.......
......ogo.......
.....oggo.......
.....ogggo......
....oghhggo.....
...oghhgggo.....
...ogggggggo....
..oggggggggo....
..oggggggggo....
..oggggggggo....
...oggggggo.....
....oggggo......
.....oooo.......
................
"""

FANG = """
................
.........oo.....
........owwo....
........owwo....
.......owwwo....
.......owwwo....
.......owwo.....
......owwwo.....
......owwo......
.....owwwo......
.....owwo.......
....owwo........
....owo.........
...owo..........
...oo...........
................
"""

TOOTH = """
................
......oooo......
.....owwwwo.....
.....owwwwo.....
.....owwwwo.....
.....owhwwo.....
.....owwwwo.....
......owwwo.....
......owwwo.....
......owwo......
.......owwo.....
.......owwo.....
........owo.....
........owo.....
.........o......
................
"""

HOOK_CLAW = """
................
....oo..........
...okko.........
...okkko........
....okkko.......
.....okkko......
......okkko.....
.......okkko....
.......okkkko...
......okkkkko...
.....okkkkkko...
....okkkkkkko...
...okkkkkkko....
...okkkkkko.....
....ooooooo.....
................
"""

FUR_CLAW = """
................
..........oo....
.........okko...
........okkko...
........okkko...
.......okkkko...
.......okkkko...
......okkkko....
......okkkko....
.....okkkko.....
....offffo......
...offffffo.....
...offffffo.....
....offffo......
.....oooo.......
................
"""

FEATHER = """
................
..........oo....
.........offo...
........offffo..
.......offffo...
......offqffo...
.....offqffo....
....offqffo.....
....offqfo......
...offqffo......
...ofqffo.......
..ofqfo.........
..oqfo..........
..oqo...........
..oo............
................
"""

GEODE = """
................
................
....oooooo......
...osssssso.....
..ossscsssso....
..osscccssso....
.ossccGccssso...
.osscGGGcssso...
.osscccGcssso...
..osscccssso....
..ossscsssso....
...osssssso.....
....oooooo......
................
................
................
"""

BLOB = """
................
................
.....oooo.......
....oggggo......
...oghhgggo.....
..oghhggggo.....
..ogggggggo.....
.oggggggggggo...
.oggggggggggo...
.oggggggggggo...
..oggggggggo....
...oggggggo.....
....oooooo......
................
................
................
"""

SCALE = """
................
.......oo.......
.....oosSoo.....
....osSSSSso....
...osSSSSSSso...
..osSSSSSSSSso..
..oSSSSSSSSSo...
..oSSSSSSSSSo...
...oSSSSSSSo....
....oSSSSSo.....
.....oSSSo......
......oSo.......
.......o........
..s.........s...
................
................
"""

TUFT = """
................
....h....h......
...hh...hh..h...
...hh..hhh.hh...
..hhh..hhh.hh...
..hhh.hhhhhhh...
..hhdhhhhhdhh...
..hhhhhhhhhhh...
...hhhhhhhhh....
...hhhdhhhhh....
....hhhhhhh.....
....hhhhhh......
.....hhhh.......
......hh........
................
................
"""

BONE = """
................
................
................
..oo........oo..
.owwo......owwo.
.owwwoooooowwwo.
.owwwwwwwwwwwwo.
.owwwoooooowwwo.
.owwo......owwo.
..oo........oo..
................
................
................
................
................
................
"""

ARROW_BUNDLE = """
................
..k....k....k...
..kk...kk...kk..
.kkkk.kkkk.kkkk.
..ss...ss...ss..
..ss...ss...ss..
..ss...ss...ss..
.tttttttttttttt.
.tttttttttttttt.
..ss...ss...ss..
..ss...ss...ss..
..ss...ss...ss..
..ff...ff...ff..
.f.f..f.f..f.f..
................
................
"""

ARROW_PROJECTILE = """
................
................
................
................
................
........k.......
.ff.....kk......
.fffsssskkkk....
.ff.....kk......
........k.......
................
................
................
................
................
................
"""

ROCK_PROJECTILE = """
................
................
................
.....oooo.......
....ohhhhoo.....
...ohhhhhssdo...
..ohhhhssssddo..
..ohhssssssddo..
..osssssdddddo..
...osssddddddo..
....odddddddo...
.....ooooooo....
................
................
................
................
"""


# ------------------------------------------------------------------- recipes
# (file name, art, palette)

ICONS = [
    ("grug_mobs_item_light_leather.png", HIDE,
     {"o": "#5a3f28", "b": "#b98a55", "h": "#d8ab74"}),
    ("grug_mobs_item_heavy_leather.png", HIDE_STACK,
     {"o": "#3d2a19", "b": "#8a5f38", "c": "#6f4c2c", "h": "#a97a4a"}),
    ("grug_mobs_item_scaled_hide.png", SCALED,
     {"o": "#20402f", "b": "#3f7a56", "s": "#59a071"}),
    ("grug_mobs_item_sleek_pelt.png", PELT,
     {"o": "#1b1b22", "b": "#3a3a46", "h": "#5c5c6e"}),
    ("grug_mobs_item_linen_scrap.png", SCRAP,
     {"o": "#7d7461", "b": "#cfc4a8"}),
    ("grug_mobs_item_linen_cloth.png", BOLT,
     {"o": "#8a8068", "b": "#ded3b6", "h": "#f2ead2", "a": "#bfb392"}),
    ("grug_mobs_item_heavy_cloth.png", BOLT,
     {"o": "#3f3a30", "b": "#8f8365", "h": "#a99b78", "a": "#6d6450"}),
    ("grug_mobs_item_spider_silk.png", SKEIN,
     {"o": "#9aa3ad", "w": "#eef2f6", "h": "#ffffff"}),
    ("grug_mobs_item_venom_gland.png", ORGAN,
     {"o": "#274a1e", "g": "#6aa83c", "h": "#9ed46a"}),
    ("grug_mobs_item_venom_sac.png", TEARDROP,
     {"o": "#3a1f4a", "g": "#7b3fa0", "h": "#b276d4"}),
    ("grug_mobs_item_fang.png", FANG,
     {"o": "#7a705c", "w": "#efe7cf"}),
    ("grug_mobs_item_croc_tooth.png", TOOTH,
     {"o": "#7a6d4a", "w": "#e8dcae", "h": "#fff6d2"}),
    ("grug_mobs_item_raptor_claw.png", HOOK_CLAW,
     {"o": "#120f12", "k": "#3c3230"}),
    ("grug_mobs_item_bear_claw.png", FUR_CLAW,
     {"o": "#2a201a", "k": "#e0d6bf", "f": "#7a5231"}),
    ("grug_mobs_item_feather.png", FEATHER,
     {"o": "#8c8f96", "f": "#e8ecf2", "q": "#c2c7cf"}),
    ("grug_mobs_item_sharp_feather.png", FEATHER,
     {"o": "#2b3138", "f": "#6e7a86", "q": "#aeb8c2"}),
    ("grug_mobs_item_stone_core.png", GEODE,
     {"o": "#2f2f33", "s": "#77787e", "c": "#4f5056", "G": "#ffd45e"}),
    ("grug_mobs_item_slime_gel.png", BLOB,
     {"o": "#2d4a1c", "g": "#7fb04a", "h": "#b6da84"}),
    ("grug_mobs_item_shiny_scale.png", SCALE,
     {"o": "#1d4a4f", "S": "#43b0b8", "s": "#7fdde3"}),
    ("grug_mobs_item_ape_hair.png", TUFT,
     {"h": "#3a2c22", "d": "#241a13"}),
    ("grug_mobs_item_bone.png", BONE,
     {"o": "#8d8672", "w": "#efe9d6"}),
    ("grug_mobs_item_arrow.png", ARROW_BUNDLE,
     {"k": "#b9c0c8", "s": "#8a6238", "t": "#6b4a2a", "f": "#d9d2c0"}),
    # Projectile sprite of grug_mobs:arrow_entity (not an inventory item).
    ("grug_mobs_arrow.png", ARROW_PROJECTILE,
     {"k": "#c9d1da", "s": "#8a6238", "f": "#e2dccb"}),
    # Projectile sprite of grug_mobs:rock_entity (golem, not an inventory
    # item): a lit-from-the-upper-left grey boulder.
    ("grug_mobs_rock.png", ROCK_PROJECTILE,
     {"o": "#2b2b30", "h": "#9a9aa2", "s": "#6e6e77", "d": "#4a4a52"}),
]


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else \
        os.path.join("mods", "ENTITIES", "grug_mobs", "textures")
    if not os.path.isdir(outdir):
        raise SystemExit("no such directory: " + outdir)
    for name, art, palette in ICONS:
        print(build(name, art, palette, outdir))
    print("%d icons written to %s" % (len(ICONS), outdir))


if __name__ == "__main__":
    main()
