#!/usr/bin/env python3
"""Generates the 16x16 mob-material item icons of grug_mobs (plus the few
node tiles of other mods that are authored the same way).

Grudgelands project, **CC0 1.0** - original pixel art, NOT derived from any
vendored or third-party asset. Fully deterministic (no randomness), so
re-running the script reproduces every PNG byte-for-byte.

Every icon is authored as a 16x16 ASCII map plus a per-icon palette, which
makes the art reviewable in the diff instead of only in a binary blob.

Usage:
    python3 tools/gen_mob_item_textures.py \\
        [outdir [nodes_outdir [gear_outdir [traders_outdir]]]]

Default outdir:         mods/ENTITIES/grug_mobs/textures    (ICONS)
Default nodes_outdir:   mods/ITEMS/grug_nodes/textures      (NODE_ICONS)
Default gear_outdir:    mods/ITEMS/grug_gear/textures       (GEAR_ICONS)
Default traders_outdir: mods/ENTITIES/grug_traders/textures (TRADER_ICONS)
"""

import os
import sys

from PIL import Image

TRANSPARENT = (0, 0, 0, 0)


def rgba(hexstr):
    hexstr = hexstr.lstrip("#")
    return (int(hexstr[0:2], 16), int(hexstr[2:4], 16), int(hexstr[4:6], 16), 255)


def build(name, art, palette, outdir):
    rows = art.strip("\n").split("\n")
    assert len(rows) == 16, "%s: %d rows" % (name, len(rows))
    img = Image.new("RGBA", (16, 16), TRANSPARENT)
    px = img.load()
    for y, row in enumerate(rows):
        assert len(row) == 16, "%s: row %d has %d cols" % (name, y, len(row))
        for x, ch in enumerate(row):
            if ch != ".":
                assert ch in palette, "%s: unmapped char %r" % (name, ch)
                px[x, y] = rgba(palette[ch])
    path = os.path.join(outdir, name)
    img.save(path)
    return path


# ---------------------------------------------------------------- shared art

HIDE = """
................
....ooo...ooo...
...obbbo.obbbo..
..obbbbbobbbbbo.
..obbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..obbbbbbbbbbo..
..obbbbbbbbbo...
...obbbbbbbo....
...obbbbbbbo....
..obbbbbbbbbo...
..obbbo.obbbo...
...ooo...ooo....
................
"""

HIDE_STACK = """
................
................
..oooooooooooo..
.obbbbbbbbbbbbo.
.obhhbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..oooooooooooo..
..oooooooooooo..
.occcccccccccco.
.occcccccccccco.
.occhhcccccccco.
.occcccccccccco.
..oooooooooooo..
................
................
"""

SCALED = """
................
....ooo...ooo...
...obsbo.obsbo..
..obsbsbobsbsbo.
..obbsbsbsbsbbo.
.obsbsbsbsbsbso.
.obbsbsbsbsbsbo.
.obsbsbsbsbsbso.
..obbsbsbsbsbo..
..obsbsbsbsbo...
...obbsbsbbo....
...obsbsbsbo....
..obbsbsbsbbo...
..obsbo.obsbo...
...ooo...ooo....
................
"""

PELT = """
................
.....oooo.......
....obbbbo......
...obbhhbbo.....
..obbbbbbbbo....
..obbbbbbbbo....
.obbbhhbbbbbo...
.obbbbbbbbbbo...
.obbbbbbbbbbo...
..obbbbbbbbo....
..obbbhhbbbo....
...obbbbbbo.....
....obbbbo......
.....obbbo......
......ooo.......
................
"""

SCRAP = """
................
................
....oo..ooo.....
...obbooobbo....
..obbbbbbbbo....
..obbbbbbbbbo...
.obbbbbbbbbbo...
.obbbbbbbbbo....
.obbbbbbbbbbo...
..obbbbbbbbo....
..obbbobbbo.....
...obbo.obo.....
....oo...o......
................
................
................
"""

BOLT = """
................
................
..oooooooooooo..
.obbbbbbbbbbbbo.
.obhhbbbbbbbbbo.
.obbbbbbbbbbbbo.
.oaaaaaaaaaaaao.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.oaaaaaaaaaaaao.
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
..oooooooooooo..
................
................
................
"""

SKEIN = """
................
......oooo......
.....owwwwo.....
....owwwwwwo....
...owwhwwwwo....
...owwwwwwwwo...
..owwwwwwwwwo...
..owwwwwwwwwo...
..owwwwwwwwo....
...owwwwwwwo....
...owwwwwwo.....
....owwwwo......
.....oooo.......
.......ww.......
........w.......
................
"""

ORGAN = """
................
.......oo.......
......oggo......
.....oggggo.....
....oghhgggo....
...oghhggggo....
...oggggggggo...
..oggggggggggo..
..oggggggggggo..
..oggggggggggo..
...oggggggggo...
....oggggggo....
.....oggggo.....
......oggo......
.......oo.......
................
"""

TEARDROP = """
................
.......o........
......ogo.......
......ogo.......
.....oggo.......
.....ogggo......
....oghhggo.....
...oghhgggo.....
...ogggggggo....
..oggggggggo....
..oggggggggo....
..oggggggggo....
...oggggggo.....
....oggggo......
.....oooo.......
................
"""

FANG = """
................
.........oo.....
........owwo....
........owwo....
.......owwwo....
.......owwwo....
.......owwo.....
......owwwo.....
......owwo......
.....owwwo......
.....owwo.......
....owwo........
....owo.........
...owo..........
...oo...........
................
"""

TOOTH = """
................
......oooo......
.....owwwwo.....
.....owwwwo.....
.....owwwwo.....
.....owhwwo.....
.....owwwwo.....
......owwwo.....
......owwwo.....
......owwo......
.......owwo.....
.......owwo.....
........owo.....
........owo.....
.........o......
................
"""

HOOK_CLAW = """
................
....oo..........
...okko.........
...okkko........
....okkko.......
.....okkko......
......okkko.....
.......okkko....
.......okkkko...
......okkkkko...
.....okkkkkko...
....okkkkkkko...
...okkkkkkko....
...okkkkkko.....
....ooooooo.....
................
"""

FUR_CLAW = """
................
..........oo....
.........okko...
........okkko...
........okkko...
.......okkkko...
.......okkkko...
......okkkko....
......okkkko....
.....okkkko.....
....offffo......
...offffffo.....
...offffffo.....
....offffo......
.....oooo.......
................
"""

FEATHER = """
................
..........oo....
.........offo...
........offffo..
.......offffo...
......offqffo...
.....offqffo....
....offqffo.....
....offqfo......
...offqffo......
...ofqffo.......
..ofqfo.........
..oqfo..........
..oqo...........
..oo............
................
"""

GEODE = """
................
................
....oooooo......
...osssssso.....
..ossscsssso....
..osscccssso....
.ossccGccssso...
.osscGGGcssso...
.osscccGcssso...
..osscccssso....
..ossscsssso....
...osssssso.....
....oooooo......
................
................
................
"""

BLOB = """
................
................
.....oooo.......
....oggggo......
...oghhgggo.....
..oghhggggo.....
..ogggggggo.....
.oggggggggggo...
.oggggggggggo...
.oggggggggggo...
..oggggggggo....
...oggggggo.....
....oooooo......
................
................
................
"""

SCALE = """
................
.......oo.......
.....oosSoo.....
....osSSSSso....
...osSSSSSSso...
..osSSSSSSSSso..
..oSSSSSSSSSo...
..oSSSSSSSSSo...
...oSSSSSSSo....
....oSSSSSo.....
.....oSSSo......
......oSo.......
.......o........
..s.........s...
................
................
"""

TUFT = """
................
....h....h......
...hh...hh..h...
...hh..hhh.hh...
..hhh..hhh.hh...
..hhh.hhhhhhh...
..hhdhhhhhdhh...
..hhhhhhhhhhh...
...hhhhhhhhh....
...hhhdhhhhh....
....hhhhhhh.....
....hhhhhh......
.....hhhh.......
......hh........
................
................
"""

BONE = """
................
................
................
..oo........oo..
.owwo......owwo.
.owwwoooooowwwo.
.owwwwwwwwwwwwo.
.owwwoooooowwwo.
.owwo......owwo.
..oo........oo..
................
................
................
................
................
................
"""

ARROW_BUNDLE = """
................
..k....k....k...
..kk...kk...kk..
.kkkk.kkkk.kkkk.
..ss...ss...ss..
..ss...ss...ss..
..ss...ss...ss..
.tttttttttttttt.
.tttttttttttttt.
..ss...ss...ss..
..ss...ss...ss..
..ss...ss...ss..
..ff...ff...ff..
.f.f..f.f..f.f..
................
................
"""

ARROW_PROJECTILE = """
................
................
................
................
................
........k.......
.ff.....kk......
.fffsssskkkk....
.ff.....kk......
........k.......
................
................
................
................
................
................
"""

ROCK_PROJECTILE = """
................
................
................
.....oooo.......
....ohhhhoo.....
...ohhhhhssdo...
..ohhhhssssddo..
..ohhssssssddo..
..osssssdddddo..
...osssddddddo..
....odddddddo...
.....ooooooo....
................
................
................
................
"""

# Raw fish (Mirefolk drop). Side view, head left, fan tail right.
FISH = """
................
................
.....ooooo......
...oobbbbboo..o.
..obbbbbbbbbo.to
.obwwbbbbbbbbott
.obwebbbbbbbbbtt
.obbbbbbbbbbbbtt
.obbbbbbbbbbbbtt
.obbbbbbbbbbbott
..obbbbbbbbbo.to
...oobbbbboo..o.
.....ooooo......
................
................
................
"""

# Camp fire node tile (grug_mobs:camp_fire), used on every face of the low
# nodebox: a stone ring around charred logs and a hot core, seen top-down.
# Fully opaque -- a node tile must not have holes.
CAMP_FIRE = """
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaooooooooaaaa
aaaoOooooooOoaaa
aaoOoaeeeeaoOoaa
aaooaeEFFEeaooaa
aoOoaeFYYFeaoOoa
aooaeEFYYFEeaooa
aooaeEFYYFEeaooa
aoOoaeFYYFeaoOoa
aaooaeEFFEeaooaa
aaoOoaeeeeaoOoaa
aaaoOooooooOoaaa
aaaaooooooooaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
"""


GUARD_BANNER = """
......pPPp......
......pPPpeeeee.
......pPPpcCccc.
......pPPpccmcc.
......pPPpcmmmc.
......pPPpcmcmc.
......pPPpccccc.
......pPPpeeeee.
......pPPp......
......pPPp......
......pPPp......
......pPPp......
......pPPp......
......pPPp......
......pPPp......
......pPPp......
"""


# Overlay tile of grug_nodes:depleted_vein (WP6/T9 R4 ore respawn): the
# pockets a mined-out vein leaves in the stone. Composed over
# default_stone.png at runtime, so everything outside the pockets stays
# transparent ('.'). Four hollows plus a hairline crack, all kept one pixel
# away from the border so the tile still tiles seamlessly. Each hollow is a
# dark core ('d'), a softer floor ('s') and a lit lower-right rim ('h') --
# the same light-from-the-upper-left convention as the other node art here.
DEPLETED_VEIN = """
................
................
...dd...........
..dddh....dd....
...sh....dddh...
..........sh....
.......s.....s..
.......d........
........d..dd...
........s.dddh..
....dd.....sh...
...dddh.........
....sh..........
.........d......
................
................
"""


# Trash loot of the bandit families (WP7): a drawstring coin pouch, pulled
# shut at the neck ('s' = cord), and a torn faction pennant on a snapped
# pole. Both exist to be sold to vendors and are never worn, so they read at
# icon size rather than carrying detail.
STOLEN_PURSE = """
................
................
......ooo.......
.....o.s.o......
.....os.so......
....ossssso.....
...obbbbbbbo....
..obbbbbbbbbo...
..obbbhbbbbbo...
..obbbbbbbbbo...
..obbbbbbbbbo...
...obbbbbbbo....
....ooooooo.....
................
................
................
"""

WAR_TROPHY = """
................
.....o..........
.....op.........
.....opccco.....
.....opcccco....
.....opcchcco...
.....opcccco....
.....opcccoo....
.....opcco......
.....opco.......
.....opo........
.....opo........
.....opo........
......oo........
................
................
"""


# ----------------------------------------------------------------- gear art
# Vendor bracket gear (grug_gear, items_crafting.md §3.8). Eight base arts
# only: the four weapon families and the four armor slots. The cloth armor
# line reuses the SAME four armor arts with a cloth palette (the FEATHER /
# BOLT trick above), and the six brackets are tinted at runtime with
# `^[multiply:<hex>` -- so the whole catalog costs 12 PNGs, not 72.

# Blade up, brass crossguard, wrapped grip. 'h' is the lit blade edge
# (light from the upper left, like the rest of the art in this file).
SWORD = """
................
.......oo.......
......ohbo......
......ohbo......
......ohbo......
......ohbo......
......ohbo......
......ohbo......
......ohbo......
...ogggggggo....
...ooooooooo....
......oppo......
......oppo......
......oppo......
.....opppo......
......ooo.......
"""

# Same steel and grip as the sword, but only 5 rows of blade against the
# sword's 8 and a stubbier guard: the fpi 0.7 weapon has to read as "short"
# next to the sword at 16px, and length is the only cue that survives there.
DAGGER = """
................
................
................
.......oo.......
......ohbo......
......ohbo......
......ohbo......
......ohbo......
....oogggoo.....
....ooooooo.....
......oppo......
......oppo......
.....opppo......
......ooo.......
................
................
"""

# Two-hander: a single-bit crescent head ('k' iron, 'h' the ground cutting
# edge on the left) hung off a haft ('s') that runs the full icon height --
# a symmetric head reads as a mushroom at this size, the offset one does not.
GREATAXE = """
................
.........oso....
.....oooooso....
...oohkkkkso....
..ohkkkkkkso....
..ohkkkkkkso....
.ohkkkkkkkso....
..ohkkkkkkso....
..ohkkkkkkso....
...oohkkkkso....
.....oooooso....
.........oso....
.........oso....
.........oso....
.........oso....
.........ooo....
"""

# Caster two-hander: focus crystal ('C' lit facet, 'c' body) on a shaft with
# two metal bands ('b').
STAFF = """
................
......ooo.......
.....ocCco......
....ocCCCco.....
....occCcco.....
.....occco......
......ooo.......
......oso.......
......oso.......
......obo.......
......oso.......
......oso.......
......oso.......
......obo.......
......oso.......
......ooo.......
"""

# Armor slots. Deliberately silhouette-first (helm with visor slits, torso
# with pauldrons, two-legged greaves, side-view boot) so the same four arts
# still read as cowl/robe/leggings/slippers under the cloth palette.
ARMOR_HEAD = """
................
................
......oooo......
....oobbbboo....
...obbbbbbbbo...
..obbbbhbbbbbo..
..obbbbbbbbbbo..
..oddddbbddddo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...obbbbbbbbo...
...obbo..obbo...
...oooo..oooo...
................
................
................
"""

ARMOR_CHEST = """
................
..oo........oo..
.obbo......obbo.
.obbbo....obbbo.
.obbbbooooobbbo.
.obbbbbbbbbbbbo.
.obbbbbhbbbbbbo.
.obbbbbbbbbbbbo.
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
..obbbbbbbbbbo..
...oooooooooo...
................
"""

ARMOR_LEGS = """
................
..oooooooooooo..
.obbbbbbbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbbhbbbbbbo.
.obbbbbbbbbbbbo.
.obbbbboobbbbbo.
.obbbbo..obbbbo.
.obbbbo..obbbbo.
.obbbbo..obbbbo.
.obbbbo..obbbbo.
.obbbbo..obbbbo.
.obbbbo..obbbbo.
.obbbbo..obbbbo.
..oooo....oooo..
................
"""

ARMOR_FEET = """
................
................
....oooooo......
...obbbbbbo.....
...obbbbbbo.....
...obhbbbbo.....
...obbbbbbo.....
...obbbbbbo.....
...obbbbbbo.....
...obbbbbbooo...
...obbbbbbbbbo..
...obbbbbbbbbbo.
...obbbbbbbbbbo.
....oooooooooo..
................
................
"""

# Shared palettes for the two armor lines that ship (metal = armor class 3,
# cloth = 1; leather is Phase 2 and has no art yet).
ARMOR_METAL = {"o": "#20222a", "b": "#9aa3ad", "h": "#d6dde4", "d": "#12141a"}
ARMOR_CLOTH = {"o": "#332b3d", "b": "#6f5f8c", "h": "#a394c0", "d": "#221c2a"}


# --------------------------------------------------------------- trader art
# Vendor consumables (grug_traders, items_crafting.md §3.6/§8.2). A round
# flask with a corked neck: the silhouette has to read as "potion" at 16px
# next to the tool and armor icons, so the body is deliberately wider than
# anything else in this file.

POTION_FLASK = """
................
......oooo......
......occo......
......ohgo......
......ohgo......
.....ohgggo.....
....ohgggggo....
...ohgggggggo...
...oRrrrrrrro...
..oRrrrrrrrrro..
..oRrrrrrrrrro..
..oRrrrrrrrrro..
..orrrrrrrrrro..
...orrrrrrrro...
....oooooooo....
................
"""


# ------------------------------------------------------------------- recipes
# (file name, art, palette)

ICONS = [
    ("grug_mobs_item_light_leather.png", HIDE,
     {"o": "#5a3f28", "b": "#b98a55", "h": "#d8ab74"}),
    ("grug_mobs_item_heavy_leather.png", HIDE_STACK,
     {"o": "#3d2a19", "b": "#8a5f38", "c": "#6f4c2c", "h": "#a97a4a"}),
    ("grug_mobs_item_scaled_hide.png", SCALED,
     {"o": "#20402f", "b": "#3f7a56", "s": "#59a071"}),
    ("grug_mobs_item_sleek_pelt.png", PELT,
     {"o": "#1b1b22", "b": "#3a3a46", "h": "#5c5c6e"}),
    ("grug_mobs_item_linen_scrap.png", SCRAP,
     {"o": "#7d7461", "b": "#cfc4a8"}),
    ("grug_mobs_item_linen_cloth.png", BOLT,
     {"o": "#8a8068", "b": "#ded3b6", "h": "#f2ead2", "a": "#bfb392"}),
    ("grug_mobs_item_heavy_cloth.png", BOLT,
     {"o": "#3f3a30", "b": "#8f8365", "h": "#a99b78", "a": "#6d6450"}),
    ("grug_mobs_item_spider_silk.png", SKEIN,
     {"o": "#9aa3ad", "w": "#eef2f6", "h": "#ffffff"}),
    ("grug_mobs_item_venom_gland.png", ORGAN,
     {"o": "#274a1e", "g": "#6aa83c", "h": "#9ed46a"}),
    ("grug_mobs_item_venom_sac.png", TEARDROP,
     {"o": "#3a1f4a", "g": "#7b3fa0", "h": "#b276d4"}),
    ("grug_mobs_item_fang.png", FANG,
     {"o": "#7a705c", "w": "#efe7cf"}),
    ("grug_mobs_item_croc_tooth.png", TOOTH,
     {"o": "#7a6d4a", "w": "#e8dcae", "h": "#fff6d2"}),
    ("grug_mobs_item_raptor_claw.png", HOOK_CLAW,
     {"o": "#120f12", "k": "#3c3230"}),
    ("grug_mobs_item_bear_claw.png", FUR_CLAW,
     {"o": "#2a201a", "k": "#e0d6bf", "f": "#7a5231"}),
    ("grug_mobs_item_feather.png", FEATHER,
     {"o": "#8c8f96", "f": "#e8ecf2", "q": "#c2c7cf"}),
    ("grug_mobs_item_sharp_feather.png", FEATHER,
     {"o": "#2b3138", "f": "#6e7a86", "q": "#aeb8c2"}),
    ("grug_mobs_item_stone_core.png", GEODE,
     {"o": "#2f2f33", "s": "#77787e", "c": "#4f5056", "G": "#ffd45e"}),
    ("grug_mobs_item_slime_gel.png", BLOB,
     {"o": "#2d4a1c", "g": "#7fb04a", "h": "#b6da84"}),
    ("grug_mobs_item_shiny_scale.png", SCALE,
     {"o": "#1d4a4f", "S": "#43b0b8", "s": "#7fdde3"}),
    ("grug_mobs_item_ape_hair.png", TUFT,
     {"h": "#3a2c22", "d": "#241a13"}),
    ("grug_mobs_item_bone.png", BONE,
     {"o": "#8d8672", "w": "#efe9d6"}),
    ("grug_mobs_item_arrow.png", ARROW_BUNDLE,
     {"k": "#b9c0c8", "s": "#8a6238", "t": "#6b4a2a", "f": "#d9d2c0"}),
    # Projectile sprite of grug_mobs:arrow_entity (not an inventory item).
    ("grug_mobs_arrow.png", ARROW_PROJECTILE,
     {"k": "#c9d1da", "s": "#8a6238", "f": "#e2dccb"}),
    # Projectile sprite of grug_mobs:rock_entity (golem, not an inventory
    # item): a lit-from-the-upper-left grey boulder.
    ("grug_mobs_rock.png", ROCK_PROJECTILE,
     {"o": "#2b2b30", "h": "#9a9aa2", "s": "#6e6e77", "d": "#4a4a52"}),
    ("grug_mobs_item_raw_fish.png", FISH,
     {"o": "#2c4a55", "b": "#6fa3b4", "t": "#4b7d8e", "w": "#eef4f6",
      "e": "#16202a"}),
    # Node tile of grug_mobs:camp_fire (not an inventory item).
    ("grug_mobs_camp_fire.png", CAMP_FIRE,
     {"a": "#3a332c", "o": "#6b6259", "O": "#8a8078", "e": "#7a3a16",
      "E": "#c25a1c", "F": "#f08a2a", "Y": "#ffd45e"}),
    # WP7 bandit trash loot (items_crafting.md §8.1: the "stolen purse"
    # replaces physical coin drops) and the faction war trophy.
    ("grug_mobs_item_stolen_purse.png", STOLEN_PURSE,
     {"o": "#3d2a19", "b": "#8a5f38", "h": "#a97a4a", "s": "#6f4c2c"}),
    ("grug_mobs_item_war_trophy.png", WAR_TROPHY,
     {"o": "#241a13", "p": "#6b4a2a", "c": "#a8323c", "h": "#e8c46a"}),
]

# Vendor bracket gear (mods/ITEMS/grug_gear). Twelve files for a 72-item
# catalog: one art per weapon family, one per armor slot, the armor arts
# emitted twice (metal + cloth palette). The bracket ladder is a runtime
# `^[multiply:` tint in grug_gear/init.lua, never a PNG.
GEAR_ICONS = [
    ("grug_gear_item_sword.png", SWORD,
     {"o": "#20222a", "b": "#9aa3ad", "h": "#e2e8ee", "g": "#8a6f3a",
      "p": "#5a3d24"}),
    ("grug_gear_item_dagger.png", DAGGER,
     {"o": "#20222a", "b": "#9aa3ad", "h": "#e2e8ee", "g": "#8a6f3a",
      "p": "#5a3d24"}),
    ("grug_gear_item_greataxe.png", GREATAXE,
     {"o": "#1a1a20", "k": "#6e7681", "h": "#c6cdd6", "s": "#6b4a2a"}),
    ("grug_gear_item_staff.png", STAFF,
     {"o": "#241d2a", "c": "#4a7fc0", "C": "#a8d8ff", "s": "#6b4a2a",
      "b": "#b9c0c8"}),
    ("grug_gear_item_head_metal.png", ARMOR_HEAD, ARMOR_METAL),
    ("grug_gear_item_chest_metal.png", ARMOR_CHEST, ARMOR_METAL),
    ("grug_gear_item_legs_metal.png", ARMOR_LEGS, ARMOR_METAL),
    ("grug_gear_item_feet_metal.png", ARMOR_FEET, ARMOR_METAL),
    ("grug_gear_item_head_cloth.png", ARMOR_HEAD, ARMOR_CLOTH),
    ("grug_gear_item_chest_cloth.png", ARMOR_CHEST, ARMOR_CLOTH),
    ("grug_gear_item_legs_cloth.png", ARMOR_LEGS, ARMOR_CLOTH),
    ("grug_gear_item_feet_cloth.png", ARMOR_FEET, ARMOR_CLOTH),
]

# Vendor consumables (mods/ENTITIES/grug_traders). One file today: the weak
# healing potion of items_crafting.md §3.6, the only potion the vendor floor
# sells. WP10's alchemy potions get their own palettes on the SAME flask art
# (the FEATHER / armor-line trick above) when they land.
TRADER_ICONS = [
    ("grug_traders_item_potion_healing_weak.png", POTION_FLASK,
     {"o": "#20222a", "c": "#8a5f38", "g": "#cfe0ea", "h": "#ffffff",
      "r": "#c0303c", "R": "#e8626c"}),
]

# Node tiles that live in ANOTHER mod but are authored by the same rules
# (16x16 ASCII art, CC0, deterministic). Kept in this script instead of a
# near-identical sibling so there is exactly one generator to maintain.
NODE_ICONS = [
    # Tile of grug_nodes:guard_banner (WP6/T8 guard post anchor). The node is
    # a nodebox, and nodebox faces sample the REGION of the tile their box
    # covers: columns 6..9 are the pole, columns 10..14 / rows 1..7 the flag
    # board, the rest is never drawn and stays transparent. Faction-neutral
    # colours on purpose (the faction comes from the territory, not the node).
    ("grug_nodes_guard_banner.png", GUARD_BANNER,
     {"p": "#4a3524", "P": "#6b4e33", "e": "#7a6a52", "c": "#d9d2be",
      "C": "#efe9d8", "m": "#3f4a5a"}),
    # Overlay tile of grug_nodes:depleted_vein (WP6/T9). Neutral greys only:
    # the pockets must read as holes in the grey default_stone.png below,
    # never as a new mineral.
    ("grug_nodes_depleted_vein.png", DEPLETED_VEIN,
     {"d": "#2c2c2c", "s": "#414141", "h": "#8b8b8b"}),
]


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else \
        os.path.join("mods", "ENTITIES", "grug_mobs", "textures")
    nodes_outdir = sys.argv[2] if len(sys.argv) > 2 else \
        os.path.join("mods", "ITEMS", "grug_nodes", "textures")
    gear_outdir = sys.argv[3] if len(sys.argv) > 3 else \
        os.path.join("mods", "ITEMS", "grug_gear", "textures")
    traders_outdir = sys.argv[4] if len(sys.argv) > 4 else \
        os.path.join("mods", "ENTITIES", "grug_traders", "textures")
    for d in (outdir, nodes_outdir, gear_outdir, traders_outdir):
        if not os.path.isdir(d):
            raise SystemExit("no such directory: " + d)
    for name, art, palette in ICONS:
        print(build(name, art, palette, outdir))
    for name, art, palette in NODE_ICONS:
        print(build(name, art, palette, nodes_outdir))
    for name, art, palette in GEAR_ICONS:
        print(build(name, art, palette, gear_outdir))
    for name, art, palette in TRADER_ICONS:
        print(build(name, art, palette, traders_outdir))
    print("%d icons written to %s, %d to %s, %d to %s, %d to %s"
          % (len(ICONS), outdir, len(NODE_ICONS), nodes_outdir,
             len(GEAR_ICONS), gear_outdir,
             len(TRADER_ICONS), traders_outdir))


if __name__ == "__main__":
    main()
