"""Round 38 lane I: README.md and summary.md of the name inventory
(written by inventory.py; deterministic, no timestamps)."""
from collections import Counter, defaultdict

import check_rules
import inventory

RACE_ORDER = ["dwarf", "human", "elf", "undead", "orc", "troll"]


def readme(model, meta):
    srcs = "\n".join("| `%s` | %s | %s |" % (s["id"], s["what"], s["where"].replace("|", "/"))
                     for s in model.sources)
    by_source = Counter(s["source"] for s in model.slots)
    src_counts = ", ".join("%s %d" % kv for kv in sorted(by_source.items()))
    return """# Round 38 name inventory

Generated by `tools/r38_names/inventory.py` (lane I) from the shipped data and
code; do not edit by hand. Input digest `{digest}` ({slots} slots,
{objectives} quest objectives aimed at mobs, {surfaces} text surfaces).

## Rebuild

    cd <repo or worktree>
    python3 tools/r38_names/inventory.py [--out DIR]          # writes this folder
    python3 tools/r38_names/inventory.py --check [--out DIR]  # exit 1 when stale
    python3 tools/r38_names/check_rules.py <proposal files>   # rules 1-4 (plan §2.2)
    python3 tools/r38_names/check_rules.py --today            # today's names
    python3 tools/r38_names/test_rules.py                     # the checker's fixture

The zones' neighbours come from `tools/r38_names/neighbours.tsv`, built by
`luajit tools/r38_names/neighbours.lua . > tools/r38_names/neighbours.tsv`
(the zone session of the six quest seeds, about 55 s; run it through the
round's Lua queue). Rebuild it after a zone-field change only.

As a module: `sys.path.insert(0, "tools/r38_names"); import inventory;
m = inventory.build()` gives `m.slots`, `m.slot_by_key`, `m.objectives`,
`m.zones`, `m.surfaces`, `m.drop_tier(level)`, `m.signal` (the signal-word
set); `build(repo, surfaces=False)` skips the text scan. A full build takes
about a second.

## What a slot is

One name a player can see on a mob, today and after the round. Every slot
has a **slot key** `<scope>/<source id>/L<lo>-<hi>`:

- `<scope>`: the zone id (`kragmar_stillgrave_hollow`), or `world` for
  slots without a zone (the underground casts, the water mobs, the
  settlement and outpost guards, sub-types nothing places).
- `<source id>`: the sub-type role for recipe roles, leaders, critters, the
  Rift Spawn rows and summons (`small_boar`); `rare.<rare id>` for a named
  rare; `<settlement key>.<post>` for a PvP garrison (`guard`, `general`,
  `bodyguard`, `commander`, `captain-<race>`); the entity role otherwise
  (`king_dwarf`, `royal_guard_dwarf`, `ice_dragon`, `ice_whelp`,
  `rift_boss`, `guard_accord`, `zombie`).
- `L<lo>-<hi>`: the levels the mob of this slot spawns at (always both
  numbers, `L10-10` for one level).

Slots by source: {src_counts}.

- **recipe**: one slot per (zone, sub-type role, level range) of the zone's
  spawn recipe. A role's level range in a kind or camp is its belt's
  levels cut to the role's catalogue levels (`role_range`), so all kinds
  and camps of one belt that list the role share one slot; the slot's
  `units` list them (kind or camp id, terrain type, belt, clocks,
  `inherited_clocks` where the kind's roster is its belt's `open` roster,
  and the area tag `<zone>/<kind or camp id>` its mobs carry).
- **leader**: a named leader at its fixed level (the top of its role range
  in its belt); leaders carry no area tag.
- **critter**: a critter row the recipe keeps (level 1, one entity name in
  every zone today).
- **abm_row**: the Rift Spawn's surface rows in the four zones that keep
  them, one slot per belt middle (the region level it spawns at).
- **rare**, **boss**, **boss_guard**, **summon**, **pvp_garrison**,
  **guard**, **underground**, **water**, **unplaced**: the other name
  sources below.

The displayed nametag is `<tier prefix><name> [Lv n] hp/max`: `Elite `, a
star for rares, `Boss `; the prefix is not part of the name.

## Files

- `slots.json`: everything: `zones` (zone facts: band, race region,
  continent, role, neighbours on all six seeds and on some seeds),
  `slots`, `objectives`, `sources`. Slot fields: `key`, `zone`,
  `zone_name`, `zone_role`, `zone_band`, `race_region`, `continent`,
  `neighbours`, `neighbours_some_seeds`, `source`, `name` (today),
  `name_source`, `name_where` (file:line), `words`, `signal_words`,
  `entity`, `role`, `family`, `base`, `tier` (normal, critter, guard,
  elite, named, boss: the class rule 1 counts words by), `authored_tier`,
  `leader`, `disposition`, `size` (the authored size factor; a leader's is
  grug_mobs.LEADER.size), `drops` (drop family), `role_levels`, `levels`,
  `drop_tiers`, `clocks` (day, night, any, cave), `units`, `tags` (area
  tags its mobs carry), `quest_targets`, `quest_mentions`, `notes`, and
  for PvP captains and commanders `quest_label` (the generic name the quest
  log shows for them, "Throng Captain").
- `zones.tsv`: one row per zone (band, race region, continent, role,
  biomes, neighbours on all six seeds and on some, slot count).
- `slots.tsv`: one row per slot (the columns a naming agent scans;
  `same_name_not_counted` is "in the zone/everywhere": the spawn sources
  bearing the label's name that the slot's quests do not count);
  `by_zone/<zone>.tsv` and `by_zone/world.tsv` split it per zone.
- `surfaces.tsv`: every place a slot's name appears as text (goal 4).
- `today/<zone>.json`, `today/world.json`: today's names in the proposal
  format below (a template for the naming lanes).
- `today_check.txt`: `check_rules.py` over today's names.
- `summary.md`: one page of counts and findings; `lists.md`: the full
  name lists behind it.

## Drop tier

`drop_tier(L) = clamp(floor((L - 1) / 10) + 1, 1, 6)`: the loot code's
`grug_mobs.level_band` (family drop table) and `grug_items.enchant_tier`
(gear pool, `ceil(L / 10)` of `min(L, 60)`) give the same tier for every
mob level: 1-10 T1, 11-20 T2, 21-30 T3, 31-40 T4, 41-50 T5, 51-60 T6 (and
above 60 T6 for drops). Level 30 is T3 and level 20 is T2, so the
capitals' first belt (L20-23) spans T2 and T3 on its own. (Bag sizes use
other cuts, 15/30/45: `grug_items.BAG_DROPS`.)

## Quest links

`objectives` (and each slot's `quest_targets`) hold every kill objective,
item objective with `roles` and quest drop: quest id, file, JSON path,
kind, roles, area, the label the game shows per role (the role's display
name in its target zone: a leader's zone, else the area's zone, else the
quest's zone; for an item objective the quest log shows the item, and the
label is its source mob's name), `targets` (the slots whose mobs count),
and:

- `same_name_not_counted`: spawn sources `<slot key>@<kind or camp id>`
  (no `@` for untagged sources) whose mobs bear the label's name but do not
  count (another kind or camp than the area, another zone, another role);
  `same_name_not_counted_in_zone`: those in the target zone (the
  kill-credit bug of plan §1);
- `counted_other_name`: counting sources whose mobs show another name.

`quest_mentions` lists every quest-file string that names today's name
verbatim (simple plurals and possessives included; quest id and JSON path).
Placeholders such as `{{name:<leader role>}}` fill a leader's or an area's
name at runtime and follow a rename by themselves.

## Text surfaces (`surfaces.tsv`)

Every verbatim occurrence of a slot name, and of the generic quest labels
"Accord/Throng Captain" and "Accord/Throng War Commander" (counted for the
captain and commander slots), case-insensitive for names of two or more
words, case-sensitive and only in `mods/` for one-word names; the longest
name wins where names overlap ("Braindead Zombie", not "Zombie"):
`quest_text` (quest files), `name_source` (the name's own definition in
subtypes.json), `game_data` (other JSON: items, pvp_names), `game_code` (Lua
strings and comments), `generated_doc` (`docs/design/zone_mobs.md`, rebuilt by
`tools/r37_dd/zone_mobs.lua`), `doc` (`docs/design/*.md`, the story bible,
README.md), `tool` (fixtures and tools that spell a name). Not scanned:
vendored mods, history (CHANGELOG, older planning). Dynamic surfaces that
need no text edit: quest labels, the tracker and the feed
(`grug_quests/labels.lua` reads the display names), `{{name:...}}`
placeholders, the rare broadcast (`rares.lua` spec.name), kill notices
from the entity description. The only locale files are the vendored
mobs mod's; no grug mod ships a translation.

## Proposal format (for `check_rules.py`)

One JSON file per zone (and `world.json`):

    {{"zone": "<zone id or world>", "lane": "Z3",
     "slots": {{"<slot key>": {{"name": "Forest Piglet", "reason": "one line"}},
               "<slot key>": {{"keep": true, "reason": "one line"}}}}}}

Every slot is named exactly once over all files; `keep: true` keeps
today's name. `check_rules.py` prints one line per problem (`R0` coverage,
`R1` words, `R2` signal words, `R3` Piglet, `R4` level stretch) and exits 1
on any; `--partial` checks only the zones the given files touch (rule 4
then sees only those names). Notes (no exit status) flag a `*_hunt_01`
start pig without "Piglet" and slots whose own band spans tiers.

## Name sources (file:line)

| id | what | where |
|---|---|---|
{srcs}

Rows marked "(no slot)" were searched and name no creature (job titles,
item and place labels, player tags) or are dormant today.
""".format(digest=meta["input_digest"], slots=len(model.slots), objectives=len(model.objectives),
           surfaces=len(model.surfaces), src_counts=src_counts, srcs=srcs)


def summary(model):
    slots = model.slots
    lines = ["# Round 38 name inventory: summary", ""]
    names = {s["name"] for s in slots}
    by_tier = Counter(s["tier"] for s in slots)
    by_cont = Counter(s["continent"] or "world" for s in slots)
    lines.append("**%d slots**, %d distinct names today. Tier: %s. Continent: %s." % (
        len(slots), len(names), ", ".join("%s %d" % kv for kv in sorted(by_tier.items())),
        ", ".join("%s %d" % kv for kv in sorted(by_cont.items()))))
    lines.append("")
    lines.append("Per race region (the naming lanes), zone: slots")
    lines.append("")
    zcount = Counter(s["zone"] for s in slots if s["zone"])
    for race in RACE_ORDER:
        zs = [z for z in model.zone_order if model.zones[z]["race_region"] == race]
        lines.append("- **%s** %d: %s" % (race, sum(zcount[z] for z in zs), ", ".join(
            "%s %d" % (model.zones[z]["name"], zcount[z]) for z in zs)))
    lines.append("- **world** %d: underground %d, guards %d, water %d, unplaced %d" % (
        sum(1 for s in slots if not s["zone"]), *[sum(1 for s in slots if s["source"] == k)
                                                  for k in ("underground", "guard", "water", "unplaced")]))
    fam = Counter(s["family"] for s in slots if s["source"] in ("recipe", "leader"))
    lines.append("")
    lines.append("Families (recipe and leader slots, %d): " % len(fam) +
                 ", ".join("%s %d" % kv for kv in fam.most_common(14)) + " ... (all in `lists.md`)")
    # quests
    obj = model.objectives
    targeted = sum(1 for s in slots if s["quest_targets"])
    pairs = set()
    for o in obj:
        if not o["area"]:
            continue
        for role in o["roles"]:
            lab = o["labels"][role].lower()
            if any(model.slot_by_key[x.split("@")[0]]["name"].lower() == lab
                   for x in o["same_name_not_counted_in_zone"]):
                pairs.add((o["area"].split("/")[0], role))
    rpairs = {p for p in pairs if p[1] in model.subtypes}
    lines.append("")
    other = [o for o in obj if o["counted_other_name"]]
    lines.append("**Quests:** %d objectives aim at mobs (%s); %d slots are targeted. %d objectives leave "
                 "same-named mobs uncounted, %d of them in the target zone itself: %d area-targeted "
                 "(zone, role) pairs, %d of recipe roles (the Round 37 analysis' %d rows with area quests "
                 "in `multi_region_roles.tsv`, the same pairs; its 159 counts only roles in two or more "
                 "kinds) and %d of garrison guards. %d objectives count mobs of another name than their "
                 "label (%s)." % (
                     len(obj), ", ".join("%s %d" % kv for kv in sorted(Counter(o["kind"] for o in obj).items())),
                     targeted, sum(1 for o in obj if o["same_name_not_counted"]),
                     sum(1 for o in obj if o["same_name_not_counted_in_zone"]), len(pairs), len(rpairs),
                     len(rpairs), len(pairs) - len(rpairs), len(other),
                     "all PvP captains and commanders: the quest label is the entity's \"Throng Captain\", "
                     "the mob shows its pvp_names.json name" if other and all(
                         r.startswith(("captain_", "commander_")) for o in other for r in o["roles"]
                         if any(model.slot_by_key[x.split("@")[0]]["role"] == r for x in o["counted_other_name"]))
                     else "see `objectives` in slots.json"))
    # rules today
    problems, notes = check_rules.check(model, check_rules.today_entries(model))
    rc = Counter(p.split()[0] for p in problems)
    r4names = {p.split("'")[1] for p in problems if p.startswith("R4")}
    lines.append("")
    lines.append("**Today's names as a proposal** (`today_check.txt` has every line): %d problems: R1 %d, R2 %d, R3 %d, "
                 "R4 %d lines over %d names; %d notes." % (len(problems), rc["R1"], rc["R2"], rc["R3"],
                                                          rc["R4"], len(r4names), len(notes)))
    by_name = defaultdict(list)
    for s in slots:
        by_name[s["name"]].append(s)
    long_normal = sorted(n for n, ss in by_name.items()
                         if any(s["words"] > inventory.TIER_WORDS[s["tier"]] and inventory.TIER_WORDS[s["tier"]] == 2
                                for s in ss))
    long_named = sorted(n for n, ss in by_name.items()
                        if any(s["words"] > 3 and inventory.TIER_WORDS[s["tier"]] == 3 for s in ss))
    lines.append("")
    lines.append("- Normal, critter or guard names with more than 2 words: %d names (%d slots), e.g. %s." % (
        len(long_normal), sum(len(by_name[n]) for n in long_normal), "; ".join(long_normal[:4])))
    lines.append("- Named, elite or boss names with more than 3 words: %d (the six \"Confused ... Chief\" start "
                 "leaders, kings and royal guards, %s)." % (len(long_named), "; ".join(
                     n for n in long_named if not n.startswith(("Confused", "King of")))))
    sig = Counter(w for s in slots for w in s["signal_words"])
    signed = sorted({s["name"] for s in slots if s["signal_words"]})
    lines.append("- Signal words: %d slots, %d names (%s)." % (
        sum(1 for s in slots if s["signal_words"]), len(signed), ", ".join("%s %d" % kv for kv in sig.most_common())))
    lines.append("- Rule 2.2.4 broken today by %d names (a gap or more than one drop tier across their bands), e.g. %s." % (
        len(r4names), "; ".join(sorted(r4names)[:4])))
    keep3 = sorted({s["name"] for s in slots if s["tier"] in ("named", "elite", "boss") and s["words"] == 3})
    caps = [n for n in keep3 if n.startswith("Captain ")]
    lines.append("- Three-word named, elite and boss names that keep their names (§2.2.1): %d, %d of them "
                 "PvP captains; e.g. %s (all in `lists.md`)." % (
                     len(keep3), len(caps), "; ".join([n for n in keep3 if n not in caps][:5])))
    multi = [s for s in slots if len(s["drop_tiers"]) > 1]
    lines.append("")
    lines.append("**Findings worth a look**")
    lines.append("")
    msrc = Counter(s["source"] for s in multi)
    lines.append("- %d slots span several drop tiers on their own (%s), so no name can satisfy rule 4's "
                 "\"one tier\" for them: the underground casts (one name per entity, level = max(surface "
                 "level above, depth level): e.g. Zombie L3-60), the two faction guards (L20-60, the same "
                 "entity as the PvP garrison guards), the capital slots of the L20-23 belt (level 20 is T2; "
                 "merging them with L24+ always breaks rule 4) and unplaced elite sub-types." % (
                     len(multi), ", ".join("%s %d" % kv for kv in sorted(msrc.items()))))
    unplaced = [s["name"] for s in slots if s["source"] == "unplaced"]
    lines.append("- %d registered sub-types are never placed (no recipe, camp or leader): %s." % (
        len(unplaced), ", ".join(unplaced)))
    whelps = [s for s in slots if s["role"].endswith("_whelp")]
    lines.append("- The dragon whelps are level %d normal mobs with 4-word names in level-60 island zones; "
                 "the royal guards' names have 5-6 words (\"King of Dur Brannoc Royal Guard\")." %
                 whelps[0]["levels"][0])
    crit = sorted({s["name"] for s in slots if s["source"] == "critter"})
    lines.append("- Critters and the underground and water mobs are base entities: one name for every zone "
                 "today (%s); a per-zone critter name needs a mechanism the sub-types have "
                 "(display_by_zone)." % ", ".join(crit))
    gsig = sorted({s["name"] for s in slots if s["signal_words"] and s["source"] in ("underground",)})
    lines.append("- Underground names with a signal word: %s." % ", ".join(gsig))
    nb = sum(1 for z in model.zones.values() if z["neighbours_some_seeds"])
    lines.append("- Neighbours are geometric and seed-dependent: %d of 38 zones have a neighbour on some of "
                 "the six seeds only (`neighbours_some_seeds`)." % nb)
    lines.append("- PvP captains are named per camp and race (%d names); which one a world shows depends on "
                 "its seed (one race per camp)." % sum(1 for s in slots if ".captain-" in s["key"]))
    return "\n".join(lines) + "\n"


def lists(model):
    """The full name lists behind summary.md."""
    slots = model.slots
    by_name = defaultdict(list)
    for s in slots:
        by_name[s["name"]].append(s)
    problems, _ = check_rules.check(model, check_rules.today_entries(model))
    r4 = sorted({p.split("'")[1] for p in problems if p.startswith("R4")})
    out = ["# Round 38 name inventory: name lists", ""]

    def section(title, names):
        out.append("## %s (%d)" % (title, len(names)))
        out.append("")
        for n in names:
            ss = by_name[n]
            out.append("- %s: %s" % (n, ", ".join(sorted("%s L%d-%d" % (s["zone"] or "world", s["levels"][0],
                                                                         s["levels"][1]) for s in ss))))
        out.append("")
    section("Normal, critter and guard names with more than 2 words", sorted(
        n for n, ss in by_name.items() if any(inventory.TIER_WORDS[s["tier"]] == 2 and s["words"] > 2 for s in ss)))
    section("Named, elite and boss names with more than 3 words", sorted(
        n for n, ss in by_name.items() if any(inventory.TIER_WORDS[s["tier"]] == 3 and s["words"] > 3 for s in ss)))
    section("Names with a signal word", sorted(n for n, ss in by_name.items() if ss[0]["signal_words"]))
    section("Names breaking rule 2.2.4 today", r4)
    section("Three-word named, elite and boss names (they keep their names)", sorted(
        {s["name"] for s in slots if s["tier"] in ("named", "elite", "boss") and s["words"] == 3}))
    fam = Counter(s["family"] for s in slots)
    out.append("## Families (all slots)")
    out.append("")
    out.append(", ".join("%s %d" % kv for kv in sorted(fam.items())))
    return "\n".join(out) + "\n"
