#!/usr/bin/env bash
# Static gates for the round-4 HUD-bars lane: parser and SETGLOBAL per changed
# file and tree-wide, the five plain-5.1 sweeps scoped to the changed Lua and
# then tree-wide over mods/*/grug_* and tools, the fresh-server audit, and a
# LICENSE-media.md row for every texture the lane added.
set -uo pipefail
export LC_ALL=C
repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd -P)"
cd "$repo" || exit 1
LUAC="$repo/tools/bin/luac51"

CHANGED=(
	mods/CORE/grug_core/hud_layout.lua
	mods/CORE/grug_core/init.lua
	mods/PLAYER/grug_abilities/init.lua
	mods/PLAYER/grug_xp/init.lua
	mods/PLAYER/grug_money/init.lua
	tools/ui/hud_bars_kat.lua
)

echo "== parser and SETGLOBAL on every Lua file this lane changed =="
for file in "${CHANGED[@]}"; do
	if "$LUAC" -p "$file" >/dev/null 2>&1; then
		globals="$("$LUAC" -p -l "$file" | grep -c SETGLOBAL)"
		echo "$file parser PASS; SETGLOBAL [$globals]"
	else
		echo "$file parser FAIL"
	fi
done

echo "== whole tree parses =="
find mods -name '*.lua' -path 'mods/*/grug_*' -print0 |
	xargs -0 "$LUAC" -p && echo "mods/*/grug_* parser PASS"
find tools -name '*.lua' -print0 | xargs -0 "$LUAC" -p &&
	echo "tools parser PASS"

sweeps() {
	local index=1
	for pattern in \
		'(^|[^[:alnum:]_.:])goto[[:space:](]|::[A-Za-z_]+::' \
		'\\u\{|\\x[0-9A-Fa-f]|\\z' \
		'table\.(unpack|pack|move)|rawlen|coroutine\.isyieldable|math\.(type|tointeger)|utf8\.' \
		'[^:/]//|[[:alnum:]_)"] *(&|\||<<|>>) *[[:alnum:]_("]' \
		'\brequire[[:space:]]*\(|io\.popen|os\.(execute|exit)|\bminetest\.'; do
		echo "SWEEP $index"
		grep -rnE "$pattern" "$@" --include=*.lua
		index=$((index + 1))
	done
	echo "SWEEPS DONE (no output above a SWEEP line means zero hits)"
}

echo "== five plain-5.1 sweeps, scoped to the Lua this lane changed =="
sweeps "${CHANGED[@]}"

echo "== the same five sweeps over all of mods/*/grug_* and tools =="
sweeps mods/*/grug_* tools

echo "== fresh server check =="
python3 tools/check_fresh_server.py

echo "== every grug_core media file has a LICENSE-media.md row =="
missing=0
for png in mods/CORE/grug_core/textures/*.png; do
	name="$(basename "$png")"
	if grep -qF "\`$name\`" mods/CORE/grug_core/LICENSE-media.md; then
		echo "$name licensed"
	else
		echo "$name MISSING FROM LICENSE-media.md"
		missing=$((missing + 1))
	fi
done
echo "media rows missing: $missing"

echo "== the bar strip is reproducible from its documented one-liner =="
before="$(sha256sum mods/CORE/grug_core/textures/grug_core_hud_bar.png)"
python3 -c 'from PIL import Image; Image.new("RGBA", (1, 1), (255, 255, 255, 255)).save("mods/CORE/grug_core/textures/grug_core_hud_bar.png", optimize=True)'
after="$(sha256sum mods/CORE/grug_core/textures/grug_core_hud_bar.png)"
if [[ "$before" == "$after" ]]; then
	echo "regenerated byte-identical: $after"
else
	echo "GENERATOR DRIFT: $before != $after"
fi
