-- Common mob loot: caster components and vendor trash (WP7). Vendor payouts
-- come from grug_traders' price module (class and tier), not from here.

core.register_craftitem("grug_mobs:zombie_flesh", {
	description = "Rotting Flesh",
	inventory_image = "grug_mobs_item_zombie_flesh.png",
	groups = {grug_material = 1},
})

core.register_craftitem("grug_mobs:boar_tusk", {
	description = "Boar Tusk",
	inventory_image = "grug_mobs_item_boar_tusk.png",
	groups = {grug_material = 1},
})

-- Bandit drop (items_crafting.md §8.1: "Bandit 'coin' drops become a stolen
-- purse trash item"). NOT currency and never will be: money is ONE integer in
-- player meta (economy.md §1), so this item has no on_use, no money effect
-- and nothing may convert it except a trader buying it like any other trash
-- drop.
core.register_craftitem("grug_mobs:stolen_purse", {
	description = "Stolen Purse",
	inventory_image = "grug_mobs_item_stolen_purse.png",
	groups = {grug_trash_loot = 1},
})

-- Faction-NPC PvP drop (items_crafting.md §5.6: "Faction NPC kills
-- additionally drop war trophies"), 1-2 per kill (guard.lua). Trash class.
core.register_craftitem("grug_mobs:war_trophy", {
	description = "War Trophy",
	inventory_image = "grug_mobs_item_war_trophy.png",
	groups = {grug_trash_loot = 1},
})

--
-- Shared mob materials (docs/design/biomes_mobs.md §6 base-material map).
--
-- These are the cross-family drop items every roster task (WP6/T5-T7) feeds
-- and every base recipe of WP7+ consumes. WORKING NAMES: the final naming
-- pass belongs to items_crafting.md, so nothing outside grug_mobs may hard-
-- code these ids yet — dispatch on the groups instead.
--
-- Groups:
--   grug_material = 1 — "this is a crafting material from a mob"
--   grug_leather  = 1 — the [leather] flag of §6/§3.1. The WP10 Leatherworker
--                       hook multiplies the dropped stack (professions.md §3
--                       "Leatherworker x5") for every drop-list entry in this
--                       group, so it must sit on the ITEM, not on the mob.
--                       NB mobs_redo's own `mobs:leather` is in our drop
--                       tables too and cannot carry the group without
--                       overriding a vendored item — the hook therefore has
--                       to special-case that one id (documented in VENDOR.md
--                       when WP10 lands).
--   grug_leather_grade = N — one rung of the Leatherworker's leather ladder
--                       (grug_professions/leatherworker.lua), so the price
--                       module pays it no more than the leather it is
--                       refined from.
--
-- Textures: 16px originals of this project (CC0), generated by
-- tools/gen_mob_item_textures.py — see LICENSE-media.md §6.

local function material(name, description, extra_groups)
	local groups = {grug_material = 1}
	if extra_groups then
		for k, v in pairs(extra_groups) do
			groups[k] = v
		end
	end
	core.register_craftitem("grug_mobs:" .. name, {
		description = description,
		inventory_image = "grug_mobs_item_" .. name .. ".png",
		groups = groups,
	})
end

-- Hides & pelts (§6 rows "light leather" / "heavy leather" / "scaled hide")
material("light_leather", "Light Leather", {grug_leather = 1, grug_leather_grade = 1}) -- L1-15 sources
material("heavy_leather", "Heavy Leather", {grug_leather = 1, grug_leather_grade = 3}) -- L25-60 sources
material("scaled_hide", "Scaled Hide", {grug_leather = 1, grug_leather_grade = 4}) -- crocodiles, serpents
-- Panther drop; §6 does NOT flag it [leather] (the panther's leather entry
-- carries that flag), so no grug_leather group here.
material("sleek_pelt", "Sleek Pelt")

-- Cloth line (§6 "linen cloth" / "heavy cloth"). Raw Silk keeps its old id:
-- spiders spin it, and T5/T6 outlaws carry it as stolen bales. Its catalogue
-- tier is 1 (band-1 spiderlings drop it, the fishing rod needs it); the
-- Tailor declares it a T4 ingredient (grug_professions/tailor.lua).
material("linen_scrap", "Linen Scrap")
material("linen_cloth", "Linen Cloth")
material("heavy_cloth", "Heavy Cloth")
material("spider_silk", "Raw Silk")

-- Alchemy reagents (§6 "alchemy reagents (mob)")
material("venom_gland", "Venom Gland")
material("venom_sac", "Venom Sac")
material("slime_gel", "Slime Gel")

-- Teeth, claws, feathers, misc
material("fang", "Fang")
material("bear_claw", "Bear Claw")
material("croc_tooth", "Crocodile Tooth")
material("raptor_claw", "Small Cat Claw") -- id kept from the old raptor; its sources are cats (Round 28 catalogue)
material("feather", "Feather")
material("sharp_feather", "Sharp Feather")
material("ape_hair", "Ape Hair")
material("shiny_scale", "Shiny Scale")
material("bone", "Bone")
material("stone_core", "Stone Core") -- golem drop, elite-only source

-- Skeleton-archer drop: the loot bundle, not the Scout's ammunition.
material("arrow", "Bundle of Arrows")

--
-- Food (WP6/T7)
--
-- The Mirefolk drop "fish 1/1" (§3.1 swamp row); §6 lists "meat/fish
-- everywhere" as a food source for both continents. mobs_redo ships meat but
-- no fish, so this is our own item. NOT registered through material() above:
-- it is food, not a crafting material, so it carries neither grug_material
-- nor a grug_leather flag.
--
-- Edibility follows the vendored convention exactly (mobs/crafts.lua): an
-- `on_use` item_eat plus mobs.add_eatable, which layers the {eatable,
-- flammable, food} groups on top — that is what makes the item usable by
-- mobs_redo's own food handling. Cooking (a fried-fish recipe) and the real
-- food/hunger balance belong to WP7, not here; 3 HP mirrors mobs:meat_raw.
core.register_craftitem("grug_mobs:raw_fish", {
	description = "Raw Fish",
	inventory_image = "grug_mobs_item_raw_fish.png",
	on_use = core.item_eat(3),
	groups = {food_fish_raw = 1},
})
mobs.add_eatable("grug_mobs:raw_fish", 3)
