-- Trash loot: exists only to be sold to traders (WP7).
-- _grug_sell_price = buy price in COPPER units (economy.md §1).

core.register_craftitem("grug_mobs:zombie_flesh", {
	description = "Rotting Flesh",
	inventory_image = "mobs_meat_raw.png^[multiply:#7fae6a",
	groups = {grug_trash_loot = 1},
	_grug_sell_price = 2,
})

core.register_craftitem("grug_mobs:boar_tusk", {
	description = "Boar Tusk",
	inventory_image = "mobs_leather.png^[multiply:#e8e0c8",
	groups = {grug_trash_loot = 1},
	_grug_sell_price = 1,
})

-- Bandit drop (items_crafting.md §8.1: "Bandit 'coin' drops become a stolen
-- purse trash item (5c)"). NOT currency and never will be: money is ONE
-- integer in player meta (economy.md §1), so this item has no on_use, no
-- money effect and nothing may convert it except a trader paying
-- _grug_sell_price for it like for any other trash drop.
core.register_craftitem("grug_mobs:stolen_purse", {
	description = "Stolen Purse",
	inventory_image = "grug_mobs_item_stolen_purse.png",
	groups = {grug_trash_loot = 1},
	_grug_sell_price = 5,
})

-- Faction-NPC PvP drop (items_crafting.md §5.6: "Faction NPC kills
-- additionally drop war trophies (vendor 5-10c)"). 1-2 per kill at 5c each
-- is what puts a kill inside that 5-10c band — the range lives in the DROP
-- COUNT (guard.lua), not in the item price.
core.register_craftitem("grug_mobs:war_trophy", {
	description = "War Trophy",
	inventory_image = "grug_mobs_item_war_trophy.png",
	groups = {grug_trash_loot = 1},
	_grug_sell_price = 5,
})

--
-- Shared mob materials (docs/design/biomes_mobs.md §6 base-material map).
--
-- These are the cross-family drop items every roster task (WP6/T5-T7) feeds
-- and every base recipe of WP7+ consumes. WORKING NAMES: the final naming
-- pass belongs to items_crafting.md, so nothing outside grug_mobs may hard-
-- code these ids yet — dispatch on the groups instead.
--
-- Groups:
--   grug_material = 1 — "this is a crafting material from a mob"
--   grug_leather  = 1 — the [leather] flag of §6/§3.1. The WP10 Leatherworker
--                       hook multiplies the dropped stack (professions.md §3
--                       "Leatherworker x5") for every drop-list entry in this
--                       group, so it must sit on the ITEM, not on the mob.
--                       NB mobs_redo's own `mobs:leather` is in our drop
--                       tables too and cannot carry the group without
--                       overriding a vendored item — the hook therefore has
--                       to special-case that one id (documented in VENDOR.md
--                       when WP10 lands).
--
-- _grug_sell_price is the trader buy price in COPPER (economy.md §1); the
-- scale follows the two trash items above: 1-3 = vendor trash, 2-8 = tier
-- material, roughly rising with the level band the source mob lives in.
--
-- Textures: 16px originals of this project (CC0), generated by
-- tools/gen_mob_item_textures.py — see LICENSE-media.md §6.

local function material(name, description, price, extra_groups)
	local groups = {grug_material = 1}
	if extra_groups then
		for k, v in pairs(extra_groups) do
			groups[k] = v
		end
	end
	core.register_craftitem("grug_mobs:" .. name, {
		description = description,
		inventory_image = "grug_mobs_item_" .. name .. ".png",
		groups = groups,
		_grug_sell_price = price,
	})
end

local LEATHER = {grug_leather = 1}

-- Hides & pelts (§6 rows "light leather" / "heavy leather" / "scaled hide")
material("light_leather", "Light Leather", 2, LEATHER) -- L1-15 sources
material("heavy_leather", "Heavy Leather", 6, LEATHER) -- L25-60 sources
material("scaled_hide", "Scaled Hide", 6, LEATHER) -- crocodiles, serpents
-- Panther drop; §6 does NOT flag it [leather] (the panther's leather entry
-- carries that flag), so no grug_leather group here.
material("sleek_pelt", "Sleek Pelt", 7)

-- Cloth line (§6 "linen cloth" / "heavy cloth")
material("linen_scrap", "Linen Scrap", 1)
material("linen_cloth", "Linen Cloth", 3)
material("heavy_cloth", "Heavy Cloth", 5)
material("spider_silk", "Spider Silk", 5) -- Tailor T3

-- Alchemy reagents (§6 "alchemy reagents (mob)")
material("venom_gland", "Venom Gland", 4)
material("venom_sac", "Venom Sac", 5)
material("slime_gel", "Slime Gel", 3)

-- Teeth, claws, feathers, misc
material("fang", "Fang", 3)
material("bear_claw", "Bear Claw", 6)
material("croc_tooth", "Crocodile Tooth", 5)
material("raptor_claw", "Raptor Claw", 5)
material("feather", "Feather", 1)
material("sharp_feather", "Sharp Feather", 4)
material("ape_hair", "Ape Hair", 4)
material("shiny_scale", "Shiny Scale", 4)
material("bone", "Bone", 1)
material("stone_core", "Stone Core", 7) -- golem drop, elite-only source

-- Skeleton-archer drop: pure vendor trash for now (there is no bow/quiver
-- item yet), hence the bundle framing and the trash-tier price.
material("arrow", "Bundle of Arrows", 2)

--
-- Food (WP6/T7)
--
-- The Mirefolk drop "fish 1/1" (§3.1 swamp row); §6 lists "meat/fish
-- everywhere" as a food source for both continents. mobs_redo ships meat but
-- no fish, so this is our own item. NOT registered through material() above:
-- it is food, not a crafting material, so it carries neither grug_material
-- nor a grug_leather flag.
--
-- Edibility follows the vendored convention exactly (mobs/crafts.lua): an
-- `on_use` item_eat plus mobs.add_eatable, which layers the {eatable,
-- flammable, food} groups on top — that is what makes the item usable by
-- mobs_redo's own food handling. Cooking (a fried-fish recipe) and the real
-- food/hunger balance belong to WP7, not here; 3 HP mirrors mobs:meat_raw.
core.register_craftitem("grug_mobs:raw_fish", {
	description = "Raw Fish",
	inventory_image = "grug_mobs_item_raw_fish.png",
	on_use = core.item_eat(3),
	groups = {food_fish_raw = 1},
	_grug_sell_price = 2,
})
mobs.add_eatable("grug_mobs:raw_fish", 3)
